// apps/vue-app/src/pages/AspectRatio/ratio-demo.vue
<script setup lang="ts">
import { AspectRatio } from '@fex-design/vue/primitive/aspect-ratio'
import Card from '@fex-design/vue/ui/card'
defineProps<{ title: string; description: string; ratio: number; sizeClass: string }>()
</script>
<template>
  <Card :title :description
    ><AspectRatio :ratio class="rounded-md" :class="sizeClass"
      ><img
        src="/aspect-ratio-demo.svg"
        alt="Mountain landscape"
        class="size-full object-cover" /></AspectRatio
  ></Card>
</template>

// apps/react-app/src/pages/AspectRatio/ratio-demo.tsx
import { AspectRatio } from '@fex-design/react/primitive/aspect-ratio'
import { Card } from '@fex-design/react/ui/card'

interface RatioDemoProps {
  title: string
  description: string
  ratio: number
  className: string
}
export function RatioDemo({ title, description, ratio, className }: RatioDemoProps) {
  return (
    <Card title={title} description={description}>
      <AspectRatio ratio={ratio} className={`rounded-md ${className}`}>
        <img
          src="/aspect-ratio-demo.svg"
          alt="Mountain landscape"
          className="size-full object-cover"
        />
      </AspectRatio>
    </Card>
  )
}
