// packages/components/vue/src/primitive/toast/toast-root.vue
<script setup lang="ts">
import { toastRootClassName, type ToastStyleProps } from '@fex/components-styles/toast'
import { cn } from '@fex/utils'
import { computed } from 'vue'
import { toast as defaultToast, type VueToastItem, type VueToastManager } from './toast-manager'

const props = defineProps<{ class?: string, manager?: VueToastManager, toast: VueToastItem }>()
const manager = computed(() => props.manager ?? defaultToast)
const variant = computed<NonNullable<ToastStyleProps['variant']>>(() => {
  const value = props.toast.variant
  return value === 'success' || value === 'info' || value === 'warning' || value === 'error' || value === 'loading' ? value : 'default'
})
</script>

<template>
  <div
    v-bind="$attrs"
    role="status"
    data-slot="toast"
    :data-paused="props.toast.paused ? '' : undefined"
    :data-variant="props.toast.variant"
    :class="cn(toastRootClassName({ variant }), props.class)"
    @pointerenter="manager.pause(props.toast.id)"
    @pointerleave="manager.resume(props.toast.id)"
  ><slot :toast="props.toast" :manager="manager" /></div>
</template>

// packages/components/svelte/src/primitive/toast/toast-root.svelte
<script lang="ts">
  import { toastRootClassName, type ToastStyleProps } from '@fex/components-styles/toast'
  import { cn } from '@fex/utils'
  import type { Snippet } from 'svelte'
  import type { HTMLAttributes } from 'svelte/elements'
  import { toast as defaultToast, type SvelteToastItem, type SvelteToastManager } from './toast'

  interface Props extends Omit<HTMLAttributes<HTMLDivElement>, 'class'> {
    children?: Snippet
    class?: string
    manager?: SvelteToastManager
    toast: SvelteToastItem
  }

  let { children, class: className, manager = defaultToast, toast, ...rest }: Props = $props()
  const variant = $derived(isKnownVariant(toast.variant) ? toast.variant : 'default')
  const classList = $derived(cn(toastRootClassName({ variant }), className))

  function isKnownVariant(variant: SvelteToastItem['variant']): variant is NonNullable<ToastStyleProps['variant']> {
    return variant === 'default' || variant === 'success' || variant === 'info' || variant === 'warning' || variant === 'error' || variant === 'loading'
  }
</script>

<div
  {...rest}
  data-paused={toast.paused ? '' : undefined}
  data-slot="toast"
  data-variant={toast.variant}
  role="status"
  class={classList}
  onpointerenter={() => manager.pause(toast.id)}
  onpointerleave={() => manager.resume(toast.id)}
>
  {@render children?.()}
</div>
