// packages/components/solid/src/primitive/dialog/dialog.tsx
import { createDialogController, type DialogOptions } from '@fex/components-core/dialog/create-dialog-controller'
import {
  dialogBodyClassName,
  dialogCloseClassName,
  dialogContentClassName,
  dialogDescriptionClassName,
  dialogFooterClassName,
  dialogHeaderClassName,
  dialogOverlayClassName,
  dialogTitleClassName,
  type DialogStyleProps,
} from '@fex/components-styles/dialog'
import { cn } from '@fex/utils'
import { Portal } from 'solid-js/web'
import {
  createSignal,
  onCleanup,
  Show,
  splitProps,
  type JSX,
  type ParentProps,
} from 'solid-js'
import { createCoreStoreSignal } from '../../primitives/create-core-store-signal'
import { DialogContext, useDialog } from './dialog-context'
let nextDialogId = 1

export interface DialogProps extends ParentProps, DialogOptions {}

export function Dialog(props: DialogProps) {
  const [local] = splitProps(props, ['children', 'open', 'defaultOpen', 'onOpenChange', 'modal', 'forceMount', 'closeDelay', 'dismiss', 'closeOnOverlayPointer'])
  const [open, setOpen] = createSignal(local.open ?? local.defaultOpen ?? false)
  const triggerElement = { current: null as HTMLButtonElement | null }
  const dialogId = nextDialogId++

  function makeOptions(openValue: boolean): DialogOptions {
    return {
      open: openValue,
      modal: local.modal ?? true,
      forceMount: local.forceMount,
      closeDelay: local.closeDelay ?? 140,
      dismiss: local.dismiss,
      closeOnOverlayPointer: local.closeOnOverlayPointer,
      onOpenChange(nextOpen, info) {
        if (local.open === undefined) {
          setOpen(nextOpen)
          dialog.setOptions(makeOptions(nextOpen))
        }
        local.onOpenChange?.(nextOpen, info)
      },
    }
  }

  function syncOptions() {
    dialog.setOptions(makeOptions(local.open ?? open()))
    return null
  }

  const dialog = createDialogController(makeOptions(open()))
  const snapshot = createCoreStoreSignal(dialog)

  onCleanup(() => dialog.destroy())

  return (
    <>
      {syncOptions()}
      <DialogContext.Provider
        value={{
          contentId: `fex-dialog-content-${dialogId}`,
          descriptionId: `fex-dialog-description-${dialogId}`,
          dialog,
          snapshot,
          titleId: `fex-dialog-title-${dialogId}`,
          triggerElement,
        }}
      >
        {local.children}
      </DialogContext.Provider>
    </>
  )
}

export type DialogTriggerRenderProps = {
  props: {
    'aria-controls': string | undefined
    'aria-expanded': boolean
    'aria-haspopup': 'dialog'
    'data-state': 'open' | 'closed'
    class: string | undefined
    onClick: JSX.EventHandlerUnion<HTMLButtonElement, MouseEvent>
    type: 'button'
  }
  ref: (element: HTMLButtonElement) => void
  state: ReturnType<ReturnType<typeof createDialogController>['getSnapshot']>
}

export interface DialogTriggerProps {
  children: (props: DialogTriggerRenderProps) => JSX.Element
  class?: string
}

export function DialogTrigger(props: DialogTriggerProps) {
  const [local] = splitProps(props, ['children', 'class'])
  const { contentId, dialog, snapshot, triggerElement } = useDialog('DialogTrigger')

  return local.children({
    ref: (element) => {
      triggerElement.current = element
    },
    state: snapshot(),
    props: {
      type: 'button',
      class: local.class,
      'aria-haspopup': 'dialog',
      'aria-expanded': snapshot().open,
      'aria-controls': snapshot().open ? contentId : undefined,
      'data-state': snapshot().open ? 'open' : 'closed',
      onClick: (event) => dialog.toggle({ reason: 'trigger-click', event }),
    },
  })
}

export interface DialogPortalProps extends ParentProps {
  container?: HTMLElement | null
  forceMount?: boolean
}

export function DialogPortal(props: DialogPortalProps) {
  const { snapshot } = useDialog('DialogPortal')
  return (
    <Show when={snapshot().mounted || props.forceMount}>
      <Portal mount={props.container ?? document.body}>{props.children}</Portal>
    </Show>
  )
}

export interface DialogOverlayProps {
  class?: string
}

export function DialogOverlay(props: DialogOverlayProps) {
  const [local] = splitProps(props, ['class'])
  const { dialog, snapshot } = useDialog('DialogOverlay')
  onCleanup(() => dialog.setOverlayElement(null))
  return (
    <div
      ref={(element) => dialog.setOverlayElement(element)}
      data-slot="dialog-overlay"
      data-state={snapshot().open ? 'open' : 'closed'}
      data-phase={snapshot().phase}
      class={cn(dialogOverlayClassName, local.class)}
      onClick={(event) => {
        if (event.target === event.currentTarget) {
          dialog.dismiss.overlayPointer({ target: event.target, currentTarget: event.currentTarget, event })
        }
      }}
    />
  )
}

export interface DialogContentProps extends ParentProps {
  class?: string
  size?: DialogStyleProps['size']
}

export function DialogContent(props: DialogContentProps) {
  const [local] = splitProps(props, ['children', 'class', 'size'])
  const { contentId, descriptionId, dialog, snapshot, titleId } = useDialog('DialogContent')
  onCleanup(() => dialog.setLayerElement(null))
  return (
    <Show when={snapshot().mounted}>
      <div
        ref={(element) => dialog.setLayerElement(element)}
        id={contentId}
        role="dialog"
        aria-modal="true"
        aria-labelledby={titleId}
        aria-describedby={descriptionId}
        tabIndex={-1}
        data-slot="dialog-content"
        data-state={snapshot().open ? 'open' : 'closed'}
        data-phase={snapshot().phase}
        class={cn(dialogContentClassName({ size: local.size }), local.class)}
        onKeyDown={(event) => {
          if (event.key === 'Escape') {
            dialog.dismiss.escapeKey({ target: event.target, currentTarget: event.currentTarget, event })
          }
        }}
      >
        {local.children}
      </div>
    </Show>
  )
}

function createPart(slot: string, className: string) {
  return function DialogPart(props: ParentProps<{ class?: string }>) {
    const [local, rest] = splitProps(props, ['children', 'class'])
    return <div {...rest} data-slot={slot} class={cn(className, local.class)}>{local.children}</div>
  }
}

export const DialogHeader = createPart('dialog-header', dialogHeaderClassName)
export const DialogBody = createPart('dialog-body', dialogBodyClassName)
export const DialogFooter = createPart('dialog-footer', dialogFooterClassName)

export function DialogTitle(props: ParentProps<{ class?: string }>) {
  const [local, rest] = splitProps(props, ['children', 'class'])
  const { titleId } = useDialog('DialogTitle')
  return <h2 {...rest} id={titleId} data-slot="dialog-title" class={cn(dialogTitleClassName, local.class)}>{local.children}</h2>
}

export function DialogDescription(props: ParentProps<{ class?: string }>) {
  const [local, rest] = splitProps(props, ['children', 'class'])
  const { descriptionId } = useDialog('DialogDescription')
  return <p {...rest} id={descriptionId} data-slot="dialog-description" class={cn(dialogDescriptionClassName, local.class)}>{local.children}</p>
}

export type DialogCloseRenderProps = {
  class: string
  onClick: JSX.EventHandlerUnion<HTMLButtonElement, MouseEvent>
  type: 'button'
  'data-slot': 'dialog-close'
}

export interface DialogCloseProps {
  children?: JSX.Element | ((props: DialogCloseRenderProps) => JSX.Element)
  class?: string
}

export function DialogClose(props: DialogCloseProps) {
  const [local, rest] = splitProps(props, ['children', 'class'])
  const { dialog } = useDialog('DialogClose')
  const closeProps = {
    ...rest,
    type: 'button' as const,
    'data-slot': 'dialog-close' as const,
    class: cn(dialogCloseClassName, local.class),
    onClick: (event: MouseEvent) => dialog.close({ reason: 'manual', source: 'close-button', event }),
  }

  return typeof local.children === 'function'
    ? local.children(closeProps)
    : <button {...closeProps}>{local.children ?? 'Close'}</button>
}

// packages/components/angular/src/primitive/dialog/dialog.ts
import { createDialogController } from '@fex/components-core/dialog/create-dialog-controller'
import type { DialogOptions } from '@fex/components-core/dialog/create-dialog-controller'
import {
  dialogBodyClassName,
  dialogContentClassName,
  dialogDescriptionClassName,
  dialogFooterClassName,
  dialogHeaderClassName,
  dialogOverlayClassName,
  dialogTitleClassName,
} from '@fex/components-styles/dialog'
import type { DialogStyleProps } from '@fex/components-styles/dialog'
import {
  ChangeDetectionStrategy,
  Component,
  Directive,
  ElementRef,
  EventEmitter,
  HostListener,
  Input,
  Output,
  inject,
} from '@angular/core'
import type { AfterViewInit, OnChanges, OnDestroy } from '@angular/core'
import { createCoreStoreSignal } from '../../signals/core-store-signal'
import { createHostClassName } from '../../signals/host-class'

let nextDialogId = 1

@Component({
  selector: 'fex-dialog',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content />',
})
export class Dialog implements OnChanges, OnDestroy {
  @Input() open?: boolean
  @Input() defaultOpen = false
  @Input() modal = true
  @Input() forceMount = false
  @Input() closeDelay = 140
  @Input() closeOnOverlayPointer = true
  @Input() dismiss?: DialogOptions['dismiss']
  @Output() openChange = new EventEmitter<boolean>()

  private localOpen = this.defaultOpen
  readonly contentId = `fex-dialog-content-${nextDialogId}`
  readonly titleId = `fex-dialog-title-${nextDialogId}`
  readonly descriptionId = `fex-dialog-description-${nextDialogId++}`
  triggerElement: HTMLButtonElement | null = null
  readonly dialog = createDialogController(this.createOptions())
  readonly snapshot = createCoreStoreSignal(this.dialog)

  private createOptions(): DialogOptions {
    return {
      open: this.open ?? this.localOpen,
      modal: this.modal,
      forceMount: this.forceMount,
      closeDelay: this.closeDelay,
      closeOnOverlayPointer: this.closeOnOverlayPointer,
      dismiss: this.dismiss,
      onOpenChange: (nextOpen) => {
        if (this.open === undefined) {
          this.localOpen = nextOpen
          this.syncOptions()
        }
        this.openChange.emit(nextOpen)
      },
    }
  }

  syncOptions() {
    this.dialog.setOptions(this.createOptions())
  }

  ngOnChanges() {
    this.syncOptions()
  }

  ngOnDestroy() {
    this.dialog.destroy()
  }
}

@Directive({
  selector: 'button[fexDialogTrigger]',
  standalone: true,
  host: {
    type: 'button',
    '[attr.aria-haspopup]': "'dialog'",
    '[attr.aria-expanded]': 'dialogRoot.snapshot().open',
    '[attr.aria-controls]': 'dialogRoot.snapshot().open ? dialogRoot.contentId : null',
    '[attr.data-state]': "dialogRoot.snapshot().open ? 'open' : 'closed'",
  },
})
export class DialogTrigger implements AfterViewInit {
  protected readonly dialogRoot = inject(Dialog)
  private readonly elementRef = inject<ElementRef<HTMLButtonElement>>(ElementRef)

  ngAfterViewInit() {
    this.dialogRoot.triggerElement = this.elementRef.nativeElement
  }

  @HostListener('click', ['$event'])
  click(event: MouseEvent) {
    this.dialogRoot.syncOptions()
    this.dialogRoot.dialog.toggle({ reason: 'trigger-click', event })
  }
}

@Component({
  selector: 'fex-dialog-portal',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content />',
})
export class DialogPortal {}

@Component({
  selector: 'fex-dialog-overlay',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    'data-slot': 'dialog-overlay',
    '[class]': 'hostClassName()',
    '[style.display]': "dialogRoot.snapshot().mounted ? null : 'none'",
    '[attr.data-state]': "dialogRoot.snapshot().open ? 'open' : 'closed'",
    '[attr.data-phase]': 'dialogRoot.snapshot().phase',
  },
  template: '',
})
export class DialogOverlay implements AfterViewInit, OnDestroy {
  protected readonly dialogRoot = inject(Dialog)
  private readonly elementRef = inject<ElementRef<HTMLDivElement>>(ElementRef)
  protected readonly hostClassName = createHostClassName(dialogOverlayClassName)

  ngAfterViewInit() {
    this.dialogRoot.dialog.setOverlayElement(this.elementRef.nativeElement)
  }

  ngOnDestroy() {
    this.dialogRoot.dialog.setOverlayElement(null)
  }

  @HostListener('click', ['$event'])
  click(event: MouseEvent) {
    if (event.target === event.currentTarget) {
      this.dialogRoot.dialog.dismiss.overlayPointer({
        target: event.target,
        currentTarget: event.currentTarget,
        event,
      })
    }
  }
}

@Component({
  selector: 'fex-dialog-content',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    role: 'dialog',
    tabindex: '-1',
    'data-slot': 'dialog-content',
    '[id]': 'dialogRoot.contentId',
    '[attr.aria-modal]': "'true'",
    '[attr.aria-labelledby]': 'dialogRoot.titleId',
    '[attr.aria-describedby]': 'dialogRoot.descriptionId',
    '[class]': 'hostClassName()',
    '[style.display]': "dialogRoot.snapshot().mounted ? null : 'none'",
    '[attr.data-state]': "dialogRoot.snapshot().open ? 'open' : 'closed'",
    '[attr.data-phase]': 'dialogRoot.snapshot().phase',
  },
  template: '<ng-content />',
})
export class DialogContent implements AfterViewInit, OnDestroy {
  @Input() size: DialogStyleProps['size'] = 'md'
  protected readonly dialogRoot = inject(Dialog)
  private readonly elementRef = inject<ElementRef<HTMLDivElement>>(ElementRef)
  protected readonly hostClassName = createHostClassName(() =>
    dialogContentClassName({ size: this.size }),
  )

  ngAfterViewInit() {
    this.dialogRoot.dialog.setLayerElement(this.elementRef.nativeElement)
  }

  ngOnDestroy() {
    this.dialogRoot.dialog.setLayerElement(null)
  }

  @HostListener('keydown', ['$event'])
  keydown(event: KeyboardEvent) {
    if (event.key === 'Escape') {
      this.dialogRoot.dialog.dismiss.escapeKey({
        target: event.target,
        currentTarget: event.currentTarget,
        event,
      })
    }
  }
}

@Component({
  selector: 'fex-dialog-header',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { '[class]': 'hostClassName()', 'data-slot': 'dialog-header' },
  template: '<ng-content />',
})
export class DialogHeader {
  protected readonly hostClassName = createHostClassName(dialogHeaderClassName)
}

@Component({
  selector: 'fex-dialog-title',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { '[id]': 'dialogRoot.titleId', '[class]': 'hostClassName()', 'data-slot': 'dialog-title' },
  template: '<ng-content />',
})
export class DialogTitle {
  protected readonly dialogRoot = inject(Dialog)
  protected readonly hostClassName = createHostClassName(dialogTitleClassName)
}

@Component({
  selector: 'fex-dialog-description',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[id]': 'dialogRoot.descriptionId',
    '[class]': 'hostClassName()',
    'data-slot': 'dialog-description',
  },
  template: '<ng-content />',
})
export class DialogDescription {
  protected readonly dialogRoot = inject(Dialog)
  protected readonly hostClassName = createHostClassName(dialogDescriptionClassName)
}

@Component({
  selector: 'fex-dialog-body',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { '[class]': 'hostClassName()', 'data-slot': 'dialog-body' },
  template: '<ng-content />',
})
export class DialogBody {
  protected readonly hostClassName = createHostClassName(dialogBodyClassName)
}

@Component({
  selector: 'fex-dialog-footer',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { '[class]': 'hostClassName()', 'data-slot': 'dialog-footer' },
  template: '<ng-content />',
})
export class DialogFooter {
  protected readonly hostClassName = createHostClassName(dialogFooterClassName)
}

@Directive({
  selector: 'button[fexDialogClose]',
  standalone: true,
  host: {
    type: 'button',
    'data-slot': 'dialog-close',
  },
})
export class DialogClose {
  protected readonly dialogRoot = inject(Dialog)

  @HostListener('click', ['$event'])
  click(event: MouseEvent) {
    this.dialogRoot.dialog.close({ reason: 'manual', source: 'close-button', event })
  }
}
