// apps/vue-admin/src/pages/Tooltip/disabled-demo.vue
<script setup lang="ts">
import { TooltipArrow, TooltipContent, TooltipPortal, TooltipRoot, TooltipTrigger } from '@fex/components-vue/primitive/tooltip'
import Button from '@fex/components-vue/ui/button'
</script>
<template><TooltipRoot><TooltipTrigger v-slot="slot"><span v-bind="slot.props" :ref="slot.ref" tabindex="0" class="inline-flex rounded-md focus-visible:ring-3 focus-visible:ring-focus/50"><Button disabled class="pointer-events-none" variant="outline">Disabled</Button></span></TooltipTrigger><TooltipPortal><TooltipContent>This feature is currently unavailable<TooltipArrow /></TooltipContent></TooltipPortal></TooltipRoot></template>

// apps/svelte-admin/src/routes/tooltip/disabled-demo.svelte
<script lang="ts">
  import TooltipRoot from '@fex/components-svelte/primitive/tooltip'
  import TooltipArrow from '@fex/components-svelte/primitive/tooltip-arrow'
  import TooltipContent from '@fex/components-svelte/primitive/tooltip-content'
  import TooltipPortal from '@fex/components-svelte/primitive/tooltip-portal'
  import TooltipTrigger from '@fex/components-svelte/primitive/tooltip-trigger'
  import Button from '@fex/components-svelte/ui/button'
</script>
<TooltipRoot><TooltipTrigger>{#snippet children(slot)}<span {...slot.props} use:slot.action tabindex="0" class="inline-flex rounded-md focus-visible:ring-3 focus-visible:ring-focus/50"><Button disabled class="pointer-events-none" variant="outline">Disabled</Button></span>{/snippet}</TooltipTrigger><TooltipPortal><TooltipContent>This feature is currently unavailable<TooltipArrow /></TooltipContent></TooltipPortal></TooltipRoot>
