// packages/@fex-design/angular/src/primitive/card/card.ts
import {
  cardClassName,
  cardContentClassName,
  cardDescriptionClassName,
  cardFooterClassName,
  cardHeaderClassName,
  cardTitleClassName,
} from '@fex-design/styles/card'
import { ChangeDetectionStrategy, Component } from '@angular/core'
import { createHostClassName } from '../../signals/host-class'

@Component({
  selector: 'fex-card-primitive',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'hostClassName()',
    'data-slot': 'card',
  },
  template: '<ng-content />',
})
export class Card {
  protected readonly hostClassName = createHostClassName(cardClassName)
}

@Component({
  selector: 'fex-card-header',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'hostClassName()',
    'data-slot': 'card-header',
  },
  template: '<ng-content />',
})
export class CardHeader {
  protected readonly hostClassName = createHostClassName(cardHeaderClassName)
}

@Component({
  selector: 'fex-card-title',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'hostClassName()',
    'data-slot': 'card-title',
  },
  template: '<ng-content />',
})
export class CardTitle {
  protected readonly hostClassName = createHostClassName(cardTitleClassName)
}

@Component({
  selector: 'fex-card-description',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'hostClassName()',
    'data-slot': 'card-description',
  },
  template: '<ng-content />',
})
export class CardDescription {
  protected readonly hostClassName = createHostClassName(cardDescriptionClassName)
}

@Component({
  selector: 'fex-card-content',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'hostClassName()',
    'data-slot': 'card-content',
  },
  template: '<ng-content />',
})
export class CardContent {
  protected readonly hostClassName = createHostClassName(cardContentClassName)
}

@Component({
  selector: 'fex-card-footer',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'hostClassName()',
    'data-slot': 'card-footer',
  },
  template: '<ng-content />',
})
export class CardFooter {
  protected readonly hostClassName = createHostClassName(cardFooterClassName)
}

// packages/@fex-design/react/src/primitive/card/card.tsx
import {
  cardActionClassName,
  cardClassName,
  cardContentClassName,
  cardDescriptionClassName,
  cardFooterClassName,
  cardHeaderClassName,
  cardTitleClassName,
} from '@fex-design/styles/card'
import { cn } from '@fex/utils'
import { type ComponentProps } from 'react'

export function Card({ className, ...props }: ComponentProps<'div'>) {
  return <div data-slot="card" className={cn(cardClassName, className)} {...props} />
}
export function CardHeader({ className, ...props }: ComponentProps<'div'>) {
  return <div data-slot="card-header" className={cn(cardHeaderClassName, className)} {...props} />
}
export function CardTitle({ className, ...props }: ComponentProps<'div'>) {
  return <div data-slot="card-title" className={cn(cardTitleClassName, className)} {...props} />
}
export function CardDescription({ className, ...props }: ComponentProps<'div'>) {
  return (
    <div
      data-slot="card-description"
      className={cn(cardDescriptionClassName, className)}
      {...props}
    />
  )
}
export function CardAction({ className, ...props }: ComponentProps<'div'>) {
  return <div data-slot="card-action" className={cn(cardActionClassName, className)} {...props} />
}
export function CardContent({ className, ...props }: ComponentProps<'div'>) {
  return <div data-slot="card-content" className={cn(cardContentClassName, className)} {...props} />
}
export function CardFooter({ className, ...props }: ComponentProps<'div'>) {
  return <div data-slot="card-footer" className={cn(cardFooterClassName, className)} {...props} />
}
