// packages/components/react/src/primitive/input/input.tsx
import {
  inputAddonAfterClassName,
  inputAddonBeforeClassName,
  inputClearClassName,
  inputControlClassName,
  inputPrefixClassName,
  inputRootClassName,
  inputSuffixClassName,
} from '@fex/components-styles/input'
import { cn } from '@fex/utils'
import {
  type ChangeEvent,
  type ComponentProps,
  type HTMLAttributes,
  type MouseEvent,
  type PointerEvent,
  type ReactNode,
  type Ref,
} from 'react'
import { CloseIcon } from '../../icon/close'
import { useComposedRef } from '../../hooks/use-composed-ref'
import { Button } from '../button/button'
import { InputContext, useInputContext } from './input-context'
import { useInput, type UseInputOptions } from './use-input'

export interface InputRootProps
  extends Omit<HTMLAttributes<HTMLDivElement>, 'defaultValue' | 'onChange'>, UseInputOptions {
  invalid?: boolean
  status?: 'error' | 'warning' | undefined
  ref?: Ref<HTMLDivElement> | undefined
}

export function InputRoot({
  value,
  defaultValue,
  disabled,
  readOnly,
  invalid = false,
  status,
  'aria-invalid': ariaInvalid,
  onValueChange,
  onClear,
  className,
  ref,
  children,
  ...props
}: InputRootProps) {
  const resolvedInvalid = invalid || status === 'error' || ariaInvalid === true || ariaInvalid === 'true'
  const input = useInput({
    value,
    defaultValue,
    disabled,
    readOnly,
    invalid: resolvedInvalid,
    onValueChange,
    onClear,
  })

  return (
    <InputContext value={input}>
      <div
        {...props}
        ref={ref}
        data-slot="input-root"
        data-disabled={input.disabled ? 'true' : undefined}
        data-readonly={input.readOnly ? 'true' : undefined}
        data-invalid={input.invalid ? 'true' : undefined}
        data-status={status}
        className={cn(inputRootClassName, className)}
      >
        {children}
      </div>
    </InputContext>
  )
}

export interface InputControlProps extends ComponentProps<'input'> {
  ref?: Ref<HTMLInputElement> | undefined
}

export function InputControl({
  className,
  disabled,
  readOnly,
  'aria-invalid': ariaInvalid,
  onChange,
  ref,
  ...props
}: InputControlProps) {
  const context = useInputContext('InputControl')
  const composedRef = useComposedRef(ref, context.focusRef)

  return (
    <input
      {...props}
      ref={composedRef}
      value={context.value}
      disabled={context.disabled || disabled}
      readOnly={context.readOnly || readOnly}
      aria-invalid={ariaInvalid ?? (context.invalid || undefined)}
      data-slot="input-control"
      className={cn(inputControlClassName, className)}
      onChange={(event: ChangeEvent<HTMLInputElement>) => {
        onChange?.(event)
        if (!event.defaultPrevented) {
          context.setValue(event.currentTarget.value, { reason: 'input', event })
        }
      }}
    />
  )
}

export interface InputPrefixProps extends ComponentProps<'span'> {
  ref?: Ref<HTMLSpanElement> | undefined
}

export function InputPrefix({ className, ref, ...props }: InputPrefixProps) {
  return (
    <span
      {...props}
      ref={ref}
      data-slot="input-prefix"
      className={cn(inputPrefixClassName, className)}
    />
  )
}

export interface InputSuffixProps extends ComponentProps<'span'> {
  ref?: Ref<HTMLSpanElement> | undefined
}

export function InputSuffix({ className, ref, ...props }: InputSuffixProps) {
  return (
    <span
      {...props}
      ref={ref}
      data-slot="input-suffix"
      className={cn(inputSuffixClassName, className)}
    />
  )
}

export interface InputAddonBeforeProps extends ComponentProps<'span'> {
  ref?: Ref<HTMLSpanElement> | undefined
}

export function InputAddonBefore({ className, ref, ...props }: InputAddonBeforeProps) {
  return (
    <span
      {...props}
      ref={ref}
      data-slot="input-addon-before"
      className={cn(inputAddonBeforeClassName, className)}
    />
  )
}

export interface InputAddonAfterProps extends ComponentProps<'span'> {
  ref?: Ref<HTMLSpanElement> | undefined
}

export function InputAddonAfter({ className, ref, ...props }: InputAddonAfterProps) {
  return (
    <span
      {...props}
      ref={ref}
      data-slot="input-addon-after"
      className={cn(inputAddonAfterClassName, className)}
    />
  )
}

export interface InputClearProps extends Omit<ComponentProps<'button'>, 'type'> {
  forceMount?: boolean
  ref?: Ref<HTMLButtonElement> | undefined
  children?: ReactNode
}

export interface InputClearButtonProps extends Omit<ComponentProps<'button'>, 'type'> {
  ref?: Ref<HTMLButtonElement> | undefined
  children?: ReactNode
  'data-slot'?: string | undefined
}

export function InputClearButton({
  className,
  children,
  'aria-label': ariaLabel = 'Clear input',
  'data-slot': dataSlot = 'input-clear',
  onPointerDown,
  ref,
  ...props
}: InputClearButtonProps) {
  return (
    <Button
      {...props}
      ref={ref}
      type="button"
      aria-label={ariaLabel}
      data-slot={dataSlot}
      className={cn(inputClearClassName, className)}
      onPointerDown={(event: PointerEvent<HTMLButtonElement>) => {
        onPointerDown?.(event)
        if (!event.defaultPrevented) event.preventDefault()
      }}
    >
      {children ?? <CloseIcon />}
    </Button>
  )
}

export function InputClear({
  forceMount = false,
  className,
  children,
  'aria-label': ariaLabel = 'Clear input',
  onPointerDown,
  onClick,
  ref,
  ...props
}: InputClearProps) {
  const input = useInputContext('InputClear')
  if (!forceMount && !input.canClear) return null

  return (
    <InputClearButton
      {...props}
      ref={ref}
      aria-label={ariaLabel}
      data-visible={input.canClear ? 'true' : 'false'}
      disabled={!input.canClear}
      className={className}
      onPointerDown={onPointerDown}
      onClick={(event: MouseEvent<HTMLButtonElement>) => {
        onClick?.(event)
        if (!event.defaultPrevented) input.clear()
      }}
    >
      {children}
    </InputClearButton>
  )
}

// packages/components/solid/src/primitive/input/input.tsx
import { inputAddonAfterClassName, inputAddonBeforeClassName, inputClearClassName, inputControlClassName, inputPrefixClassName, inputRootClassName, inputSuffixClassName } from '@fex/components-styles/input'
import { cn } from '@fex/utils'
import { createContext, splitProps, type JSX, type ParentProps, useContext } from 'solid-js'
import { CloseIcon } from '../../icon/close'
import { Button } from '../button/button'
import { createInput, type InputChangeReason } from './create-input'

type InputContextValue = ReturnType<typeof createInput>
const InputContext = createContext<InputContextValue>()

export interface InputRootProps extends ParentProps<JSX.HTMLAttributes<HTMLDivElement>> { value?: string | undefined; defaultValue?: string | undefined; disabled?: boolean | undefined; readOnly?: boolean | undefined; invalid?: boolean | undefined; status?: 'error' | 'warning' | undefined; onValueChange?: ((value: string, meta: { reason: InputChangeReason; event?: InputEvent }) => void) | undefined; onClear?: (() => void) | undefined }
export function InputRoot(props: InputRootProps) {
  const [local, rest] = splitProps(props, ['children', 'class', 'value', 'defaultValue', 'disabled', 'readOnly', 'invalid', 'status', 'onValueChange', 'onClear'])
  const input = createInput({ value: () => props.value, defaultValue: props.defaultValue, disabled: () => props.disabled, readOnly: () => props.readOnly, invalid: () => props.invalid || props.status === 'error', onValueChange: (value, meta) => props.onValueChange?.(value, meta), onClear: () => props.onClear?.() })
  return <InputContext.Provider value={input}><div {...rest} data-slot="input-root" data-disabled={input.disabled() || undefined} data-readonly={input.readOnly() || undefined} data-invalid={input.invalid() || undefined} data-status={local.status} class={cn(inputRootClassName, local.class)}>{local.children}</div></InputContext.Provider>
}

function useInputContext(name: string) { const context = useContext(InputContext); if (!context) throw new Error(`${name} must be used inside InputRoot.`); return context }
export function InputControl(props: JSX.InputHTMLAttributes<HTMLInputElement>) {
  const context = useInputContext('InputControl')
  const [local, rest] = splitProps(props, ['class', 'onInput', 'ref', 'disabled', 'readOnly', 'aria-invalid'])
  return <input {...rest} ref={(node) => { context.setFocusElement(node); if (typeof local.ref === 'function') local.ref(node) }} value={context.value()} disabled={context.disabled() || local.disabled} readOnly={context.readOnly() || local.readOnly} aria-invalid={local['aria-invalid'] ?? (context.invalid() || undefined)} data-slot="input-control" class={cn(inputControlClassName, local.class)} onInput={(event) => { if (typeof local.onInput === 'function') local.onInput(event); if (!event.defaultPrevented) context.setValue(event.currentTarget.value, 'input', event) }} />
}
function part(slot: string, className: string) { return (props: ParentProps<JSX.HTMLAttributes<HTMLSpanElement>>) => <span {...props} data-slot={slot} class={cn(className, props.class)}>{props.children}</span> }
export const InputPrefix = part('input-prefix', inputPrefixClassName)
export const InputSuffix = part('input-suffix', inputSuffixClassName)
export const InputAddonBefore = part('input-addon-before', inputAddonBeforeClassName)
export const InputAddonAfter = part('input-addon-after', inputAddonAfterClassName)
export function InputClear(props: ParentProps<JSX.ButtonHTMLAttributes<HTMLButtonElement>> & { forceMount?: boolean }) {
  const context = useInputContext('InputClear')
  const [local, rest] = splitProps(props, ['forceMount', 'class', 'children', 'onPointerDown', 'onClick'])
  return (local.forceMount || context.canClear()) ? <Button {...rest} type="button" data-slot="input-clear" disabled={!local.forceMount && !context.canClear()} class={cn(inputClearClassName, local.class)} onPointerDown={(event) => { if (typeof local.onPointerDown === 'function') local.onPointerDown(event); if (!event.defaultPrevented) event.preventDefault() }} onClick={(event) => { if (typeof local.onClick === 'function') local.onClick(event); if (!event.defaultPrevented) context.clear() }}>{local.children ?? <CloseIcon />}</Button> : null
}
