// packages/@fex-design/vue/src/primitive/context-menu/context-menu-portal.vue
<script setup lang="ts">
import { Teleport } from 'vue'
import { useContextMenuContext } from './context'
const props = defineProps<{ to?: string | HTMLElement }>()
const { controller, snapshot } = useContextMenuContext('ContextMenuPortal')
</script>
<template><Teleport v-if="snapshot.overlay.mounted" :to="props.to ?? controller.overlay.resolvePopupContainer() ?? 'body'"><slot /></Teleport></template>

// packages/@fex-design/svelte/src/primitive/context-menu/context-menu-portal.svelte
<script lang="ts">
  import type { Snippet } from 'svelte'
  import { getContext } from 'svelte'
  import { contextMenuContextKey, type ContextMenuContext } from './context-menu-context'
  let { children, container }: { children?: Snippet; container?: HTMLElement | null } = $props()
  const { controller, snapshot } = getContext<ContextMenuContext>(contextMenuContextKey)
  function portalAction(element: HTMLDivElement) {
    const target = container ?? controller.overlay.resolvePopupContainer() ?? document.body
    target.appendChild(element)
    return { destroy() { element.remove() } }
  }
</script>
{#if $snapshot.overlay.mounted}
  <div use:portalAction data-slot="context-menu-portal" style="display: contents">
    {@render children?.()}
  </div>
{/if}
