// packages/@fex-design/vue/src/primitive/pagination/pagination-previous.vue
﻿<script setup lang="ts">
import { paginationTextClassName } from '@fex-design/styles/pagination'
import { ChevronLeftIcon } from '../../icon/chevron'
import PaginationLink from './pagination-link.vue'

withDefaults(defineProps<{ text?: string }>(), { text: 'Previous' })
</script>

<template>
  <PaginationLink v-bind="$attrs" aria-label="Go to previous page" size="default">
    <ChevronLeftIcon />
    <span :class="paginationTextClassName">{{ text }}</span>
  </PaginationLink>
</template>

// packages/@fex-design/svelte/src/primitive/pagination/pagination-previous.svelte
<script lang="ts">
  import { paginationLinkClassName, paginationTextClassName, paginationTextLinkClassName } from '@fex-design/styles/pagination'
  import { cn } from '@fex/utils'
  import type { HTMLAnchorAttributes } from 'svelte/elements'
  import ChevronLeftIcon from '../../icon/chevron-left.svelte'
  interface Props extends Omit<HTMLAnchorAttributes, 'class'> { class?: string | undefined; text?: string }
  let { class: className, text = 'Previous', ...rest }: Props = $props()
  const classList = $derived(cn(paginationLinkClassName, paginationTextLinkClassName, className))
</script>
<a {...rest} aria-label="Go to previous page" data-slot="pagination-link" class={classList}><ChevronLeftIcon /><span class={paginationTextClassName}>{text}</span></a>
