// apps/solid-admin/src/pages/Avatar/group-demo.tsx
import { Avatar, AvatarFallback, AvatarGroup } from '@fex-design/solid/primitive/avatar'
import { Card } from '@fex-design/solid/ui/card'
import { For } from 'solid-js'
export function GroupDemo() {
  return <Card title="Avatar group" description="Keep the first avatars visible and summarize the rest."><AvatarGroup maxCount={3}><For each={['AM', 'BL', 'CS', 'DT', 'ER']}>{(name) => <Avatar><AvatarFallback>{name}</AvatarFallback></Avatar>}</For></AvatarGroup></Card>
}

// apps/react-admin/src/pages/Avatar/group-demo.tsx
import { Avatar, AvatarFallback, AvatarGroup } from '@fex-design/react/primitive/avatar'
import { Card } from '@fex-design/react/ui/card'

export function GroupDemo() {
  return (
    <Card title="Avatar group" description="Keep the first avatars visible and summarize the rest.">
      <AvatarGroup maxCount={3}>
        {['AM', 'BL', 'CS', 'DT', 'ER'].map((name) => <Avatar key={name}><AvatarFallback>{name}</AvatarFallback></Avatar>)}
      </AvatarGroup>
    </Card>
  )
}
