// apps/vue-app/src/pages/Menu/menubar-demo.vue
<script setup lang="ts">
import { DropdownContent } from '@fex-design/vue/primitive/dropdown'
import { MenuItem, MenuList, MenuRoot } from '@fex-design/vue/primitive/menu'
import { PopoverPortal, PopoverRoot, PopoverTrigger } from '@fex-design/vue/primitive/popover'
import { mergeProps } from 'vue'
import {
  horizontalListClassName,
  popupClassName,
  verticalItemClassName,
  verticalListClassName,
  menubarClassName,
  menubarTriggerClassName,
} from './demo-styles'

const menus = [
  { name: 'File', items: ['New file', 'Open…', 'Save'] },
  { name: 'Edit', items: ['Undo', 'Redo', 'Find'] },
  { name: 'View', items: ['Zoom in', 'Zoom out', 'Full screen'] },
  { name: 'Profiles', items: ['Andy', 'Benoit', 'Add Profile…'] },
]
</script>

<template>
  <MenuRoot role="menubar" aria-label="Editor commands" :class="menubarClassName">
    <MenuList orientation="horizontal" :class="horizontalListClassName">
      <PopoverRoot v-for="menu in menus" :key="menu.name" :trigger="['click']" side="bottom" align="start">
        <PopoverTrigger v-slot="popover">
          <MenuItem :value="menu.name" submenu>
            <template #trigger="slot">
              <button v-bind="mergeProps(slot.props, popover.props)" :ref="popover.ref" aria-haspopup="menu" :class="menubarTriggerClassName">{{ menu.name }}</button>
            </template>
          </MenuItem>
        </PopoverTrigger>
        <PopoverPortal>
          <DropdownContent :class="popupClassName">
            <MenuList orientation="vertical" :parent-value="menu.name" :class="verticalListClassName">
              <MenuItem v-for="item in menu.items" :key="item" :value="`${menu.name}-${item}`" :class="verticalItemClassName">{{ item }}</MenuItem>
            </MenuList>
          </DropdownContent>
        </PopoverPortal>
      </PopoverRoot>
    </MenuList>
  </MenuRoot>
</template>

// apps/angular-app/src/pages/menu/menubar-demo.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core'
import { DropdownContent } from '@fex-design/angular/primitive/dropdown'
import { MenuItem, MenuList, MenuRoot } from '@fex-design/angular/primitive/menu'
import { Popover, PopoverPortal, PopoverTrigger } from '@fex-design/angular/primitive/popover'
import { horizontalListClassName, menubarClassName, menubarTriggerClassName, popupClassName, verticalItemClassName, verticalListClassName } from './demo-styles'
@Component({ selector: 'app-menu-menubar-demo', standalone: true, imports: [MenuRoot, MenuList, MenuItem, Popover, PopoverTrigger, PopoverPortal, DropdownContent], changeDetection: ChangeDetectionStrategy.OnPush, templateUrl: './menubar-demo.component.html' })
export class MenuMenubarDemoComponent {
  protected readonly menus = [{ name: 'File', items: ['New Tab', 'New Window', 'Print…'] }, { name: 'Edit', items: ['Undo', 'Redo', 'Copy', 'Paste'] }, { name: 'View', items: ['Reload', 'Fullscreen'] }, { name: 'Profiles', items: ['Andy', 'Benoit', 'Add Profile…'] }]
  protected readonly rootClassName = menubarClassName; protected readonly horizontalListClassName = horizontalListClassName; protected readonly horizontalItemClassName = menubarTriggerClassName; protected readonly verticalListClassName = verticalListClassName; protected readonly verticalItemClassName = verticalItemClassName; protected readonly popupClassName = popupClassName
}
