// packages/@fex-design/svelte/src/primitive/tree-select/tree-select-root.svelte
<script lang="ts">
  import { createTreeSelectController } from '@fex-design/core/tree-select/create-tree-select-controller'
  import type { TreeSelectItem, TreeSelectValue } from '@fex-design/core/tree-select/types'
  import type { Snippet } from 'svelte'
  import { setContext } from 'svelte'
  import { readableCoreStore } from '../../stores/core-store'
  import Popover from '../popover/popover.svelte'
  import { treeSelectContextKey, type TreeSelectContext } from './context'
  interface Props {
    children?: Snippet<[{ controller: ReturnType<typeof createTreeSelectController>; state: ReturnType<ReturnType<typeof createTreeSelectController>['getSnapshot']> }]>
    items?: readonly TreeSelectItem[]
    value?: TreeSelectValue | readonly TreeSelectValue[] | undefined
    defaultValue?: TreeSelectValue | readonly TreeSelectValue[] | undefined
    multiple?: boolean
    disabled?: boolean
    searchable?: boolean
    searchValue?: string | undefined
    defaultSearchValue?: string
    open?: boolean
    defaultOpen?: boolean
    onChange?: (value: TreeSelectValue | TreeSelectValue[] | undefined, meta: Record<string, unknown>) => void
    onSearchValueChange?: (value: string) => void
    onOpenChange?: (open: boolean, info: unknown) => void
  }
  let { children, items, value, defaultValue, multiple = false, disabled = false, searchable = false, searchValue, defaultSearchValue = '', open, defaultOpen, onChange, onSearchValueChange, onOpenChange }: Props = $props()
  let localSearch = $state(defaultSearchValue)
  let localOpen = $state(defaultOpen ?? false)
  const controller = createTreeSelectController({
    get items() { return items }, get value() { return value }, get defaultValue() { return defaultValue },
    get multiple() { return multiple }, get disabled() { return disabled },
    onChange(next, meta) { onChange?.(next, meta) },
  })
  const snapshot = readableCoreStore(controller)
  $effect(() => controller.updateOptions({ items, value, multiple, disabled }))
  function setSearchValue(next: string) {
    if (searchValue === undefined) localSearch = next
    onSearchValueChange?.(next)
  }
  function requestOpen(next: boolean) {
    if (open === undefined) localOpen = next
    onOpenChange?.(next, { source: 'trigger' })
  }
  setContext<TreeSelectContext>(treeSelectContextKey, {
    controller, snapshot, searchable: () => searchable,
    searchValue: () => searchValue ?? localSearch, setSearchValue,
    openPanel: () => requestOpen(true), closePanel: () => requestOpen(false),
  })
</script>
<Popover open={open ?? localOpen} trigger={[]} onOpenChange={(next, info) => { if (open === undefined) localOpen = next; onOpenChange?.(next, info) }}>
  {@render children?.({ controller, state: $snapshot })}
</Popover>

// packages/@fex-design/vue/src/primitive/tree-select/tree-select-root.vue
<script setup lang="ts">
import { createTreeSelectController } from '@fex-design/core/tree-select/create-tree-select-controller'
import type { TreeSelectItem, TreeSelectValue } from '@fex-design/core/tree-select/types'
import { computed, provide, ref, watchEffect } from 'vue'
import { useCoreStore } from '../../composables/use-core-store'
import PopoverRoot from '../popover/popover-root.vue'
import { treeSelectKey } from './context'

const props = withDefaults(defineProps<{
  items?: readonly TreeSelectItem[] | undefined
  value?: TreeSelectValue | readonly TreeSelectValue[] | undefined
  defaultValue?: TreeSelectValue | readonly TreeSelectValue[] | undefined
  multiple?: boolean
  disabled?: boolean
  searchable?: boolean
  searchValue?: string | undefined
  defaultSearchValue?: string
  open?: boolean
  defaultOpen?: boolean
}>(), { multiple: false, disabled: false, searchable: false })
const emit = defineEmits<{
  change: [value: TreeSelectValue | TreeSelectValue[] | undefined, meta: unknown]
  searchValueChange: [value: string]
  openChange: [value: boolean, info: unknown]
}>()
const controller = createTreeSelectController({
  get items() { return props.items },
  get value() { return props.value },
  get defaultValue() { return props.defaultValue },
  get multiple() { return props.multiple },
  get disabled() { return props.disabled },
  onChange(value, meta) { emit('change', value, meta) },
})
const store = useCoreStore(controller)
const snapshot = computed(() => { void props.value; void props.multiple; void store.value; return controller.getSnapshot() })
const localSearchValue = ref(props.defaultSearchValue ?? '')
const localOpen = ref(props.defaultOpen ?? false)
const resolvedOpen = computed(() => props.open ?? localOpen.value)
const searchValue = computed({
  get: () => props.searchValue ?? localSearchValue.value,
  set: (value) => {
    if (props.searchValue === undefined) localSearchValue.value = value
    emit('searchValueChange', value)
  },
})
function requestOpen(value: boolean) {
  if (props.open === undefined) localOpen.value = value
  emit('openChange', value, { source: 'trigger' })
}
watchEffect(() => controller.updateOptions({
  items: props.items,
  value: props.value,
  multiple: props.multiple,
  disabled: props.disabled,
}))
provide(treeSelectKey, {
  controller,
  snapshot,
  searchable: computed(() => props.searchable),
  searchValue,
  setSearchValue: (value) => { searchValue.value = value },
  openPanel: () => requestOpen(true),
  closePanel: () => requestOpen(false),
  togglePanel: () => requestOpen(!resolvedOpen.value),
})
function handleOpenChange(value: boolean, info: unknown) { if (props.open === undefined) localOpen.value = value; emit('openChange', value, info) }
defineExpose({ controller, registerItem: (item: TreeSelectItem) => controller.registerItem(item) })
</script>
<template>
  <PopoverRoot :open="resolvedOpen" :disabled="disabled" @open-change="handleOpenChange">
    <slot :controller="controller" :state="snapshot" />
  </PopoverRoot>
</template>
