// packages/components/svelte/src/primitive/date-picker/date-picker-cancel.svelte
<script lang="ts">
  import type { Snippet } from 'svelte'
  import { datePickerCancelClassName } from '@fex/components-styles/date-picker'
  import Button from '../button/button.svelte'
  import { useFooterOwner } from './date-picker-footer.svelte'
  interface Props { children?: Snippet }
  let { children }: Props = $props()
  const owner = useFooterOwner()
</script>

<Button data-slot="date-picker-cancel" class={datePickerCancelClassName} onclick={() => owner.cancel()}>
  {#if children}{@render children()}{:else}取消{/if}
</Button>

// packages/@fex-design/vue/src/primitive/date-picker/date-picker-cancel.vue
<script setup lang="ts">
import { datePickerCancelClassName } from '@fex-design/styles/date-picker'
import Button from '../button/button.vue'
import { createDatePickerFooterActions } from './date-picker-footer.vue'

const owner = createDatePickerFooterActions()
</script>

<template>
  <Button data-slot="date-picker-cancel" :class="datePickerCancelClassName" @click="owner.cancel()">
    <slot>取消</slot>
  </Button>
</template>
