// apps/react-admin/src/pages/Upload/multiple-demo.tsx
import { uploadFeature } from '@fex/components-core/upload/features/upload'
import { UploadRoot, UploadTrigger, useUpload } from '@fex/components-react/primitive/upload'
import { Button } from '@fex/components-react/ui/button'
import { uploadBody, uploadServerUrl } from './api'
import { DemoUploadList } from './demo-list'
import { UploadDemoSection } from './demo-section'

export function MultipleUploadDemo() {
  const upload = useUpload({
    multiple: true,
    autoUpload: false,
    features: [
      uploadFeature({
        request: ({ file, signal, onProgress }) =>
          uploadBody(`${uploadServerUrl}/upload`, file, {
            fileName: file.name,
            signal,
            onProgress,
          }),
      }),
    ],
  })
  return (
    <UploadDemoSection
      title="多文件手动上传"
      description="一次选择多个文件，可逐个上传，也可以手动启动整个文件队列。"
    >
      <UploadRoot controller={upload}>
        <div className="flex gap-space-sm">
          <UploadTrigger>{({ props }) => <Button {...props}>选择多个文件</Button>}</UploadTrigger>
          <Button
            variant="outline"
            onClick={() =>
              void upload
                .getFeature<import('@fex/components-core/upload/types').UploadFeatureApi>('upload')
                ?.startAll()
            }
          >
            全部上传
          </Button>
        </div>
        <DemoUploadList />
      </UploadRoot>
    </UploadDemoSection>
  )
}

// apps/angular-admin/src/pages/upload/multiple-demo.component.ts
import { uploadFeature } from '@fex/components-core/upload/features/upload'
import type { UploadFeatureApi } from '@fex/components-core/upload/types'
import {
  UploadRoot,
  UploadTrigger,
  createUploadSignals,
} from '@fex/components-angular/primitive/upload'
import { Button } from '@fex/components-angular/ui/button'
import { ChangeDetectionStrategy, Component } from '@angular/core'
import { uploadBody, uploadServerUrl } from './api'
import { DemoUploadListComponent } from './demo-list.component'
import { UploadDemoSectionComponent } from './demo-section.component'
@Component({
  selector: 'fex-multiple-upload-demo',
  standalone: true,
  imports: [UploadDemoSectionComponent, UploadRoot, UploadTrigger, Button, DemoUploadListComponent],
  changeDetection: ChangeDetectionStrategy.OnPush,
  templateUrl: './multiple-demo.component.html',
})
export class MultipleUploadDemoComponent {
  protected readonly upload = createUploadSignals({
    multiple: true,
    autoUpload: false,
    features: [
      uploadFeature({
        request: ({ file, signal, onProgress }) =>
          uploadBody(`${uploadServerUrl}/upload`, file, {
            fileName: file.name,
            signal,
            onProgress,
          }),
      }),
    ],
  }).upload
  protected startAll() {
    void this.upload.getFeature<UploadFeatureApi>('upload')?.startAll()
  }
}

<fex-upload-demo-section
  title="多文件手动上传"
  description="一次选择多个文件，可逐个上传，也可以手动启动整个文件队列。"
  ><fex-upload-root [controller]="upload"
    ><div class="flex gap-space-sm">
      <button fexButton fexUploadTrigger variant="outline">选择多个文件</button
      ><button fexButton variant="outline" (click)="startAll()">全部上传</button>
    </div>
    <fex-demo-upload-list /></fex-upload-root
></fex-upload-demo-section>
