// packages/@fex-design/svelte/src/primitive/dialog/dialog-footer.svelte
<script lang="ts">
  import { dialogFooterClassName } from '@fex-design/styles/dialog'
  import { cn } from '@fex/utils'
  import type { Snippet } from 'svelte'
  let { children, class: className }: { children?: Snippet; class?: string } = $props()
</script>
<div data-slot="dialog-footer" class={cn(dialogFooterClassName, className)}>{@render children?.()}</div>

// packages/@fex-design/vue/src/primitive/dialog/dialog-footer.vue
<script setup lang="ts">
import { dialogFooterClassName } from '@fex-design/styles/dialog'
import { cn } from '@fex/utils'
const props = defineProps<{ class?: string }>()
</script>
<template>
  <div v-bind="$attrs" data-slot="dialog-footer" :class="cn(dialogFooterClassName, props.class)">
    <slot />
  </div>
</template>
