// packages/components/react/src/primitive/dialog/dialog.tsx
import {
  createContext,
  use,
  useId,
  useRef,
  useState,
  type ComponentProps,
  type KeyboardEvent,
  type MouseEvent,
  type ReactNode,
  type Ref,
} from 'react'
import { createPortal } from 'react-dom'
import { createDialogController, type DialogController, type DialogOptions } from '@fex/components-core/dialog/create-dialog-controller'
import {
  dialogBodyClassName,
  dialogCloseClassName,
  dialogContentClassName,
  dialogDescriptionClassName,
  dialogFooterClassName,
  dialogHeaderClassName,
  dialogOverlayClassName,
  dialogTitleClassName,
  type DialogStyleProps,
} from '@fex/components-styles/dialog'
import { cn, shallowEqualObject } from '@fex/utils'
import { useCoreStore } from '../../hooks/use-core-store'
import { useIsomorphicLayoutEffect } from '../../hooks/use-isomorphic-layout-effect'
import { useLazyRef } from '../../hooks/use-lazy-ref'
import { useMemoizedFn } from '../../hooks/use-memoized-fn'
import useUnmount from '../../hooks/use-unmount'

type DialogContextValue = {
  contentId: string
  descriptionId: string
  dialog: DialogController
  titleId: string
  triggerRef: React.RefObject<HTMLButtonElement | null>
}

const DialogContext = createContext<DialogContextValue | null>(null)
const defaultDismiss = { escapeKey: true, overlayPointer: true }

function useDialogContext(component: string) {
  const context = use(DialogContext)
  if (!context) {
    throw new Error(`${component} must be used inside DialogRoot`)
  }
  return context
}

export function useDialog(component = 'useDialog') {
  const context = useDialogContext(component)
  const snapshot = useCoreStore(context.dialog)
  return { ...context, snapshot }
}

function toEventInfo(event: { target: EventTarget | null; currentTarget: EventTarget | null; event?: Event }) {
  return {
    target: event.target,
    currentTarget: event.currentTarget,
    event: 'event' in event ? event.event : undefined,
  }
}

export interface DialogRootProps extends DialogOptions {
  children?: ReactNode
}

export function DialogRoot({
  children,
  open: openProp,
  defaultOpen,
  onOpenChange,
  modal = true,
  closeDelay = 140,
  dismiss = defaultDismiss,
  ...options
}: DialogRootProps) {
  const isControlled = openProp !== undefined
  const [uncontrolledOpen, setUncontrolledOpen] = useState(defaultOpen ?? false)
  const open = isControlled ? openProp : uncontrolledOpen
  const triggerRef = useRef<HTMLButtonElement | null>(null)
  const handleOpenChange = useMemoizedFn<NonNullable<DialogOptions['onOpenChange']>>((nextOpen, info) => {
    if (!isControlled) {
      setUncontrolledOpen(nextOpen)
    }
    onOpenChange?.(nextOpen, info)
  })
  const dialogOptions: DialogOptions = { ...options, open, onOpenChange: handleOpenChange, modal, closeDelay, dismiss }
  const dialogRef = useLazyRef(() => createDialogController(dialogOptions))
  const latestOptionsRef = useRef(dialogOptions)
  const dialog = dialogRef.current

  useIsomorphicLayoutEffect(() => {
    if (!shallowEqualObject(latestOptionsRef.current, dialogOptions)) {
      latestOptionsRef.current = dialogOptions
      dialog.setOptions(dialogOptions)
    }
  })

  useUnmount(() => dialog.destroy())

  return (
    <DialogContext
      value={{
        contentId: useId(),
        descriptionId: useId(),
        dialog,
        titleId: useId(),
        triggerRef,
      }}
    >
      {children}
    </DialogContext>
  )
}

export type DialogTriggerRenderProps = Omit<ComponentProps<'button'>, 'children' | 'ref'> & {
  'data-state': 'open' | 'closed'
  ref: Ref<HTMLButtonElement>
}

export interface DialogTriggerProps extends Omit<ComponentProps<'button'>, 'children'> {
  children: (props: DialogTriggerRenderProps) => ReactNode
  ref?: Ref<HTMLButtonElement>
}

export function useDialogTrigger({ ref, onClick, ...props }: Omit<DialogTriggerProps, 'children'>) {
  const { contentId, dialog, snapshot, triggerRef } = useDialog('useDialogTrigger')
  const setTrigger = useMemoizedFn((element: HTMLButtonElement | null) => {
    triggerRef.current = element
    if (typeof ref === 'function') ref(element)
    else if (ref && 'current' in ref) ref.current = element
  })

  return {
    snapshot,
    props: {
      ...props,
      ref: setTrigger,
      type: props.type ?? 'button',
      'aria-haspopup': 'dialog' as const,
      'aria-expanded': snapshot.open,
      'aria-controls': snapshot.open ? contentId : undefined,
      'data-state': snapshot.open ? 'open' as const : 'closed' as const,
      onClick: (event: MouseEvent<HTMLButtonElement>) => {
        onClick?.(event)
        if (!event.defaultPrevented) {
          dialog.toggle({ reason: 'trigger-click', event: event.nativeEvent })
        }
      },
    },
  }
}

export function DialogTrigger({ children, ...props }: DialogTriggerProps) {
  const trigger = useDialogTrigger(props)
  return children(trigger.props)
}

export interface DialogPortalProps {
  children?: ReactNode
  container?: HTMLElement | null
  forceMount?: boolean
}

export function DialogPortal({ children, container, forceMount }: DialogPortalProps) {
  const { snapshot } = useDialog('DialogPortal')
  const portalContainer = container ?? globalThis.document?.body
  if (!portalContainer || (!snapshot.mounted && !forceMount)) {
    return null
  }
  return createPortal(children, portalContainer)
}

export interface DialogOverlayProps extends ComponentProps<'div'> {
  ref?: Ref<HTMLDivElement>
}

export function DialogOverlay({ ref, className, onClick, ...props }: DialogOverlayProps) {
  const { dialog, snapshot } = useDialog('DialogOverlay')
  const setOverlay = useMemoizedFn((element: HTMLDivElement | null) => {
    dialog.setOverlayElement(element)
    if (typeof ref === 'function') ref(element)
    else if (ref && 'current' in ref) ref.current = element
  })
  return (
    <div
      {...props}
      ref={setOverlay}
      data-slot="dialog-overlay"
      data-state={snapshot.open ? 'open' : 'closed'}
      data-phase={snapshot.phase}
      className={cn(dialogOverlayClassName, className)}
      onClick={(event) => {
        onClick?.(event)
        if (!event.defaultPrevented && event.target === event.currentTarget) {
          dialog.dismiss.overlayPointer({ ...toEventInfo(event), event: event.nativeEvent })
        }
      }}
    />
  )
}

export interface DialogContentProps extends ComponentProps<'div'>, DialogStyleProps {
  ref?: Ref<HTMLDivElement>
}

export function DialogContent({ ref, className, size, onKeyDown, ...props }: DialogContentProps) {
  const { contentId, descriptionId, dialog, snapshot, titleId } = useDialog('DialogContent')
  const setContent = useMemoizedFn((element: HTMLDivElement | null) => {
    dialog.setLayerElement(element)
    if (typeof ref === 'function') ref(element)
    else if (ref && 'current' in ref) ref.current = element
  })

  if (!snapshot.mounted) {
    return null
  }

  return (
    <div
      {...props}
      ref={setContent}
      id={contentId}
      role="dialog"
      aria-modal="true"
      aria-labelledby={titleId}
      aria-describedby={descriptionId}
      tabIndex={-1}
      data-slot="dialog-content"
      data-state={snapshot.open ? 'open' : 'closed'}
      data-phase={snapshot.phase}
      className={cn(dialogContentClassName({ size }), className)}
      onKeyDown={(event: KeyboardEvent<HTMLDivElement>) => {
        onKeyDown?.(event)
        if (!event.defaultPrevented && event.key === 'Escape') {
          dialog.dismiss.escapeKey({ ...toEventInfo(event), event: event.nativeEvent })
        }
      }}
    />
  )
}

export function DialogHeader({ className, ...props }: ComponentProps<'div'>) {
  return <div {...props} data-slot="dialog-header" className={cn(dialogHeaderClassName, className)} />
}

export function DialogTitle({ className, ...props }: ComponentProps<'h2'>) {
  const { titleId } = useDialog('DialogTitle')
  return <h2 {...props} id={titleId} data-slot="dialog-title" className={cn(dialogTitleClassName, className)} />
}

export function DialogDescription({ className, ...props }: ComponentProps<'p'>) {
  const { descriptionId } = useDialog('DialogDescription')
  return <p {...props} id={descriptionId} data-slot="dialog-description" className={cn(dialogDescriptionClassName, className)} />
}

export function DialogBody({ className, ...props }: ComponentProps<'div'>) {
  return <div {...props} data-slot="dialog-body" className={cn(dialogBodyClassName, className)} />
}

export function DialogFooter({ className, ...props }: ComponentProps<'div'>) {
  return <div {...props} data-slot="dialog-footer" className={cn(dialogFooterClassName, className)} />
}

export type DialogCloseRenderProps = Omit<ComponentProps<'button'>, 'children' | 'ref'> & {
  ref?: Ref<HTMLButtonElement>
}

export interface DialogCloseProps extends Omit<ComponentProps<'button'>, 'children'> {
  children?: ((props: DialogCloseRenderProps) => ReactNode) | ReactNode
  ref?: Ref<HTMLButtonElement>
}

export function DialogClose({ children, className, onClick, type = 'button', ...props }: DialogCloseProps) {
  const { dialog } = useDialog('DialogClose')
  const closeProps = {
    ...props,
    type,
    'data-slot': 'dialog-close',
    className: cn(dialogCloseClassName, className),
    onClick: (event: MouseEvent<HTMLButtonElement>) => {
      onClick?.(event)
      if (!event.defaultPrevented) {
        dialog.close({ reason: 'manual', source: 'close-button', event: event.nativeEvent })
      }
    },
  }

  return typeof children === 'function' ? children(closeProps) : <button {...closeProps}>{children ?? 'Close'}</button>
}

export const Dialog = Object.assign(DialogRoot, {
  Root: DialogRoot,
  Trigger: DialogTrigger,
  Portal: DialogPortal,
  Overlay: DialogOverlay,
  Content: DialogContent,
  Header: DialogHeader,
  Title: DialogTitle,
  Description: DialogDescription,
  Body: DialogBody,
  Footer: DialogFooter,
  Close: DialogClose,
})

export {
  DialogRoot as Root,
  DialogTrigger as Trigger,
  DialogPortal as Portal,
  DialogOverlay as Overlay,
  DialogContent as Content,
  DialogHeader as Header,
  DialogTitle as Title,
  DialogDescription as Description,
  DialogBody as Body,
  DialogFooter as Footer,
  DialogClose as Close,
}

// packages/components/solid/src/primitive/dialog/dialog.tsx
import { createDialogController, type DialogOptions } from '@fex/components-core/dialog/create-dialog-controller'
import {
  dialogBodyClassName,
  dialogCloseClassName,
  dialogContentClassName,
  dialogDescriptionClassName,
  dialogFooterClassName,
  dialogHeaderClassName,
  dialogOverlayClassName,
  dialogTitleClassName,
  type DialogStyleProps,
} from '@fex/components-styles/dialog'
import { cn } from '@fex/utils'
import { Portal } from 'solid-js/web'
import {
  createContext,
  createSignal,
  onCleanup,
  Show,
  splitProps,
  useContext,
  type Accessor,
  type JSX,
  type ParentProps,
} from 'solid-js'
import { createCoreStoreSignal } from '../../primitives/create-core-store-signal'

type DialogContextValue = {
  contentId: string
  descriptionId: string
  dialog: ReturnType<typeof createDialogController>
  snapshot: Accessor<ReturnType<ReturnType<typeof createDialogController>['getSnapshot']>>
  titleId: string
  triggerElement: { current: HTMLButtonElement | null }
}

const DialogContext = createContext<DialogContextValue>()
let nextDialogId = 1

function useDialog(component: string) {
  const context = useContext(DialogContext)
  if (!context) {
    throw new Error(`${component} must be used inside Dialog`)
  }
  return context
}

export interface DialogProps extends ParentProps, DialogOptions {}

export function Dialog(props: DialogProps) {
  const [local] = splitProps(props, ['children', 'open', 'defaultOpen', 'onOpenChange', 'modal', 'forceMount', 'closeDelay', 'dismiss', 'closeOnOverlayPointer'])
  const [open, setOpen] = createSignal(local.open ?? local.defaultOpen ?? false)
  const triggerElement = { current: null as HTMLButtonElement | null }
  const dialogId = nextDialogId++

  function makeOptions(openValue: boolean): DialogOptions {
    return {
      open: openValue,
      modal: local.modal ?? true,
      forceMount: local.forceMount,
      closeDelay: local.closeDelay ?? 140,
      dismiss: local.dismiss,
      closeOnOverlayPointer: local.closeOnOverlayPointer,
      onOpenChange(nextOpen, info) {
        if (local.open === undefined) {
          setOpen(nextOpen)
          dialog.setOptions(makeOptions(nextOpen))
        }
        local.onOpenChange?.(nextOpen, info)
      },
    }
  }

  function syncOptions() {
    dialog.setOptions(makeOptions(local.open ?? open()))
    return null
  }

  const dialog = createDialogController(makeOptions(open()))
  const snapshot = createCoreStoreSignal(dialog)

  onCleanup(() => dialog.destroy())

  return (
    <>
      {syncOptions()}
      <DialogContext.Provider
        value={{
          contentId: `fex-dialog-content-${dialogId}`,
          descriptionId: `fex-dialog-description-${dialogId}`,
          dialog,
          snapshot,
          titleId: `fex-dialog-title-${dialogId}`,
          triggerElement,
        }}
      >
        {local.children}
      </DialogContext.Provider>
    </>
  )
}

export type DialogTriggerRenderProps = {
  props: {
    'aria-controls': string | undefined
    'aria-expanded': boolean
    'aria-haspopup': 'dialog'
    'data-state': 'open' | 'closed'
    class: string | undefined
    onClick: JSX.EventHandlerUnion<HTMLButtonElement, MouseEvent>
    type: 'button'
  }
  ref: (element: HTMLButtonElement) => void
  state: ReturnType<ReturnType<typeof createDialogController>['getSnapshot']>
}

export interface DialogTriggerProps {
  children: (props: DialogTriggerRenderProps) => JSX.Element
  class?: string
}

export function DialogTrigger(props: DialogTriggerProps) {
  const [local] = splitProps(props, ['children', 'class'])
  const { contentId, dialog, snapshot, triggerElement } = useDialog('DialogTrigger')

  return local.children({
    ref: (element) => {
      triggerElement.current = element
    },
    state: snapshot(),
    props: {
      type: 'button',
      class: local.class,
      'aria-haspopup': 'dialog',
      'aria-expanded': snapshot().open,
      'aria-controls': snapshot().open ? contentId : undefined,
      'data-state': snapshot().open ? 'open' : 'closed',
      onClick: (event) => dialog.toggle({ reason: 'trigger-click', event }),
    },
  })
}

export interface DialogPortalProps extends ParentProps {
  container?: HTMLElement | null
  forceMount?: boolean
}

export function DialogPortal(props: DialogPortalProps) {
  const { snapshot } = useDialog('DialogPortal')
  return (
    <Show when={snapshot().mounted || props.forceMount}>
      <Portal mount={props.container ?? document.body}>{props.children}</Portal>
    </Show>
  )
}

export interface DialogOverlayProps {
  class?: string
}

export function DialogOverlay(props: DialogOverlayProps) {
  const [local] = splitProps(props, ['class'])
  const { dialog, snapshot } = useDialog('DialogOverlay')
  onCleanup(() => dialog.setOverlayElement(null))
  return (
    <div
      ref={(element) => dialog.setOverlayElement(element)}
      data-slot="dialog-overlay"
      data-state={snapshot().open ? 'open' : 'closed'}
      data-phase={snapshot().phase}
      class={cn(dialogOverlayClassName, local.class)}
      onClick={(event) => {
        if (event.target === event.currentTarget) {
          dialog.dismiss.overlayPointer({ target: event.target, currentTarget: event.currentTarget, event })
        }
      }}
    />
  )
}

export interface DialogContentProps extends ParentProps {
  class?: string
  size?: DialogStyleProps['size']
}

export function DialogContent(props: DialogContentProps) {
  const [local] = splitProps(props, ['children', 'class', 'size'])
  const { contentId, descriptionId, dialog, snapshot, titleId } = useDialog('DialogContent')
  onCleanup(() => dialog.setLayerElement(null))
  return (
    <Show when={snapshot().mounted}>
      <div
        ref={(element) => dialog.setLayerElement(element)}
        id={contentId}
        role="dialog"
        aria-modal="true"
        aria-labelledby={titleId}
        aria-describedby={descriptionId}
        tabIndex={-1}
        data-slot="dialog-content"
        data-state={snapshot().open ? 'open' : 'closed'}
        data-phase={snapshot().phase}
        class={cn(dialogContentClassName({ size: local.size }), local.class)}
        onKeyDown={(event) => {
          if (event.key === 'Escape') {
            dialog.dismiss.escapeKey({ target: event.target, currentTarget: event.currentTarget, event })
          }
        }}
      >
        {local.children}
      </div>
    </Show>
  )
}

function createPart(slot: string, className: string) {
  return function DialogPart(props: ParentProps<{ class?: string }>) {
    const [local, rest] = splitProps(props, ['children', 'class'])
    return <div {...rest} data-slot={slot} class={cn(className, local.class)}>{local.children}</div>
  }
}

export const DialogHeader = createPart('dialog-header', dialogHeaderClassName)
export const DialogBody = createPart('dialog-body', dialogBodyClassName)
export const DialogFooter = createPart('dialog-footer', dialogFooterClassName)

export function DialogTitle(props: ParentProps<{ class?: string }>) {
  const [local, rest] = splitProps(props, ['children', 'class'])
  const { titleId } = useDialog('DialogTitle')
  return <h2 {...rest} id={titleId} data-slot="dialog-title" class={cn(dialogTitleClassName, local.class)}>{local.children}</h2>
}

export function DialogDescription(props: ParentProps<{ class?: string }>) {
  const [local, rest] = splitProps(props, ['children', 'class'])
  const { descriptionId } = useDialog('DialogDescription')
  return <p {...rest} id={descriptionId} data-slot="dialog-description" class={cn(dialogDescriptionClassName, local.class)}>{local.children}</p>
}

export type DialogCloseRenderProps = {
  class: string
  onClick: JSX.EventHandlerUnion<HTMLButtonElement, MouseEvent>
  type: 'button'
  'data-slot': 'dialog-close'
}

export interface DialogCloseProps {
  children?: JSX.Element | ((props: DialogCloseRenderProps) => JSX.Element)
  class?: string
}

export function DialogClose(props: DialogCloseProps) {
  const [local, rest] = splitProps(props, ['children', 'class'])
  const { dialog } = useDialog('DialogClose')
  const closeProps = {
    ...rest,
    type: 'button' as const,
    'data-slot': 'dialog-close' as const,
    class: cn(dialogCloseClassName, local.class),
    onClick: (event: MouseEvent) => dialog.close({ reason: 'manual', source: 'close-button', event }),
  }

  return typeof local.children === 'function'
    ? local.children(closeProps)
    : <button {...closeProps}>{local.children ?? 'Close'}</button>
}
