// packages/components/svelte/src/primitive/table/table-caption.svelte
<script lang="ts">
  import { tableCaptionClassName } from '@fex/components-styles/table'
  import { cn } from '@fex/utils'
  import type { Snippet } from 'svelte'
  import type { HTMLAttributes } from 'svelte/elements'
  interface Props extends Omit<HTMLAttributes<HTMLElement>, 'class'> { class?: string | undefined; children?: Snippet }
  let { class: className, children, ...rest }: Props = $props()
  const classList = $derived(cn(tableCaptionClassName, className))
</script>
<caption {...rest} data-slot="table-caption" class={classList}>{@render children?.()}</caption>

// packages/components/vue/src/primitive/table/table-caption.vue
﻿<script setup lang="ts">
import { tableCaptionClassName } from '@fex/components-styles/table'
import { cn } from '@fex/utils'

defineOptions({ inheritAttrs: false })
const props = defineProps<{ class?: string | undefined }>()
</script>

<template>
  <caption
    v-bind="$attrs"
    data-slot="table-caption"
    :class="cn(tableCaptionClassName, props.class)"
  >
    <slot />
  </caption>
</template>
