// packages/components/svelte/src/primitive/table/table-header.svelte
<script lang="ts">
  import { tableHeaderClassName } from '@fex/components-styles/table'
  import { cn } from '@fex/utils'
  import type { Snippet } from 'svelte'
  import type { HTMLAttributes } from 'svelte/elements'
  interface Props extends Omit<HTMLAttributes<HTMLTableSectionElement>, 'class'> { class?: string; children?: Snippet }
  let { class: className, children, ...rest }: Props = $props()
  const classList = $derived(cn(tableHeaderClassName, className))
</script>
<thead {...rest} data-slot="table-header" class={classList}>{@render children?.()}</thead>

// packages/components/vue/src/primitive/table/table-header.vue
﻿<script setup lang="ts">
import { tableHeaderClassName } from '@fex/components-styles/table'
import { cn } from '@fex/utils'

defineOptions({ inheritAttrs: false })
const props = defineProps<{ class?: string | undefined }>()
</script>

<template>
  <thead v-bind="$attrs" data-slot="table-header" :class="cn(tableHeaderClassName, props.class)">
    <slot />
  </thead>
</template>
