// apps/solid-admin/src/pages/Home.tsx
import { A } from '@solidjs/router'
import { For } from 'solid-js'

const componentLinks = [
  { href: '/auto-complete', label: 'AutoComplete' },
  { href: '/carousel', label: 'Carousel' },
  { href: '/button', label: 'Button' },
  { href: '/calendar', label: 'Calendar' },
    { href: '/card', label: 'Card' },
    { href: '/checkbox', label: 'Checkbox' },
    { href: '/collapse', label: 'Collapse' },
  { href: '/context-menu', label: 'ContextMenu' },
    { href: '/dialog', label: 'Dialog' },
  { href: '/drawer', label: 'Drawer' },
  { href: '/dropdown', label: 'Dropdown' },
  { href: '/data-table', label: 'Data Table' },
  { href: '/date-picker', label: 'DatePicker' },
  { href: '/alert', label: 'Alert' },
  { href: '/badge', label: 'Badge' },
  { href: '/breadcrumb', label: 'Breadcrumb' },
  { href: '/empty', label: 'Empty' },
  { href: '/form', label: 'Form' },
  { href: '/input', label: 'Input' },
  { href: '/kbd', label: 'Kbd' },
  { href: '/listbox', label: 'Listbox' },
  { href: '/menu', label: 'Menu' },
  { href: '/pagination', label: 'Pagination' },
  { href: '/popover', label: 'Popover' },
  { href: '/radio', label: 'Radio' },
  { href: '/rate', label: 'Rate' },
  { href: '/spinner', label: 'Spinner' },
  { href: '/slider', label: 'Slider' },
  { href: '/scrollbar', label: 'Scrollbar' },
  { href: '/select', label: 'Select' },
  { href: '/switch', label: 'Switch' },
  { href: '/table', label: 'Table' },
  { href: '/tabs', label: 'Tabs' },
  { href: '/steps', label: 'Steps' },
  { href: '/timeline', label: 'Timeline' },
  { href: '/transfer', label: 'Transfer' },
  { href: '/upload', label: 'Upload' },
  { href: '/tree', label: 'Tree' },
  { href: '/toast', label: 'Toast' },
  { href: '/sortable', label: 'Sortable' },
  { href: '/interactions', label: 'Interactions' },
  { href: '/resizable', label: 'Resizable' },
  { href: '/textarea', label: 'Textarea' },
    { href: '/time-picker', label: 'TimePicker' },
    { href: '/tooltip', label: 'Tooltip' },
  // eslint-disable-next-line unicorn/no-array-sort -- this literal is newly created and not shared.
].sort((left, right) => left.label.localeCompare(right.label))

function NavLink(props: { href: string; label: string }) {
  return (
    <A
      class="rounded-md border border-border bg-background px-space-lg py-space-sm text-sm text-foreground transition-colors hover:bg-muted-background"
      href={props.href}
    >
      {props.label}
    </A>
  )
}

export function Home() {
  return (
    <main class="min-h-screen bg-secondary-background px-page-padding py-space-xl">
      <div class="mx-auto w-full max-w-5xl space-y-space-xl">
        <header class="space-y-space-sm">
          <h1 class="text-2xl font-semibold text-foreground">Solid Admin</h1>
          <p class="text-sm leading-6 text-muted-foreground">
            临时导航入口，后续后台功能完整后再调整首页结构。
          </p>
        </header>

        <section class="space-y-space-md">
          <h2 class="text-base font-medium text-foreground">Components</h2>
          <nav
            class="grid grid-cols-1 gap-space-sm sm:grid-cols-2 lg:grid-cols-3"
            aria-label="组件示例"
          >
            <For each={componentLinks}>
              {(link) => <NavLink href={link.href} label={link.label} />}
            </For>
          </nav>
        </section>
      </div>
    </main>
  )
}

// apps/angular-admin/src/pages/home.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core'
import { RouterLink } from '@angular/router'

@Component({
  selector: 'fex-home',
  imports: [RouterLink],
  host: { class: 'block' },
  templateUrl: './home.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class HomeComponent {
  protected readonly componentLinks = [
    { to: '/auto-complete', label: 'AutoComplete' },
    { to: '/carousel', label: 'Carousel' },
    { to: '/button', label: 'Button' },
    { to: '/calendar', label: 'Calendar' },
    { to: '/card', label: 'Card' },
    { to: '/checkbox', label: 'Checkbox' },
    { to: '/collapse', label: 'Collapse' },
    { to: '/context-menu', label: 'ContextMenu' },
    { to: '/dialog', label: 'Dialog' },
    { to: '/drawer', label: 'Drawer' },
    { to: '/dropdown', label: 'Dropdown' },
    { to: '/data-table', label: 'Data Table' },
    { to: '/date-picker', label: 'DatePicker' },
    { to: '/alert', label: 'Alert' },
    { to: '/badge', label: 'Badge' },
    { to: '/breadcrumb', label: 'Breadcrumb' },
    { to: '/empty', label: 'Empty' },
    { to: '/form', label: 'Form' },
    { to: '/input', label: 'Input' },
    { to: '/kbd', label: 'Kbd' },
    { to: '/listbox', label: 'Listbox' },
    { to: '/menu', label: 'Menu' },
    { to: '/pagination', label: 'Pagination' },
    { to: '/popover', label: 'Popover' },
    { to: '/radio', label: 'Radio' },
    { to: '/rate', label: 'Rate' },
    { to: '/spinner', label: 'Spinner' },
    { to: '/slider', label: 'Slider' },
    { to: '/scrollbar', label: 'Scrollbar' },
    { to: '/select', label: 'Select' },
    { to: '/switch', label: 'Switch' },
    { to: '/table', label: 'Table' },
    { to: '/tabs', label: 'Tabs' },
    { to: '/steps', label: 'Steps' },
    { to: '/timeline', label: 'Timeline' },
    { to: '/toast', label: 'Toast' },
    { to: '/sortable', label: 'Sortable' },
    { to: '/interactions', label: 'Interactions' },
    { to: '/resizable', label: 'Resizable' },
    { to: '/textarea', label: 'Textarea' },
    { to: '/time-picker', label: 'TimePicker' },
    { to: '/tooltip', label: 'Tooltip' },
    { to: '/tree', label: 'Tree' },
    { to: '/transfer', label: 'Transfer' },
    { to: '/upload', label: 'Upload' },
    // eslint-disable-next-line unicorn/no-array-sort -- this literal is newly created and not shared.
  ].sort((left, right) => left.label.localeCompare(right.label))
}

<main class="min-h-screen bg-secondary-background px-page-padding py-space-xl">
  <div class="mx-auto w-full max-w-5xl space-y-space-xl">
    <header class="space-y-space-sm">
      <h1 class="text-2xl font-semibold text-foreground">Angular Admin</h1>
      <p class="text-sm leading-6 text-muted-foreground">
        临时导航入口，后续后台功能完整后再调整首页结构。
      </p>
    </header>

    <section class="space-y-space-md">
      <h2 class="text-base font-medium text-foreground">Components</h2>
      <nav
        class="grid grid-cols-1 gap-space-sm sm:grid-cols-2 lg:grid-cols-3"
        aria-label="组件示例"
      >
        @for (link of componentLinks; track link.to) {
          <a
            class="rounded-md border border-border bg-background px-space-lg py-space-sm text-sm text-foreground transition-colors hover:bg-muted-background"
            [routerLink]="link.to"
          >
            {{ link.label }}
          </a>
        }
      </nav>
    </section>
  </div>
</main>
