// packages/@fex-design/vue/src/primitive/empty/empty-media.vue
<script setup lang="ts">
import { emptyMediaClassName, type EmptyMediaStyleProps } from '@fex-design/styles/empty'
import { cn } from '@fex/utils'

defineOptions({ inheritAttrs: false })
const props = withDefaults(
  defineProps<{ class?: string | undefined; variant?: EmptyMediaStyleProps['variant'] }>(),
  { variant: 'icon' },
)
</script>

<template>
  <div
    v-bind="$attrs"
    data-slot="empty-icon"
    :data-variant="props.variant"
    :class="cn(emptyMediaClassName({ variant: props.variant }), props.class)"
  >
    <slot />
  </div>
</template>

// packages/@fex-design/svelte/src/primitive/empty/empty-media.svelte
<script lang="ts">
  import { emptyMediaClassName, type EmptyMediaStyleProps } from '@fex-design/styles/empty'
  import { cn } from '@fex/utils'
  import type { Snippet } from 'svelte'
  import type { HTMLAttributes } from 'svelte/elements'
  interface Props extends Omit<HTMLAttributes<HTMLDivElement>, 'class'>, EmptyMediaStyleProps { class?: string; children?: Snippet }
  let { class: className, children, variant = 'default', ...rest }: Props = $props()
  const classList = $derived(cn(emptyMediaClassName({ variant }), className))
</script>
<div {...rest} data-slot="empty-icon" data-variant={variant} class={classList}>{@render children?.()}</div>
