// apps/vue-app/src/pages/Tabs/index.vue
<script setup lang="ts">
import BasicDemo from './basic-demo.vue'
import VariantDemo from './variant-demo.vue'
import DynamicDemo from './dynamic-demo.vue'
import SortableDemo from './sortable-demo.vue'
import CustomDemo from './custom-demo.vue'
</script>
<template>
  <main class="min-h-screen bg-secondary-background px-page-padding py-space-xl">
    <div class="mx-auto w-full max-w-5xl space-y-space-xl">
      <header class="space-y-space-sm">
        <RouterLink class="text-sm text-muted-foreground hover:text-foreground" to="/"
          >Back home</RouterLink
        >
        <div>
          <h1 class="text-2xl font-semibold text-foreground">Tabs</h1>
          <p class="max-w-3xl text-sm leading-6 text-muted-foreground">
            Composable tab navigation with lazy retained content and custom rendering.
          </p>
        </div>
      </header>
      <div class="space-y-space-xl">
        <BasicDemo /><VariantDemo /><DynamicDemo /><SortableDemo /><CustomDemo />
      </div>
    </div>
  </main>
</template>

// apps/angular-admin/src/pages/tabs/index.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core'
import { RouterLink } from '@angular/router'
import { BasicTabsDemoComponent } from './basic-demo.component'
import { VariantTabsDemoComponent } from './variant-demo.component'
import { DynamicTabsDemoComponent } from './dynamic-demo.component'
import { SortableTabsDemoComponent } from './sortable-demo.component'
import { CustomTabsDemoComponent } from './custom-demo.component'
@Component({
  selector: 'fex-tabs-page',
  standalone: true,
  imports: [
    RouterLink,
    BasicTabsDemoComponent,
    VariantTabsDemoComponent,
    DynamicTabsDemoComponent,
    SortableTabsDemoComponent,
    CustomTabsDemoComponent,
  ],
  host: { class: 'block' },
  templateUrl: './index.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class TabsComponent {}

<main class="min-h-screen bg-secondary-background px-page-padding py-space-xl">
  <div class="mx-auto w-full max-w-5xl space-y-space-xl">
    <header class="space-y-space-sm">
      <a class="text-sm text-muted-foreground hover:text-foreground" routerLink="/">Back home</a>
      <div>
        <h1 class="text-2xl font-semibold text-foreground">Tabs</h1>
        <p class="max-w-3xl text-sm leading-6 text-muted-foreground">
          Composable tab navigation with lazy retained content and custom elements.
        </p>
      </div>
    </header>
    <div class="space-y-space-xl">
      <fex-basic-tabs-demo /><fex-variant-tabs-demo /><fex-dynamic-tabs-demo /><fex-sortable-tabs-demo /><fex-custom-tabs-demo />
    </div>
  </div>
</main>
