// packages/@fex-design/solid/src/primitive/button/button.tsx
import { buttonPrimitiveClassName } from '@fex-design/styles/button'
import { cn } from '@fex/utils'
import type { JSX, ParentProps } from 'solid-js'
import { splitProps } from 'solid-js'

export interface ButtonProps extends ParentProps<JSX.ButtonHTMLAttributes<HTMLButtonElement>> {}

export function Button(props: ButtonProps) {
  const [local, rest] = splitProps(props, ['class', 'children', 'type'])

  return (
    <button
      data-slot="button"
      {...rest}
      type={local.type ?? 'button'}
      class={cn(buttonPrimitiveClassName, local.class)}
    >
      {local.children}
    </button>
  )
}

export default Button

// packages/@fex-design/svelte/src/primitive/button/button.svelte
<script lang="ts">
  import { buttonPrimitiveClassName } from '@fex-design/styles/button'
  import { cn } from '@fex/utils'
  import type { Snippet } from 'svelte'
  import type { HTMLButtonAttributes } from 'svelte/elements'

  interface ButtonProps extends Omit<HTMLButtonAttributes, 'class'> {
    action?: (element: HTMLButtonElement) => { destroy?: () => void } | void
    class?: string
    children?: Snippet
  }

  let { action, class: className, children, type = 'button', ...rest }: ButtonProps = $props()
  const classList = $derived(cn(buttonPrimitiveClassName, className))

  function buttonAction(element: HTMLButtonElement) {
    const cleanup = action?.(element)
    return {
      destroy() {
        cleanup?.destroy?.()
      },
    }
  }
</script>

<button data-slot="button" {...rest} class={classList} {type} use:buttonAction>
  {@render children?.()}
</button>
