// packages/@fex-design/svelte/src/primitive/card/card-title.svelte
<script lang="ts">
  import { cardTitleClassName } from '@fex-design/styles/card'
  import { cn } from '@fex/utils'
  import type { Snippet } from 'svelte'
  import type { HTMLAttributes } from 'svelte/elements'

  interface CardTitleProps extends Omit<HTMLAttributes<HTMLDivElement>, 'class'> {
    class?: string
    children?: Snippet
  }

  let { class: className, children, ...rest }: CardTitleProps = $props()

  const classList = $derived(cn(cardTitleClassName, className))
</script>

<div {...rest} data-slot="card-title" class={classList}>
  {@render children?.()}
</div>

// packages/@fex-design/vue/src/primitive/card/card-title.vue
﻿<script setup lang="ts">
import { cardTitleClassName } from '@fex-design/styles/card'
import { cn } from '@fex/utils'

defineOptions({ inheritAttrs: false })
const props = defineProps<{ class?: string | undefined }>()
</script>

<template>
  <div v-bind="$attrs" data-slot="card-title" :class="cn(cardTitleClassName, props.class)">
    <slot />
  </div>
</template>
