// apps/vue-admin/src/pages/Home.vue
<script setup lang="ts">
const componentLinks = [
  { to: '/auto-complete', label: 'AutoComplete' },
  { to: '/carousel', label: 'Carousel' },
  { to: '/button', label: 'Button' },
  { to: '/calendar', label: 'Calendar' },
  { to: '/card', label: 'Card' },
  { to: '/checkbox', label: 'Checkbox' },
  { to: '/dialog', label: 'Dialog' },
  { to: '/alert', label: 'Alert' },
  { to: '/badge', label: 'Badge' },
  { to: '/empty', label: 'Empty' },
  { to: '/form', label: 'Form' },
  { to: '/input', label: 'Input' },
  { to: '/kbd', label: 'Kbd' },
  { to: '/listbox', label: 'Listbox' },
  { to: '/menu', label: 'Menu' },
  { to: '/pagination', label: 'Pagination' },
  { to: '/popover', label: 'Popover' },
  { to: '/radio', label: 'Radio' },
  { to: '/rate', label: 'Rate' },
  { to: '/spinner', label: 'Spinner' },
  { to: '/slider', label: 'Slider' },
  { to: '/scrollbar', label: 'Scrollbar' },
  { to: '/select', label: 'Select' },
  { to: '/switch', label: 'Switch' },
  { to: '/table', label: 'Table' },
  { to: '/tabs', label: 'Tabs' },
  { to: '/transfer', label: 'Transfer' },
  { to: '/upload', label: 'Upload' },
  { to: '/data-grid', label: 'Data Grid' },
  { to: '/date-picker', label: 'DatePicker' },
  { to: '/tree', label: 'Tree' },
  { to: '/toast', label: 'Toast' },
  { to: '/sortable', label: 'Sortable' },
  { to: '/interactions', label: 'Interactions' },
  { to: '/resizable', label: 'Resizable' },
  { to: '/textarea', label: 'Textarea' },
  { to: '/time-picker', label: 'TimePicker' },
].sort((left, right) => left.label.localeCompare(right.label))
</script>

<template>
  <main class="min-h-screen bg-secondary-background px-page-padding py-space-xl">
    <div class="mx-auto w-full max-w-5xl space-y-space-xl">
      <header class="space-y-space-sm">
        <h1 class="text-2xl font-semibold text-foreground">Vue Admin</h1>
        <p class="text-sm leading-6 text-muted-foreground">
          临时导航入口，后续后台功能完整后再调整首页结构。
        </p>
      </header>

      <section class="space-y-space-md">
        <h2 class="text-base font-medium text-foreground">Components</h2>
        <nav
          class="grid grid-cols-1 gap-space-sm sm:grid-cols-2 lg:grid-cols-3"
          aria-label="组件示例"
        >
          <RouterLink
            v-for="link in componentLinks"
            :key="link.to"
            class="rounded-md border border-border bg-background px-space-lg py-space-sm text-sm text-foreground transition-colors hover:bg-muted-background"
            :to="link.to"
          >
            {{ link.label }}
          </RouterLink>
        </nav>
      </section>
    </div>
  </main>
</template>

// apps/solid-admin/src/pages/Home.tsx
import { A } from '@solidjs/router'
import { For } from 'solid-js'

const componentLinks = [
  { href: '/auto-complete', label: 'AutoComplete' },
  { href: '/carousel', label: 'Carousel' },
  { href: '/button', label: 'Button' },
  { href: '/calendar', label: 'Calendar' },
  { href: '/card', label: 'Card' },
  { href: '/checkbox', label: 'Checkbox' },
  { href: '/dialog', label: 'Dialog' },
  { href: '/data-grid', label: 'Data Grid' },
  { href: '/date-picker', label: 'DatePicker' },
  { href: '/alert', label: 'Alert' },
  { href: '/badge', label: 'Badge' },
  { href: '/empty', label: 'Empty' },
  { href: '/form', label: 'Form' },
  { href: '/input', label: 'Input' },
  { href: '/kbd', label: 'Kbd' },
  { href: '/listbox', label: 'Listbox' },
  { href: '/menu', label: 'Menu' },
  { href: '/pagination', label: 'Pagination' },
  { href: '/popover', label: 'Popover' },
  { href: '/radio', label: 'Radio' },
  { href: '/spinner', label: 'Spinner' },
  { href: '/slider', label: 'Slider' },
  { href: '/scrollbar', label: 'Scrollbar' },
  { href: '/select', label: 'Select' },
  { href: '/switch', label: 'Switch' },
    { href: '/table', label: 'Table' },
    { href: '/tabs', label: 'Tabs' },
  { href: '/transfer', label: 'Transfer' },
  { href: '/tree', label: 'Tree' },
  { href: '/toast', label: 'Toast' },
  { href: '/sortable', label: 'Sortable' },
  { href: '/interactions', label: 'Interactions' },
  { href: '/resizable', label: 'Resizable' },
  { href: '/textarea', label: 'Textarea' },
  { href: '/time-picker', label: 'TimePicker' },
].sort((left, right) => left.label.localeCompare(right.label))

function NavLink(props: { href: string; label: string }) {
  return (
    <A
      class="rounded-md border border-border bg-background px-space-lg py-space-sm text-sm text-foreground transition-colors hover:bg-muted-background"
      href={props.href}
    >
      {props.label}
    </A>
  )
}

export function Home() {
  return (
    <main class="min-h-screen bg-secondary-background px-page-padding py-space-xl">
      <div class="mx-auto w-full max-w-5xl space-y-space-xl">
        <header class="space-y-space-sm">
          <h1 class="text-2xl font-semibold text-foreground">Solid Admin</h1>
          <p class="text-sm leading-6 text-muted-foreground">
            临时导航入口，后续后台功能完整后再调整首页结构。
          </p>
        </header>

        <section class="space-y-space-md">
          <h2 class="text-base font-medium text-foreground">Components</h2>
          <nav
            class="grid grid-cols-1 gap-space-sm sm:grid-cols-2 lg:grid-cols-3"
            aria-label="组件示例"
          >
            <For each={componentLinks}>
              {(link) => <NavLink href={link.href} label={link.label} />}
            </For>
          </nav>
        </section>
      </div>
    </main>
  )
}
