// apps/angular-app/src/pages/input-number/formatter-demo.component.ts
import type { InputNumberFormatInfo } from '@fex-design/core/input-number/types'
import { ChangeDetectionStrategy, Component } from '@angular/core'
import { InputNumber } from '@fex-design/angular/primitive/input-number'
import Card from '@fex-design/angular/ui/card'

@Component({
  selector: 'fex-input-number-formatter-demo',
  standalone: true,
  imports: [Card, InputNumber],
  changeDetection: ChangeDetectionStrategy.OnPush,
  templateUrl: './formatter-demo.component.html',
})
export class FormatterDemoComponent {
  protected parser = (text: string) => {
    const value = Number(text.replace(/[¥,\s]/g, ''))
    return Number.isFinite(value) ? value : undefined
  }
  protected formatter = (value: number | undefined, info: InputNumberFormatInfo) =>
    info.userTyping
      ? info.input
      : value === undefined
        ? ''
        : `¥${new Intl.NumberFormat('zh-CN').format(value)}`
}

<fex-card title="Parser and formatter" description="Blur restores currency presentation."
  ><fex-input-number
    class="max-w-sm"
    [defaultValue]="1234.5"
    [parser]="parser"
    [formatter]="formatter"
/></fex-card>

// apps/svelte-app/src/routes/input-number/formatter-demo.svelte
<script lang="ts">
  import InputNumber from '@fex-design/svelte/primitive/input-number'
  import Card from '@fex-design/svelte/ui/card'

  const parser = (text: string) => {
    const value = Number(text.replace(/[¥,\s]/g, ''))
    return Number.isFinite(value) ? value : undefined
  }
</script>

<Card title="Parser and formatter" description="Blur restores currency presentation.">
  <InputNumber
    class="max-w-sm"
    defaultValue={1234.5}
    {parser}
    formatter={(value, info) =>
      info.userTyping
        ? info.input
        : value === undefined
          ? ''
          : `¥${new Intl.NumberFormat('zh-CN').format(value)}`}
  />
</Card>
