// packages/components/solid/src/primitive/popover/popover-context.ts
import { createContext, useContext, type Accessor } from 'solid-js'
import type { FloatingOverlay } from '@fex/components-core/overlay/create-floating-overlay'
export interface PopoverContextValue {
  arrow: boolean
  arrowElement: { current: HTMLElement | null }
  contentElement: { current: HTMLElement | null }
  overlay: FloatingOverlay
  hoverAncestors: FloatingOverlay[]
  snapshot: Accessor<ReturnType<FloatingOverlay['getSnapshot']>>
  triggerElement: { current: HTMLElement | null }
}
export interface PopoverDismissRecord {
  arrowElement: { current: HTMLElement | null }
  contentElement: { current: HTMLElement | null }
  overlay: FloatingOverlay
  triggerElement: { current: HTMLElement | null }
}
export const PopoverContext = createContext<PopoverContextValue>()
export const dismissRecords = new Set<PopoverDismissRecord>()
export function dismissOpenPopovers(event: Event, except?: FloatingOverlay) {
  const target = event.target
  dismissRecords.forEach((record) => {
    if (record.overlay === except || !record.overlay.getSnapshot().open) return
    if (
      target instanceof Node &&
      (record.triggerElement.current?.contains(target) ||
        record.contentElement.current?.contains(target) ||
        record.arrowElement.current?.contains(target))
    )
      return
    record.overlay.close({ reason: 'outside-pointer', event })
  })
}
export function usePopover(component: string) {
  const context = useContext(PopoverContext)
  if (!context) throw new Error(`${component} must be used inside Popover`)
  return context
}

// packages/components/react/src/primitive/popover/popover-context.ts
import { createContext, use } from 'react'
import type { FloatingOverlay } from '@fex/components-core/overlay/create-floating-overlay'
import type { RefObject } from 'react'

export interface PopoverContextValue {
  arrow: boolean
  arrowRef: RefObject<HTMLElement | null>
  overlay: FloatingOverlay
  hoverAncestors: FloatingOverlay[]
  triggerRef: RefObject<HTMLElement | null>
}

export const PopoverContext = createContext<PopoverContextValue | null>(null)

export function usePopoverContext(component: string) {
  const context = use(PopoverContext)
  if (!context) throw new Error(`${component} must be used inside PopoverRoot`)
  return context
}
