// apps/solid-admin/src/pages/Select/custom-tag-demo.tsx
import { Tag } from '@fex-design/solid/primitive/tag'
import { SelectContent, SelectRoot, SelectTrigger } from '@fex-design/solid/primitive/select'
import { frameworkOptions } from './data'
import { SelectDemoSection as Demo } from './demo-section'
const colors: Record<string, string> = {
  react: '#0284c7', vue: '#059669', angular: '#dc2626',
}
export function CustomTagDemo() {
  return (
    <Demo
      title="Custom selected tags"
      description="tagRender controls each selected value while remove keeps shared behavior."
    >
      <SelectRoot multiple options={frameworkOptions} defaultValue={['react', 'vue', 'angular']}>
        <SelectTrigger
          tagRender={(option, { remove }) => (
            <Tag size="sm" closable color={colors[String(option.value)] ?? 'neutral'} onPointerDownCapture={(event) => event.preventDefault()} onClose={(event) => { event.stopPropagation(); remove() }}>
              {option.label}
            </Tag>
          )}
          placeholder="请选择"
        />
        <SelectContent />
      </SelectRoot>
    </Demo>
  )
}

// apps/svelte-app/src/routes/select/custom-tag-demo.svelte
<script lang="ts">
  import SelectRoot from '@fex-design/svelte/primitive/select'
  import SelectContent from '@fex-design/svelte/primitive/select-content'
  import SelectTrigger from '@fex-design/svelte/primitive/select-trigger'
  import Tag from '@fex-design/svelte/primitive/tag'
  import { frameworkOptions } from './data'
  import Demo from './demo-section.svelte'
  const colors: Record<string,string> = { react:'#0284c7', vue:'#059669', angular:'#dc2626' }
</script>
<Demo title="Custom selected tags" description="The tag snippet controls each selected value."><SelectRoot multiple options={frameworkOptions} defaultValue={['react','vue','angular']}><SelectTrigger placeholder="请选择">{#snippet tag(item,remove)}<Tag size="sm" closable color={colors[String(item.value)]??'neutral'} onpointerdown={event=>event.preventDefault()} onClose={event=>{event.stopPropagation();remove()}}>{item.label}</Tag>{/snippet}</SelectTrigger><SelectContent/></SelectRoot></Demo>
