// apps/vue-app/src/pages/TimePicker/format-demo.vue
<script setup lang="ts">
import Card from '@fex-design/vue/ui/card'
import DemoTimePicker from './demo-time-picker.vue'
</script>
<template>
  <Card title="Format 决定列"
    ><div class="flex gap-space-lg">
      <DemoTimePicker format="HH:mm" /><DemoTimePicker format="HH:mm:ss" /></div
  ></Card>
</template>

// apps/angular-app/src/pages/time-picker/format-demo.component.ts
import Card from '@fex-design/angular/ui/card'
import { ChangeDetectionStrategy, Component } from '@angular/core'
import { DemoTimePickerComponent } from './demo-time-picker.component'
@Component({
  selector: 'fex-format-time-demo',
  standalone: true,
  imports: [Card, DemoTimePickerComponent],
  changeDetection: ChangeDetectionStrategy.OnPush,
  templateUrl: './format-demo.component.html',
})
export class FormatDemoComponent {}

<fex-card title="Format 决定列"
  ><div class="flex gap-space-lg">
    <fex-demo-time-picker format="HH:mm" /><fex-demo-time-picker format="HH:mm:ss" /></div
></fex-card>
