// apps/solid-admin/src/pages/Tooltip/controlled-demo.tsx
import * as Tooltip from '@fex/components-solid/primitive/tooltip'
import { Button } from '@fex/components-solid/ui/button'
import { createSignal } from 'solid-js'
export function ControlledDemo() { const [open, setOpen] = createSignal(false); return <div class="flex gap-space-md"><Button variant="secondary" onClick={() => setOpen(!open())}>{open() ? 'Close externally' : 'Open externally'}</Button><Tooltip.TooltipRoot open={open()} onOpenChange={setOpen}><Tooltip.TooltipTrigger>{(slot) => <Button ref={slot.ref} {...slot.props} variant="outline">Controlled trigger</Button>}</Tooltip.TooltipTrigger><Tooltip.TooltipPortal><Tooltip.TooltipContent>Controlled state remains external<Tooltip.TooltipArrow /></Tooltip.TooltipContent></Tooltip.TooltipPortal></Tooltip.TooltipRoot></div> }

// apps/vue-admin/src/pages/Tooltip/controlled-demo.vue
<script setup lang="ts">
import { ref } from 'vue'
import { TooltipArrow, TooltipContent, TooltipPortal, TooltipRoot, TooltipTrigger } from '@fex/components-vue/primitive/tooltip'
import Button from '@fex/components-vue/ui/button'
const open = ref(false)
</script>
<template><div class="flex gap-space-md"><Button variant="secondary" @click="open = !open">{{ open ? 'Close externally' : 'Open externally' }}</Button><TooltipRoot :open="open" @open-change="open = $event"><TooltipTrigger v-slot="slot"><Button v-bind="slot.props" :ref="slot.ref" variant="outline">Controlled trigger</Button></TooltipTrigger><TooltipPortal><TooltipContent>Controlled state remains external<TooltipArrow /></TooltipContent></TooltipPortal></TooltipRoot></div></template>
