// apps/angular-app/src/pages/select/local-search-demo.component.ts
import { defaultSelectFilterOption } from '@fex-design/core/select/filter-options'
import { Component } from '@angular/core'
import { frameworkOptions } from './data'
import { SimpleSelectDemo } from './simple-demo.component'
export
@Component({
  selector: 'fex-select-local-search-demo',
  standalone: true,
  imports: [SimpleSelectDemo],
  template:
    '<fex-select-simple-demo title="Local search" description="filterOption filters locally and search receives every keyword." [options]="options" [showSearch]="true" [filterOption]="filter" />',
})
class LocalSearchDemo {
  protected readonly options = frameworkOptions
  protected readonly filter = defaultSelectFilterOption
}

// apps/react-admin/src/pages/Select/local-search-demo.tsx
import { defaultSelectFilterOption } from '@fex-design/core/select/filter-options'
import {
  SelectContent,
  SelectList,
  SelectRoot,
  SelectTrigger,
} from '@fex-design/react/primitive/select'
import { frameworkOptions } from './data'
import { SelectDemoSection } from './demo-section'

export function LocalSearchDemo() {
  return (
    <SelectDemoSection
      title="Local search"
      description="filterOption filters the current options locally; onSearch still receives every keyword."
    >
      <SelectRoot
        showSearch
        filterOption={defaultSelectFilterOption}
        options={frameworkOptions}
        onSearch={() => undefined}
      >
        <SelectTrigger placeholder="请输入关键词搜索" />
        <SelectContent>
          <SelectList />
        </SelectContent>
      </SelectRoot>
    </SelectDemoSection>
  )
}
