// packages/components/svelte/src/primitive/switch/switch.svelte
<script lang="ts">
  import { switchClassName, type SwitchStyleProps } from '@fex/components-styles/switch'
  import { cn } from '@fex/utils'
  import type { Snippet } from 'svelte'
  import type { HTMLButtonAttributes } from 'svelte/elements'

  export type SwitchState = 'checked' | 'unchecked'

  interface SwitchProps extends Omit<HTMLButtonAttributes, 'checked' | 'children' | 'type'>, SwitchStyleProps {
    checked?: boolean | undefined
    defaultChecked?: boolean | undefined
    children?: Snippet<[boolean, SwitchState]> | undefined
    onCheckedChange?: ((checked: boolean, event: MouseEvent) => void) | undefined
  }

  let {
    checked,
    defaultChecked = false,
    disabled,
    size = 'default',
    class: className,
    children,
    onclick,
    onCheckedChange,
    ...rest
  }: SwitchProps = $props()

  let hasInteracted: boolean = $state(false)
  let internalChecked: boolean = $state(false)
  const currentChecked: boolean = $derived(checked ?? (hasInteracted ? internalChecked : defaultChecked))
  const switchState: SwitchState = $derived(currentChecked ? 'checked' : 'unchecked')
</script>

<button
  {...rest}
  type="button"
  role="switch"
  disabled={disabled}
  aria-checked={currentChecked}
  data-state={switchState}
  data-disabled={disabled ? 'true' : undefined}
  class={cn(switchClassName({ size }), className)}
  onclick={(event) => {
    onclick?.(event)
    if (event.defaultPrevented || disabled) return
    const nextChecked = !currentChecked
    if (checked === undefined) {
      hasInteracted = true
      internalChecked = nextChecked
    }
    onCheckedChange?.(nextChecked, event)
  }}
>
  {@render children?.(currentChecked, switchState)}
</button>

// packages/components/angular/src/primitive/switch/switch.ts
import { switchClassName, switchThumbClassName } from "@fex/components-styles/switch";
import { cn } from "@fex/utils";
import {
  booleanAttribute,
  ChangeDetectionStrategy,
  Component,
  computed,
  inject,
  input,
  output,
  signal,
} from "@angular/core";
import { createHostClassName } from "../../signals/host-class";

export type SwitchState = "checked" | "unchecked";
type SwitchSize = "sm" | "default" | "lg";

@Component({
  selector: "button[fexSwitchPrimitive]",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    type: "button",
    role: "switch",
    "[disabled]": "disabled()",
    "[attr.aria-checked]": "currentChecked()",
    "[attr.data-state]": "state()",
    "[attr.data-disabled]": "disabled() ? 'true' : null",
    "[class]": "hostClassName()",
    "(click)": "handleClick($event)",
  },
  template: "<ng-content />",
})
export class SwitchRoot {
  checked = input<boolean | undefined>();
  defaultChecked = input(false, { transform: booleanAttribute });
  disabled = input(false, { transform: booleanAttribute });
  size = input<SwitchSize>("default");
  checkedChange = output<{ checked: boolean; event: MouseEvent }>();

  private readonly hasInteracted = signal(false);
  private readonly internalChecked = signal(false);
  readonly currentChecked = computed(() =>
    this.checked() ?? (this.hasInteracted() ? this.internalChecked() : this.defaultChecked()),
  );
  readonly state = computed<SwitchState>(() => (this.currentChecked() ? "checked" : "unchecked"));
  protected readonly hostClassName = createHostClassName(() => cn(switchClassName({ size: this.size() })));

  handleClick(event: MouseEvent) {
    if (event.defaultPrevented || this.disabled()) return;
    const nextChecked = !this.currentChecked();
    if (this.checked() === undefined) {
      this.hasInteracted.set(true);
      this.internalChecked.set(nextChecked);
    }
    this.checkedChange.emit({ checked: nextChecked, event });
  }
}

@Component({
  selector: "span[fexSwitchThumb]",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    "[attr.data-state]": "resolvedState()",
    "[class]": "hostClassName()",
  },
  template: "<ng-content />",
})
export class SwitchThumb {
  private readonly root = inject(SwitchRoot, { optional: true });

  checked = input(false, { transform: booleanAttribute });
  state = input<SwitchState | undefined>();
  size = input<SwitchSize>("default");

  protected readonly resolvedState = computed<SwitchState>(() => this.state() ?? this.root?.state() ?? (this.checked() ? "checked" : "unchecked"));
  protected readonly hostClassName = createHostClassName(() => cn(switchThumbClassName({ size: this.size() })));
}
