// packages/@fex-design/react/src/primitive/aspect-ratio/aspect-ratio.tsx
import { aspectRatioClassName } from '@fex-design/styles/aspect-ratio'
import { cn } from '@fex/utils'
import type { ComponentProps, CSSProperties } from 'react'

export function AspectRatio({
  ratio,
  className,
  style,
  ...props
}: ComponentProps<'div'> & { ratio: number }) {
  return (
    <div
      data-slot="aspect-ratio"
      className={cn(aspectRatioClassName, className)}
      style={{ aspectRatio: ratio, ...style } as CSSProperties}
      {...props}
    />
  )
}

// packages/@fex-design/solid/src/primitive/aspect-ratio/aspect-ratio.tsx
import { aspectRatioClassName } from '@fex-design/styles/aspect-ratio'
import { cn } from '@fex/utils'
import { splitProps, type JSX, type ParentProps } from 'solid-js'
export function AspectRatio(
  props: ParentProps<JSX.HTMLAttributes<HTMLDivElement>> & { ratio: number },
) {
  const [local, rest] = splitProps(props, ['class', 'style', 'children', 'ratio'])
  return (
    <div
      {...rest}
      data-slot="aspect-ratio"
      class={cn(aspectRatioClassName, local.class)}
      style={{
        'aspect-ratio': local.ratio,
        ...(typeof local.style === 'object' ? local.style : {}),
      }}
    >
      {local.children}
    </div>
  )
}
