// packages/components/solid/src/primitive/date-picker/date-picker-content.tsx
import { datePickerContentClassName } from '@fex/components-styles/date-picker'
import { cn } from '@fex/utils'
import { splitProps, type ParentProps } from 'solid-js'
import { PopoverContent, PopoverPortal, type PopoverContentProps } from '../popover/popover'

export interface DatePickerContentProps extends ParentProps<PopoverContentProps> {}

export function DatePickerContent(props: DatePickerContentProps) {
  const [local, rest] = splitProps(props, ['class', 'children'])
  return (
    <PopoverPortal>
      <PopoverContent {...rest} class={cn(datePickerContentClassName, local.class)}>
        {local.children}
      </PopoverContent>
    </PopoverPortal>
  )
}

export const RangePickerContent = DatePickerContent

// packages/components/svelte/src/primitive/date-picker/date-picker-content.svelte
<script lang="ts">
  import { datePickerContentClassName } from '@fex/components-styles/date-picker'
  import { cn } from '@fex/utils'
  import type { Snippet } from 'svelte'
  import PopoverContent from '../popover/popover-content.svelte'
  import PopoverPortal from '../popover/popover-portal.svelte'

  let { class: className, children }: { class?: string; children?: Snippet } = $props()
</script>

<PopoverPortal>
  <PopoverContent class={cn(datePickerContentClassName, className)}>
    {@render children?.()}
  </PopoverContent>
</PopoverPortal>
