// packages/components/vue/src/primitive/date-picker/date-picker-preset.vue
<script setup lang="ts">
import { datePickerPresetClassName } from '@fex/components-styles/date-picker'
import { cn } from '@fex/utils'
import { computed, useAttrs } from 'vue'
import Button from '../button/button.vue'

defineOptions({ inheritAttrs: false })

const attrs = useAttrs()
const className = computed(() => cn(datePickerPresetClassName, attrs.class as string | undefined))
</script>

<template>
  <Button data-slot="date-picker-preset" v-bind="{ ...attrs, class: undefined }" :class="className">
    <slot />
  </Button>
</template>

// packages/components/svelte/src/primitive/date-picker/date-picker-preset.svelte
<script lang="ts">
  import type { Snippet } from 'svelte'
  import type { HTMLButtonAttributes } from 'svelte/elements'
  import { datePickerPresetClassName } from '@fex/components-styles/date-picker'
  import Button from '../button/button.svelte'
  interface Props extends Omit<HTMLButtonAttributes, 'children' | 'class'> { class?: string; children?: Snippet }
  let { class: className, children, ...rest }: Props = $props()
</script>

<Button {...rest} data-slot="date-picker-preset" class={className ? `${datePickerPresetClassName} ${className}` : datePickerPresetClassName}>
  {@render children?.()}
</Button>
