// packages/components/vue/src/primitive/date-picker/range-picker-trigger.vue
<script setup lang="ts">
import { getRangeInputPreviewValue } from '@fex/components-core/date-picker/range'
import { formatDatePickerValue, parseDatePickerValue } from '@fex/components-core/date-picker/value'
import { datePickerRangeInputClassName, datePickerRangeInputControlClassName, datePickerRangeSeparatorClassName, datePickerRangeTriggerClassName } from '@fex/components-styles/date-picker'
import { cn } from '@fex/utils'
import { computed, ref, watch } from 'vue'
import { CalendarIcon } from '../../icon/calendar'
import { InputClear, InputControl, InputRoot, InputSuffix } from '../input/input'
import PopoverTrigger from '../popover/popover-trigger.vue'
import { useRangePickerContext } from './context'

const props = withDefaults(defineProps<{ class?: string; startPlaceholder?: string; endPlaceholder?: string; separator?: string; status?: 'error' | 'warning' }>(), { startPlaceholder: '开始日期', endPlaceholder: '结束日期', separator: '→' })
const context = useRangePickerContext('RangePickerTrigger')
const startValue = computed(() => formatDatePickerValue(context.rangeValue.value.start ?? null, context))
const endValue = computed(() => formatDatePickerValue(context.rangeValue.value.end ?? null, context))
const startText = ref(startValue.value)
const endText = ref(endValue.value)
const focusedPart = ref<'start' | 'end' | null>(null)
watch(startValue, (next) => { startText.value = next })
watch(endValue, (next) => { endText.value = next })
watch(context.open, (next) => {
  if (!next) focusedPart.value = null
})
const previewStartValue = computed(() => getRangeInputPreviewValue(context.rangeValue.value, context.hoverValue.value, context.activePart.value, 'start'))
const previewEndValue = computed(() => getRangeInputPreviewValue(context.rangeValue.value, context.hoverValue.value, context.activePart.value, 'end'))
const previewStartText = computed(() => context.activePart.value === 'start' && previewStartValue.value ? formatDatePickerValue(previewStartValue.value, context) : startText.value)
const previewEndText = computed(() => context.activePart.value === 'end' && previewEndValue.value ? formatDatePickerValue(previewEndValue.value, context) : endText.value)
function canClear() {
  return context.allowClear !== false && Boolean(previewStartText.value || previewEndText.value)
}
function input(part: 'start' | 'end', text: string) {
  if (part === 'start') startText.value = text
  else endText.value = text
  context.setActivePart(part)
  context.setHoverValue(null)
  const result = parseDatePickerValue(text, context)
  if (result.valid) context.select(result.value)
}
function focus(part: 'start' | 'end') {
  context.setActivePart(part)
  focusedPart.value = part
  context.openPanel(part)
}
function openFromTrigger(event: MouseEvent) {
  if (context.disabled) {
    event.preventDefault()
    event.stopPropagation()
    return
  }
  const part = (event.target as HTMLElement | null)?.closest('[data-range-part]')?.getAttribute('data-range-part')
  context.openPanel(part === 'start' || part === 'end' ? part : undefined)
}
function clickTrigger(event: MouseEvent, triggerClick?: (event: MouseEvent) => void) {
  if (context.disabled) {
    event.preventDefault()
    event.stopPropagation()
    return
  }
  openFromTrigger(event)
  triggerClick?.(event)
}
function getPickerTriggerProps(triggerProps: Record<string, unknown>) {
  const { onClick: _onClick, onFocus: _onFocus, onBlur: _onBlur, ...rest } = triggerProps
  return rest
}
</script>

<template>
  <PopoverTrigger v-slot="{ props: triggerProps, ref: triggerRef }">
    <InputRoot
      v-bind="getPickerTriggerProps(triggerProps)"
      :ref="triggerRef"
      :class="cn(datePickerRangeTriggerClassName, props.class)"
      value=""
      :disabled="context.disabled"
      :read-only="context.readOnly"
      :status="props.status ?? context.status"
      @value-change="() => undefined"
      @click="(event) => clickTrigger(event, triggerProps.onClick as ((event: MouseEvent) => void) | undefined)"
    >
      <InputRoot data-range-part="start" :data-active="(context.open.value ? context.activePart.value === 'start' : focusedPart === 'start') || undefined" :value="previewStartText" :read-only="context.readOnly" :class="datePickerRangeInputClassName" @value-change="input('start', $event)">
        <InputControl :class="cn(datePickerRangeInputControlClassName, previewStartText !== startText && 'text-muted-foreground')" :placeholder="props.startPlaceholder" @click="focus('start')" @focus="focus('start')" />
      </InputRoot>
      <span aria-hidden="true" :class="datePickerRangeSeparatorClassName">{{ props.separator }}</span>
      <InputRoot data-range-part="end" :data-active="(context.open.value ? context.activePart.value === 'end' : focusedPart === 'end') || undefined" :value="previewEndText" :read-only="context.readOnly" :class="datePickerRangeInputClassName" @value-change="input('end', $event)">
        <InputControl :class="cn(datePickerRangeInputControlClassName, previewEndText !== endText && 'text-muted-foreground')" :placeholder="props.endPlaceholder" @click="focus('end')" @focus="focus('end')" />
      </InputRoot>
      <InputClear
        v-if="canClear()"
        :force-mount="true"
        aria-label="清除日期范围"
        @pointerdown.stop.prevent
        @click.stop.prevent="context.clear()"
      />
      <InputSuffix v-else><slot name="suffix"><CalendarIcon class="size-4" /></slot></InputSuffix>
    </InputRoot>
  </PopoverTrigger>
</template>

// packages/components/svelte/src/primitive/date-picker/range-picker-trigger.svelte
<script lang="ts">
  import { getRangeInputPreviewValue } from '@fex/components-core/date-picker/range'
  import { formatDatePickerValue, parseDatePickerValue } from '@fex/components-core/date-picker/value'
  import { datePickerRangeInputClassName, datePickerRangeInputControlClassName, datePickerRangeSeparatorClassName, datePickerRangeTriggerClassName } from '@fex/components-styles/date-picker'
  import { cn } from '@fex/utils'
  import CalendarIcon from '../../icon/calendar.svelte'
  import InputClear from '../input/input-clear.svelte'
  import InputControl from '../input/input-control.svelte'
  import InputRoot from '../input/input-root.svelte'
  import InputSuffix from '../input/input-suffix.svelte'
  import PopoverTrigger from '../popover/popover-trigger.svelte'
  import { useRangePickerContext } from './context'

  let { class: className, startPlaceholder = '开始日期', endPlaceholder = '结束日期', separator = '→', status }: { class?: string; startPlaceholder?: string; endPlaceholder?: string; separator?: string; status?: 'error' | 'warning' } = $props()
  const context = useRangePickerContext('RangePickerTrigger')
  const startValue = $derived(formatDatePickerValue(context.getRangeValue().start ?? null, context))
  const endValue = $derived(formatDatePickerValue(context.getRangeValue().end ?? null, context))
  let startText = $state(startValue)
  let endText = $state(endValue)
  let focusedPart = $state<'start' | 'end' | null>(null)
  $effect(() => { startText = startValue; endText = endValue })
  $effect(() => { if (!context.getOpen()) focusedPart = null })
  const previewStartValue = $derived(getRangeInputPreviewValue(context.getRangeValue(), context.getHoverValue(), context.getActivePart(), 'start'))
  const previewEndValue = $derived(getRangeInputPreviewValue(context.getRangeValue(), context.getHoverValue(), context.getActivePart(), 'end'))
  const previewStartText = $derived(context.getActivePart() === 'start' && previewStartValue ? formatDatePickerValue(previewStartValue, context) : startText)
  const previewEndText = $derived(context.getActivePart() === 'end' && previewEndValue ? formatDatePickerValue(previewEndValue, context) : endText)
  const hasValue = $derived(Boolean(context.getRangeValue().start || context.getRangeValue().end))
  function input(part: 'start' | 'end', text: string) { if (part === 'start') startText = text; else endText = text; context.setActivePart(part); context.setHoverValue(null); const result = parseDatePickerValue(text, context); if (result.valid) context.select(result.value as never) }
  function focus(part: 'start' | 'end') { context.setActivePart(part); focusedPart = part; context.openPanel(part) }
  function open(event: MouseEvent) {
    if (context.disabled) {
      event.preventDefault()
      event.stopPropagation()
      return
    }
    const part = (event.target as HTMLElement).closest('[data-range-part]')?.getAttribute('data-range-part')
    context.openPanel(part === 'start' || part === 'end' ? part : undefined)
  }
</script>

<PopoverTrigger>{#snippet children(slot)}
  <InputRoot
    action={slot.action}
    aria-haspopup={slot.props['aria-haspopup']}
    aria-expanded={slot.props['aria-expanded']}
    data-state={slot.props['data-state']}
    value=""
    disabled={context.disabled}
    readOnly={context.readOnly}
    status={status ?? context.status}
    class={cn(datePickerRangeTriggerClassName, className)}
    onValueChange={() => undefined}
    onclick={open}
  >
    <InputRoot data-range-part="start" data-active={(context.getOpen() ? context.getActivePart() === 'start' : focusedPart === 'start') || undefined} value={previewStartText} readOnly={context.readOnly} class={datePickerRangeInputClassName} onValueChange={(value) => input('start', value)}><InputControl class={cn(datePickerRangeInputControlClassName, previewStartText !== startText && 'text-muted-foreground')} placeholder={startPlaceholder} onfocus={() => focus('start')} /></InputRoot>
    <span aria-hidden="true" class={datePickerRangeSeparatorClassName}>{separator}</span>
    <InputRoot data-range-part="end" data-active={(context.getOpen() ? context.getActivePart() === 'end' : focusedPart === 'end') || undefined} value={previewEndText} readOnly={context.readOnly} class={datePickerRangeInputClassName} onValueChange={(value) => input('end', value)}><InputControl class={cn(datePickerRangeInputControlClassName, previewEndText !== endText && 'text-muted-foreground')} placeholder={endPlaceholder} onfocus={() => focus('end')} /></InputRoot>
    {#if context.allowClear && hasValue}<InputClear forceMount onpointerdown={(event) => event.stopPropagation()} onclick={(event) => { event.stopPropagation(); context.clear() }} />{:else}<InputSuffix><CalendarIcon /></InputSuffix>{/if}
  </InputRoot>
{/snippet}</PopoverTrigger>
