// apps/react-admin/src/pages/TimePicker/decoration-demo.tsx
import { CalendarIcon } from '@fex/components-react/icon/calendar'
import { Card } from '@fex/components-react/ui/card'
import { DemoTimePicker } from './demo-time-picker'
export function DecorationDemo() {
  return (
    <Card title="前后缀" description="复用 Input primitive 的 Prefix 和 Suffix。">
      <DemoTimePicker
        prefix={<span className="text-xs">开始</span>}
        suffix={<CalendarIcon className="size-4" />}
      />
    </Card>
  )
}

// apps/vue-admin/src/pages/TimePicker/decoration-demo.vue
<script setup lang="ts">
import { CalendarIcon } from '@fex/components-vue/icon/calendar'
import Card from '@fex/components-vue/ui/card'
import DemoTimePicker from './demo-time-picker.vue'
</script>
<template>
  <Card title="前后缀"
    ><DemoTimePicker
      ><template #prefix><span class="text-xs">开始</span></template
      ><template #suffix><CalendarIcon class="size-4" /></template></DemoTimePicker
  ></Card>
</template>
