// packages/components/svelte/src/primitive/upload/upload-list.svelte
<script lang="ts" generics="TResponse">
  import type { UploadItem } from '@fex/components-core/upload/types'
  import { uploadListClassName } from '@fex/components-styles/upload'
  import { cn } from '@fex/utils'
  import type { Snippet } from 'svelte'
  import type { HTMLAttributes } from 'svelte/elements'
  import { readable } from 'svelte/store'
  import { useUploadContext } from './context'
  let { children, class: className, ...rest }: Omit<HTMLAttributes<HTMLDivElement>, 'children'> & { children: Snippet<[readonly UploadItem<TResponse>[]]> } = $props()
  const { upload, listId } = useUploadContext<TResponse>()
  const items = readable(upload.getItems(), (set) => upload.subscribeItems(() => set(upload.getItems())))
</script>
{#if $items.length}<div {...rest} id={listId} role="list" class={cn(uploadListClassName(), className)}>{@render children($items)}</div>{/if}

// packages/components/vue/src/primitive/upload/upload-list.vue
<script setup lang="ts">
import { uploadListClassName } from '@fex/components-styles/upload'
import { cn } from '@fex/utils'
import { onScopeDispose, shallowRef, useAttrs } from 'vue'
import { useUploadContext } from './context'
defineOptions({ inheritAttrs: false })
const attrs = useAttrs()
const { upload, listId } = useUploadContext()
const items = shallowRef(upload.getItems())
const unsubscribe = upload.subscribeItems(() => { items.value = upload.getItems() })
onScopeDispose(unsubscribe)
</script>
<template><div v-if="items.length" v-bind="{ ...attrs, class: undefined }" :id="listId" role="list" :class="cn(uploadListClassName(), attrs.class as string | undefined)"><slot :items="items" /></div></template>
