// apps/solid-admin/src/routes/components/index.tsx
import { lazy } from 'solid-js'
import type { AppRoute } from '../types'

const ButtonPage = lazy(() =>
  import('../../pages/Button').then((module) => ({ default: module.ButtonPage })),
)
const AutoCompletePage = lazy(() => import('../../pages/AutoComplete').then((module) => ({ default: module.AutoCompletePage })))
const CalendarPage = lazy(() =>
  import('../../pages/Calendar').then((module) => ({ default: module.CalendarPage })),
)
const CardPage = lazy(() =>
  import('../../pages/Card').then((module) => ({ default: module.CardPage })),
)
const CheckboxPage = lazy(() =>
  import('../../pages/Checkbox').then((module) => ({ default: module.CheckboxPage })),
)
const DialogPage = lazy(() =>
  import('../../pages/Dialog').then((module) => ({ default: module.DialogPage })),
)
const AlertPage = lazy(() =>
  import('../../pages/Alert').then((module) => ({ default: module.AlertPage })),
)
const BadgePage = lazy(() =>
  import('../../pages/Badge').then((module) => ({ default: module.BadgePage })),
)
const EmptyPage = lazy(() =>
  import('../../pages/Empty').then((module) => ({ default: module.EmptyPage })),
)
const InputPage = lazy(() =>
  import('../../pages/Input').then((module) => ({ default: module.InputPage })),
)
const FormPage = lazy(() => import('../../pages/Form').then((module) => ({ default: module.FormPage })))
const TransferPage = lazy(() => import('../../pages/Transfer').then((module) => ({ default: module.TransferPage })))
const KbdPage = lazy(() =>
  import('../../pages/Kbd').then((module) => ({ default: module.KbdPage })),
)
const ListboxPage = lazy(() =>
  import('../../pages/Listbox').then((module) => ({ default: module.ListboxPage })),
)
const MenuPage = lazy(() =>
  import('../../pages/Menu').then((module) => ({ default: module.MenuPage })),
)
const PaginationPage = lazy(() =>
  import('../../pages/Pagination').then((module) => ({ default: module.PaginationPage })),
)
const PopoverPage = lazy(() =>
  import('../../pages/Popover').then((module) => ({ default: module.PopoverPage })),
)
const RadioPage = lazy(() =>
  import('../../pages/Radio').then((module) => ({ default: module.RadioPage })),
)
const RatePage = lazy(() =>
  import('../../pages/Rate').then((module) => ({ default: module.RatePage })),
)
const SpinnerPage = lazy(() =>
  import('../../pages/Spinner').then((module) => ({ default: module.SpinnerPage })),
)
const SliderPage = lazy(() =>
  import('../../pages/Slider').then((module) => ({ default: module.SliderPage })),
)
const ScrollbarPage = lazy(() =>
  import('../../pages/Scrollbar').then((module) => ({ default: module.ScrollbarPage })),
)
const SelectPage = lazy(() => import('../../pages/Select').then((module) => ({ default: module.SelectPage })))
const SwitchPage = lazy(() =>
  import('../../pages/Switch').then((module) => ({ default: module.SwitchPage })),
)
const TablePage = lazy(() =>
  import('../../pages/Table').then((module) => ({ default: module.TablePage })),
)
const TabsPage = lazy(() =>
  import('../../pages/Tabs').then((module) => ({ default: module.TabsPage })),
)
const ToastPage = lazy(() =>
  import('../../pages/Toast').then((module) => ({ default: module.ToastPage })),
)
const SortablePage = lazy(() =>
  import('../../pages/Sortable').then((module) => ({ default: module.SortablePage })),
)
const InteractionsPage = lazy(() =>
  import('../../pages/Interactions').then((module) => ({ default: module.InteractionsPage })),
)
const ResizablePage = lazy(() =>
  import('../../pages/Resizable').then((module) => ({ default: module.ResizablePage })),
)
const TextareaPage = lazy(() =>
  import('../../pages/Textarea').then((module) => ({ default: module.TextareaPage })),
)
const TimePickerPage = lazy(() => import('../../pages/TimePicker').then((module) => ({ default: module.TimePickerPage })))
const DataGridPage = lazy(() =>
  import('../../pages/DataGrid').then((module) => ({ default: module.DataGridPage })),
)
const DatePickerPage = lazy(() =>
  import('../../pages/DatePicker').then((module) => ({ default: module.DatePickerPage })),
)
const TreePage = lazy(() =>
  import('../../pages/Tree').then((module) => ({ default: module.TreePage })),
)
const CarouselPage = lazy(() => import('../../pages/Carousel').then((module) => ({ default: module.CarouselPage })))

export const componentRoutes: AppRoute[] = [
  { path: '/auto-complete', component: AutoCompletePage },
  { path: '/carousel', component: CarouselPage },
  {
    path: '/data-grid',
    component: DataGridPage,
  },
  {
    path: '/date-picker',
    component: DatePickerPage,
  },
  {
    path: '/button',
    component: ButtonPage,
  },
  {
    path: '/calendar',
    component: CalendarPage,
  },
  {
    path: '/card',
    component: CardPage,
  },
  {
    path: '/checkbox',
    component: CheckboxPage,
  },
  {
    path: '/dialog',
    component: DialogPage,
  },
  {
    path: '/alert',
    component: AlertPage,
  },
  {
    path: '/badge',
    component: BadgePage,
  },
  {
    path: '/empty',
    component: EmptyPage,
  },
  {
    path: '/input',
    component: InputPage,
  },
  {
    path: '/form',
    component: FormPage,
  },
  {
    path: '/kbd',
    component: KbdPage,
  },
  {
    path: '/listbox',
    component: ListboxPage,
  },
  {
    path: '/menu',
    component: MenuPage,
  },
  {
    path: '/pagination',
    component: PaginationPage,
  },
  {
    path: '/popover',
    component: PopoverPage,
  },
  {
    path: '/radio',
    component: RadioPage,
  },
  {
    path: '/rate',
    component: RatePage,
  },
  {
    path: '/spinner',
    component: SpinnerPage,
  },
  {
    path: '/slider',
    component: SliderPage,
  },
  {
    path: '/scrollbar',
    component: ScrollbarPage,
  },
  {
    path: '/select',
    component: SelectPage,
  },
  {
    path: '/switch',
    component: SwitchPage,
  },
  {
    path: '/table',
    component: TablePage,
  },
  {
    path: '/tabs',
    component: TabsPage,
  },
  {
    path: '/toast',
    component: ToastPage,
  },
  {
    path: '/sortable',
    component: SortablePage,
  },
  {
    path: '/interactions',
    component: InteractionsPage,
  },
  {
    path: '/resizable',
    component: ResizablePage,
  },
  {
    path: '/textarea',
    component: TextareaPage,
  },
  { path: '/time-picker', component: TimePickerPage },
  {
    path: '/tree',
    component: TreePage,
  },
  { path: '/transfer', component: TransferPage },
].sort((left, right) => left.path.localeCompare(right.path))

// apps/react-admin/src/routes/components/index.tsx
import { createLazyRouteElement } from '../lazy'
import { ListboxPage } from '../../pages/Listbox'

export const componentRoutes = [
  { path: '/auto-complete', element: createLazyRouteElement(() => import('../../pages/AutoComplete'), 'AutoCompletePage') },
  { path: '/carousel', element: createLazyRouteElement(() => import('../../pages/Carousel'), 'CarouselPage') },
  {
    path: '/data-grid',
    element: createLazyRouteElement(() => import('../../pages/DataGrid'), 'DataGridPage'),
  },
  {
    path: '/date-picker',
    element: createLazyRouteElement(() => import('../../pages/DatePicker'), 'DatePickerPage'),
  },
  {
    path: '/tree',
    element: createLazyRouteElement(() => import('../../pages/Tree'), 'TreePage'),
  },
  {
    path: '/transfer',
    element: createLazyRouteElement(() => import('../../pages/Transfer'), 'TransferPage'),
  },
  {
    path: '/button',
    element: createLazyRouteElement(() => import('../../pages/Button'), 'ButtonPage'),
  },
  {
    path: '/card',
    element: createLazyRouteElement(() => import('../../pages/Card'), 'CardPage'),
  },
  {
    path: '/calendar',
    element: createLazyRouteElement(() => import('../../pages/Calendar'), 'CalendarPage'),
  },
  {
    path: '/checkbox',
    element: createLazyRouteElement(() => import('../../pages/Checkbox'), 'CheckboxPage'),
  },
  {
    path: '/dialog',
    element: createLazyRouteElement(() => import('../../pages/Dialog'), 'DialogPage'),
  },
  {
    path: '/alert',
    element: createLazyRouteElement(() => import('../../pages/Alert'), 'AlertPage'),
  },
  {
    path: '/badge',
    element: createLazyRouteElement(() => import('../../pages/Badge'), 'BadgePage'),
  },
  {
    path: '/empty',
    element: createLazyRouteElement(() => import('../../pages/Empty'), 'EmptyPage'),
  },
  {
    path: '/input',
    element: createLazyRouteElement(() => import('../../pages/Input'), 'InputPage'),
  },
  {
    path: '/form',
    element: createLazyRouteElement(() => import('../../pages/Form'), 'FormPage'),
  },
  {
    path: '/kbd',
    element: createLazyRouteElement(() => import('../../pages/Kbd'), 'KbdPage'),
  },
  {
    path: '/listbox',
    element: <ListboxPage />,
  },
  {
    path: '/menu',
    element: createLazyRouteElement(() => import('../../pages/Menu'), 'MenuPage'),
  },
  {
    path: '/pagination',
    element: createLazyRouteElement(() => import('../../pages/Pagination'), 'PaginationPage'),
  },
  {
    path: '/popover',
    element: createLazyRouteElement(() => import('../../pages/Popover'), 'PopoverPage'),
  },
  {
    path: '/radio',
    element: createLazyRouteElement(() => import('../../pages/Radio'), 'RadioPage'),
  },
  {
    path: '/rate',
    element: createLazyRouteElement(() => import('../../pages/Rate'), 'RatePage'),
  },
  {
    path: '/spinner',
    element: createLazyRouteElement(() => import('../../pages/Spinner'), 'SpinnerPage'),
  },
  {
    path: '/slider',
    element: createLazyRouteElement(() => import('../../pages/Slider'), 'SliderPage'),
  },
  {
    path: '/scrollbar',
    element: createLazyRouteElement(() => import('../../pages/Scrollbar'), 'ScrollbarPage'),
  },
  {
    path: '/select',
    element: createLazyRouteElement(() => import('../../pages/Select'), 'SelectPage'),
  },
  {
    path: '/switch',
    element: createLazyRouteElement(() => import('../../pages/Switch'), 'SwitchPage'),
  },
  {
    path: '/table',
    element: createLazyRouteElement(() => import('../../pages/Table'), 'TablePage'),
  },
  {
    path: '/tabs',
    element: createLazyRouteElement(() => import('../../pages/Tabs'), 'TabsPage'),
  },
  {
    path: '/toast',
    element: createLazyRouteElement(() => import('../../pages/Toast'), 'ToastPage'),
  },
  {
    path: '/time-picker',
    element: createLazyRouteElement(() => import('../../pages/TimePicker'), 'TimePickerPage'),
  },
  {
    path: '/sortable',
    element: createLazyRouteElement(() => import('../../pages/Sortable'), 'SortablePage'),
  },
  {
    path: '/interactions',
    element: createLazyRouteElement(() => import('../../pages/Interactions'), 'InteractionsPage'),
  },
  {
    path: '/resizable',
    element: createLazyRouteElement(() => import('../../pages/Resizable'), 'ResizablePage'),
  },
  {
    path: '/textarea',
    element: createLazyRouteElement(() => import('../../pages/Textarea'), 'TextareaPage'),
  },
].sort((left, right) => left.path.localeCompare(right.path))
