// packages/components/react/src/primitive/switch/switch-context.ts
import { createContext, use } from 'react'
import type { SwitchStyleProps } from '@fex/components-styles/switch'
import type { SwitchState } from './switch'
export interface SwitchContextValue { checked: boolean, state: SwitchState, size: SwitchStyleProps['size'] }
export const SwitchContext = createContext<SwitchContextValue | null>(null)
export function useSwitchContext(componentName: string) { const context = use(SwitchContext); if (!context) throw new Error(`${componentName} must be used inside SwitchRoot.`); return context }

// packages/components/solid/src/primitive/switch/switch-context.ts
import { createContext, useContext, type Accessor } from 'solid-js'
import type { SwitchStyleProps } from '@fex/components-styles/switch'
import type { SwitchState } from './switch'
export interface SwitchContextValue { checked: Accessor<boolean>, state: Accessor<SwitchState>, size: Accessor<SwitchStyleProps['size']> }
export const SwitchContext = createContext<SwitchContextValue>()
export function useSwitchContext(componentName: string) { const context = useContext(SwitchContext); if (!context) throw new Error(`${componentName} must be used inside SwitchRoot.`); return context }
