// packages/@fex-design/svelte/src/primitive/date-picker/date-picker-root.svelte
<script lang="ts">
  import type { CalendarDate, CalendarValue, CalendarWeekday } from '@fex-design/core/calendar'
  import type { DatePickerPicker } from '@fex-design/core/date-picker/types'
  import type { Snippet } from 'svelte'
  import { setContext } from 'svelte'
  import Popover from '../popover/popover.svelte'
  import { datePickerContextKey, type DatePickerSelectionValue } from './context'
  import { useDatePicker } from './date-picker-state.svelte'

  interface Props {
    children?: Snippet
    value?: DatePickerSelectionValue | undefined
    defaultValue?: DatePickerSelectionValue | undefined
    open?: boolean | undefined
    defaultOpen?: boolean | undefined
    picker?: DatePickerPicker | undefined
    status?: 'error' | 'warning' | undefined
    multiple?: boolean | undefined
    needConfirm?: boolean | undefined
    disabled?: boolean | undefined
    readOnly?: boolean | undefined
    allowClear?: boolean | undefined
    format?: string | undefined
    weekStartsOn?: CalendarWeekday | undefined
    minDate?: CalendarDate | undefined
    maxDate?: CalendarDate | undefined
    disabledDate?: ((date: CalendarDate) => boolean) | undefined
    onChange?: ((value: DatePickerSelectionValue) => void) | undefined
    onOpenChange?: ((open: boolean) => void) | undefined
  }
  let props: Props = $props()
  // svelte-ignore state_referenced_locally -- the props proxy remains live inside the controller adapter.
  const picker = useDatePicker<CalendarValue>(props)
  setContext(datePickerContextKey, picker)
</script>

<Popover open={picker.getOpen()} trigger={['focus', 'click']} placement="bottom" sideOffset={6} onOpenChange={(open) => picker.setOpen(open)}>
  {@render props.children?.()}
</Popover>

// packages/components/react/src/primitive/date-picker/date-picker-root.tsx
import type { CalendarValue } from '@fex/components-core/calendar'
import type { ReactNode } from 'react'
import { PopoverRoot, type PopoverRootProps } from '../popover/popover'
import { DatePickerContext } from './context'
import { useDatePicker, type UseDatePickerOptions } from './use-date-picker'

export interface DatePickerRootProps<TValue extends CalendarValue = CalendarValue>
  extends
    Omit<PopoverRootProps, 'open' | 'defaultOpen' | 'onOpenChange' | 'children'>,
    UseDatePickerOptions<TValue> {
  children?: ReactNode
}

export function DatePickerRoot<TValue extends CalendarValue = CalendarValue>({
  children,
  placement = 'bottom',
  sideOffset = 6,
  picker,
  status,
  value,
  defaultValue,
  open,
  defaultOpen,
  multiple,
  needConfirm,
  disabled,
  readOnly,
  allowClear,
  format,
  weekStartsOn,
  minDate,
  maxDate,
  disabledDate,
  onChange,
  onOpenChange,
  ...props
}: DatePickerRootProps<TValue>) {
  const datePicker = useDatePicker<TValue>({
    ...(picker ? { picker } : {}),
    ...(status ? { status } : {}),
    ...(value !== undefined ? { value } : {}),
    ...(defaultValue !== undefined ? { defaultValue } : {}),
    ...(open !== undefined ? { open } : {}),
    ...(defaultOpen !== undefined ? { defaultOpen } : {}),
    ...(multiple !== undefined ? { multiple } : {}),
    ...(needConfirm !== undefined ? { needConfirm } : {}),
    ...(disabled !== undefined ? { disabled } : {}),
    ...(readOnly !== undefined ? { readOnly } : {}),
    ...(allowClear !== undefined ? { allowClear } : {}),
    ...(format ? { format } : {}),
    ...(weekStartsOn !== undefined ? { weekStartsOn } : {}),
    ...(minDate ? { minDate } : {}),
    ...(maxDate ? { maxDate } : {}),
    ...(disabledDate ? { disabledDate } : {}),
    ...(onChange ? { onChange } : {}),
    ...(onOpenChange ? { onOpenChange } : {}),
  })

  return (
    <PopoverRoot
      {...props}
      open={datePicker.open}
      onOpenChange={datePicker.setOpen}
      placement={placement}
      sideOffset={sideOffset}
      trigger={['focus', 'click']}
    >
      <DatePickerContext value={datePicker as never}>{children}</DatePickerContext>
    </PopoverRoot>
  )
}
