// apps/react-admin/src/pages/Tree/virtual-demo.tsx
import { Button } from '@fex/components-react/ui/button'
import { expansionFeature } from '@fex/components-core'
import { useRef } from 'react'
import { createLargeTreeData, departmentFieldNames } from './data'
import { DemoTree, type TreeVirtualViewportHandle } from './demo-tree'
import { TreeDemoSection } from './demo-section'

const largeTreeData = createLargeTreeData()

export function VirtualTreeDemo() {
  const viewportRef = useRef<TreeVirtualViewportHandle>(null)

  return (
    <TreeDemoSection
      title="Virtualization and locate"
      description="Only viewport rows mount. scrollToKey resolves a visible index before asking TanStack Virtual to scroll."
    >
      <div className="mb-space-md flex gap-space-sm">
        <Button
          size="sm"
          variant="outline"
          onClick={() =>
            viewportRef.current?.scrollToKey('large-3200', { reveal: true, align: 'start' })
          }
        >
          Locate row 3201
        </Button>
      </div>
      <DemoTree
        treeData={largeTreeData}
        fieldNames={departmentFieldNames}
        isLeaf={(node) => node.childCount === 0}
        features={[expansionFeature({ defaultExpandedKeys: ['large-root'] })]}
        virtual
        height={320}
        virtualViewportRef={viewportRef}
        className="rounded-md border border-border bg-background p-space-sm"
      />
    </TreeDemoSection>
  )
}

// apps/svelte-admin/src/routes/tree/virtual-demo.svelte
<script lang="ts">
  import { expansionFeature } from '@fex/components-core'
  import type { TreeKey } from '@fex/components-core/tree/types'
  import Button from '@fex/components-svelte/ui/button'
  import Card from '@fex/components-svelte/ui/card'
  import DemoTree from './demo-tree.svelte'
  import { createLargeTreeData, departmentFieldNames } from './data'

  const data = createLargeTreeData()
  let viewport:
    | { scrollToKey(key: TreeKey, settings?: { align?: 'auto' | 'start' | 'center' | 'end'; reveal?: boolean }): boolean }
    | undefined
</script>

<Card title="Virtualization and locate" description="Only viewport rows mount. scrollToKey resolves a visible index before asking TanStack Virtual to scroll.">
  <div class="mb-space-md flex gap-space-sm">
    <Button size="sm" variant="outline" onclick={() => viewport?.scrollToKey('large-3200', { reveal: true, align: 'start' })}>
      Locate row 3201
    </Button>
  </div>
  <DemoTree
    bind:this={viewport}
    treeData={data}
    fieldNames={departmentFieldNames}
    isLeaf={(node) => node.childCount === 0}
    features={[expansionFeature({ defaultExpandedKeys: ['large-root'] })]}
    virtual
    height={320}
    class="rounded-md border border-border bg-background p-space-sm"
  />
</Card>
