// apps/angular-app/src/pages/transfer/basic-demo.component.ts
import { ChangeDetectionStrategy, Component, signal } from '@angular/core'
import { Transfer } from '@fex-design/angular/primitive/transfer'
import Card from '@fex-design/angular/ui/card'
import { transferFieldNames, transferMembers } from './data'

@Component({
  selector: 'fex-transfer-basic-demo',
  standalone: true,
  imports: [Card, Transfer],
  templateUrl: './basic-demo.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class TransferBasicDemoComponent {
  protected readonly members = transferMembers
  protected readonly fieldNames = transferFieldNames
  protected readonly targetKeys = signal<readonly (string | number)[]>(['susan'])
}

<fex-card
  title="Basic, controlled and uncontrolled"
  description="The first Transfer owns its target keys; the second exposes target keys and complete moved items through onChange meta."
>
  <div class="grid gap-space-lg xl:grid-cols-2">
    <section>
      <h3 class="mb-space-sm text-sm font-medium">Uncontrolled</h3>
      <fex-transfer
        [items]="members"
        [fieldNames]="fieldNames"
        [defaultTargetKeys]="['grace']"
        [title]="{ source: 'Available', target: 'Assigned' }"
      />
    </section>
    <section>
      <h3 class="mb-space-sm text-sm font-medium">Controlled</h3>
      <fex-transfer
        [items]="members"
        [fieldNames]="fieldNames"
        [targetKeys]="targetKeys()"
        [title]="{ source: 'Team directory', target: 'Project team' }"
        (targetKeysChange)="targetKeys.set($event)"
      />
      <p class="mt-space-xs text-xs text-muted-foreground">
        Target keys: {{ targetKeys().join(', ') }}
      </p>
    </section>
  </div>
</fex-card>

// apps/solid-admin/src/pages/Transfer/basic-demo.tsx
import { Transfer } from '@fex-design/solid/primitive/transfer'
import { Card } from '@fex-design/solid/ui/card'
import { createSignal } from 'solid-js'
import { fieldNames, members } from './data'
export function BasicDemo() {
  const [targetKeys, setTargetKeys] = createSignal<readonly (string | number)[]>(['susan'])
  return (
    <Card
      title="Basic, controlled and uncontrolled"
      description="The first Transfer owns its target keys; the second exposes target keys and complete moved items through onChange meta."
    >
      <div class="grid gap-space-lg xl:grid-cols-2">
        <section class="space-y-space-sm">
          <h3 class="text-sm font-medium">Uncontrolled</h3>
          <Transfer
            items={members}
            fieldNames={fieldNames}
            defaultTargetKeys={['grace']}
            title={{ source: 'Available', target: 'Assigned' }}
          />
        </section>
        <section class="space-y-space-sm">
          <h3 class="text-sm font-medium">Controlled</h3>
          <Transfer
            items={members}
            fieldNames={fieldNames}
            targetKeys={targetKeys()}
            onChange={setTargetKeys}
            title={{ source: 'Team directory', target: 'Project team' }}
          />
          <p class="text-xs text-muted-foreground">
            Target keys: {targetKeys().join(', ') || 'none'}
          </p>
        </section>
      </div>
    </Card>
  )
}
