// apps/react-admin/src/pages/Select/clear-demo.tsx
import {
  SelectContent,
  SelectList,
  SelectRoot,
  SelectTrigger,
} from '@fex/components-react/primitive/select'
import { frameworkOptions } from './data'
import { SelectDemoSection } from './demo-section'

export function ClearDemo() {
  return (
    <SelectDemoSection
      title="Clear"
      description="Clear and the dropdown indicator share one suffix position and never render together."
    >
      <SelectRoot clearable options={frameworkOptions} defaultValue="solid">
        <SelectTrigger placeholder="请选择框架" />
        <SelectContent>
          <SelectList />
        </SelectContent>
      </SelectRoot>
    </SelectDemoSection>
  )
}

// apps/vue-admin/src/pages/Select/clear-demo.vue
<script setup lang="ts">
import { SelectContent, SelectRoot, SelectTrigger } from '@fex/components-vue/primitive/select'
import { frameworkOptions } from './data'
import Demo from './demo-section.vue'
</script>
<template>
  <Demo
    title="Clear"
    description="Clear and the dropdown indicator share one suffix position and never render together."
    ><SelectRoot clearable default-value="solid" :options="frameworkOptions"
      ><SelectTrigger placeholder="请选择" /><SelectContent /></SelectRoot
  ></Demo>
</template>
