// apps/react-app/src/pages/Select/multi-field-search-demo.tsx
import { defaultSelectFilterOption } from '@fex-design/core/select/filter-options'
import {
  SelectContent,
  SelectList,
  SelectRoot,
  SelectTrigger,
} from '@fex-design/react/primitive/select'
import { frameworkOptions } from './data'
import { SelectDemoSection } from './demo-section'

export function MultiFieldSearchDemo() {
  return (
    <SelectDemoSection
      title="Multi-field search"
      description="Search label, searchText and keywords; try google or meta."
    >
      <SelectRoot showSearch options={frameworkOptions} filterOption={defaultSelectFilterOption}>
        <SelectTrigger placeholder="输入 google 或 meta" />
        <SelectContent>
          <SelectList />
        </SelectContent>
      </SelectRoot>
    </SelectDemoSection>
  )
}

// apps/vue-admin/src/pages/Select/multi-field-search-demo.vue
<script setup lang="ts">
import { defaultSelectFilterOption } from '@fex/components-core/select/filter-options'
import { SelectContent, SelectRoot, SelectTrigger } from '@fex/components-vue/primitive/select'
import { frameworkOptions } from './data'
import Demo from './demo-section.vue'
</script>
<template>
  <Demo
    title="Multi-field search"
    description="Search label, searchText and keywords; try google or meta."
    ><SelectRoot show-search :options="frameworkOptions" :filter-option="defaultSelectFilterOption"
      ><SelectTrigger placeholder="输入 google 或 meta" /><SelectContent /></SelectRoot
  ></Demo>
</template>
