// apps/angular-app/src/pages/select/popup-render-demo.component.ts
import type { SelectOption } from '@fex-design/core/select/types'
import { ChangeDetectionStrategy, Component } from '@angular/core'
import { PlusIcon } from '@fex-design/angular/icon/plus'
import { InputControl, InputRoot } from '@fex-design/angular/primitive/input'
import {
  SelectContent,
  SelectList,
  SelectRoot,
  SelectTrigger,
} from '@fex-design/angular/primitive/select'
import { Button } from '@fex-design/angular/ui/button'
import Card from '@fex-design/angular/ui/card'
export
@Component({
  selector: 'fex-select-popup-render-demo',
  standalone: true,
  imports: [
    Card,
    PlusIcon,
    InputRoot,
    InputControl,
    Button,
    SelectRoot,
    SelectTrigger,
    SelectContent,
    SelectList,
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
  templateUrl: './popup-render-demo.component.html',
})
class PopupRenderDemo {
  protected options: SelectOption[] = [
    { value: 'jack', label: 'Jack' },
    { value: 'lucy', label: 'Lucy' },
  ]
  protected name = ''
  protected add() {
    const label = this.name.trim()
    if (!label || this.options.some((item) => item.value === label.toLocaleLowerCase())) return
    this.options = [...this.options, { value: label.toLocaleLowerCase(), label }]
    this.name = ''
  }
}

<fex-card title="Custom popup rendering" description="Custom content extends the default menu."
  ><div class="max-w-md">
    <fex-select [options]="options"
      ><fex-select-trigger placeholder="自定义下拉面板" /><fex-select-content
        ><fex-select-list />
        <div
          class="flex items-center gap-2 border-t border-border p-2"
          (pointerdown)="$event.stopPropagation()"
        >
          <fex-input-root class="flex-1" [value]="name" (valueChange)="name = $event"
            ><input fexInputControl placeholder="请输入新选项" /></fex-input-root
          ><button fexButton size="sm" variant="ghost" (click)="add()">
            <fex-plus-icon />添加
          </button>
        </div></fex-select-content
      ></fex-select
    >
  </div></fex-card
>

// apps/vue-admin/src/pages/Select/popup-render-demo.vue
<script setup lang="ts">
import type { SelectOption } from '@fex-design/core/select/types'
import { PlusIcon } from '@fex-design/vue/icon/plus'
import { InputControl, InputRoot } from '@fex-design/vue/primitive/input'
import {
  SelectContent,
  SelectList,
  SelectRoot,
  SelectTrigger,
} from '@fex-design/vue/primitive/select'
import Button from '@fex-design/vue/ui/button'
import { ref } from 'vue'
import Demo from './demo-section.vue'
const options = ref<SelectOption[]>([
  { value: 'jack', label: 'Jack' },
  { value: 'lucy', label: 'Lucy' },
])
const name = ref('')
function addItem() {
  const label = name.value.trim()
  if (!label || options.value.some((item) => item.value === label.toLocaleLowerCase())) return
  options.value = [...options.value, { value: label.toLocaleLowerCase(), label }]
  name.value = ''
}
</script>
<template>
  <Demo
    title="Custom popup rendering"
    description="The content slot wraps the default menu with interactive custom content."
    ><SelectRoot :options="options"
      ><SelectTrigger placeholder="自定义下拉面板" /><SelectContent
        ><SelectList />
        <div class="flex items-center gap-2 border-t border-border p-2" @pointerdown.stop>
          <InputRoot :value="name" class="flex-1" @value-change="name = $event"
            ><InputControl placeholder="请输入新选项" /></InputRoot
          ><Button size="sm" variant="ghost" @click="addItem"
            ><PlusIcon class="size-4" />添加</Button
          >
        </div></SelectContent
      ></SelectRoot
    ></Demo
  >
</template>
