// apps/react-admin/src/pages/Select/virtual-demo.tsx
import {
  SelectContent,
  SelectList,
  SelectRoot,
  SelectTrigger,
} from '@fex/components-react/primitive/select'
import { virtualOptions } from './data'
import { SelectDemoSection } from './demo-section'

export function VirtualDemo() {
  return (
    <SelectDemoSection
      title="Virtual scrolling"
      description="Only the visible fixed-height options and overscan are mounted from 1,000 entries."
    >
      <SelectRoot showSearch options={virtualOptions} virtual={{ itemHeight: 32, overscan: 4 }}>
        <SelectTrigger placeholder="请输入关键词或选择选项" />
        <SelectContent className="[--select-content-max-height:256px]">
          <SelectList />
        </SelectContent>
      </SelectRoot>
    </SelectDemoSection>
  )
}

// apps/vue-admin/src/pages/Select/virtual-demo.vue
<script setup lang="ts">
import { SelectContent, SelectRoot, SelectTrigger } from '@fex/components-vue/primitive/select'
import { virtualOptions } from './data'
import Demo from './demo-section.vue'
</script>
<template>
  <Demo
    title="Virtual scrolling"
    description="Only the visible fixed-height options and overscan are mounted from 1,000 entries."
    ><SelectRoot show-search :options="virtualOptions" :virtual="{ itemHeight: 32, overscan: 4 }"
      ><SelectTrigger placeholder="请输入关键词或选择选项" /><SelectContent
        class="[--select-content-max-height:256px]" /></SelectRoot
  ></Demo>
</template>
