// packages/components/svelte/src/primitive/card/card-header.svelte
<script lang="ts">
  import { cardHeaderClassName } from '@fex/components-styles/card'
  import { cn } from '@fex/utils'
  import type { Snippet } from 'svelte'
  import type { HTMLAttributes } from 'svelte/elements'

  interface CardHeaderProps extends Omit<HTMLAttributes<HTMLDivElement>, 'class'> {
    class?: string
    children?: Snippet
  }

  let { class: className, children, ...rest }: CardHeaderProps = $props()

  const classList = $derived(cn(cardHeaderClassName(), className))
</script>

<div {...rest} data-slot="card-header" class={classList}>
  {@render children?.()}
</div>

// packages/components/vue/src/primitive/card/card-header.vue
﻿<script setup lang="ts">
import { cardHeaderClassName } from '@fex/components-styles/card'
import { cn } from '@fex/utils'

defineOptions({ inheritAttrs: false })
const props = defineProps<{ class?: string | undefined }>()
</script>

<template>
  <div v-bind="$attrs" data-slot="card-header" :class="cn(cardHeaderClassName, props.class)">
    <slot />
  </div>
</template>
