// apps/angular-admin/src/pages/tabs/variant-demo.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core'
import { TabsContent, TabsItem, TabsList, TabsRoot } from '@fex/components-angular/primitive/tabs'
import Card from '@fex/components-angular/ui/card'
@Component({
  selector: 'fex-variant-tabs-demo',
  standalone: true,
  imports: [Card, TabsRoot, TabsList, TabsItem, TabsContent],
  templateUrl: './variant-demo.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class VariantTabsDemoComponent {}

<fex-card
  title="Variants"
  description="The segmented default and line variant share one behavior contract."
  ><div class="grid gap-space-xl">
    <div fexTabsRoot defaultValue="one">
      <div fexTabsList>
        <div fexTabsItem value="one">One</div>
        <div fexTabsItem value="two">Two</div>
      </div>
      <div *fexTabsContent="'one'">Default segmented tabs.</div>
      <div *fexTabsContent="'two'">Second default panel.</div>
    </div>
    <div fexTabsRoot defaultValue="one" variant="line">
      <div fexTabsList>
        <div fexTabsItem value="one">One</div>
        <div fexTabsItem value="two">Two</div>
      </div>
      <div *fexTabsContent="'one'">Line variant content.</div>
      <div *fexTabsContent="'two'">Second line panel.</div>
    </div>
  </div></fex-card
>

// apps/vue-admin/src/pages/Tabs/variant-demo.vue
<script setup lang="ts">
import { TabsContent, TabsItem, TabsList, TabsRoot } from '@fex/components-vue/primitive/tabs'
import Card from '@fex/components-vue/ui/card'
</script>
<template>
  <Card
    title="Variants"
    description="The segmented default and line variant share one behavior contract."
    ><div class="grid gap-space-xl">
      <TabsRoot default-value="one"
        ><TabsList
          ><TabsItem value="one">One</TabsItem><TabsItem value="two">Two</TabsItem></TabsList
        ><TabsContent value="one">Default segmented tabs.</TabsContent
        ><TabsContent value="two">Second default panel.</TabsContent></TabsRoot
      ><TabsRoot default-value="one" variant="line"
        ><TabsList
          ><TabsItem value="one">One</TabsItem><TabsItem value="two">Two</TabsItem></TabsList
        ><TabsContent value="one">Line variant content.</TabsContent
        ><TabsContent value="two">Second line panel.</TabsContent></TabsRoot
      >
    </div></Card
  >
</template>
