// apps/angular-admin/src/pages/auto-complete/basic-demo.component.ts
import { ChangeDetectionStrategy, Component, signal } from '@angular/core'
import {
  AutoCompleteContent,
  AutoCompleteList,
  AutoCompleteRoot,
  AutoCompleteTrigger,
} from '@fex-design/angular/primitive/auto-complete'
import Card from '@fex-design/angular/ui/card'
import { fieldNames, users } from './data'

@Component({
  selector: 'fex-auto-complete-basic-demo',
  standalone: true,
  imports: [Card, AutoCompleteRoot, AutoCompleteTrigger, AutoCompleteContent, AutoCompleteList],
  changeDetection: ChangeDetectionStrategy.OnPush,
  templateUrl: './basic-demo.component.html',
})
export class BasicDemo {
  protected readonly users = users
  protected readonly fieldNames = fieldNames
  protected readonly selected = signal('No suggestion accepted')
  protected accept(event: { meta: { selectedItem: Record<string, unknown> } }) {
    this.selected.set(`${event.meta.selectedItem['name']} · ${event.meta.selectedItem['email']}`)
  }
}

<fex-card title="Free input and local suggestions" description="Type any text, or accept a matching name with pointer or keyboard.">
  <fex-auto-complete [items]="users" [fieldNames]="fieldNames" (select)="accept($event)">
    <fex-auto-complete-trigger placeholder="Try A or Bella" [clearable]="true" />
    <fex-auto-complete-content><fex-auto-complete-list /></fex-auto-complete-content>
  </fex-auto-complete>
  <p class="mt-space-sm text-xs text-muted-foreground">{{ selected() }}</p>
</fex-card>

// apps/svelte-app/src/routes/auto-complete/basic-demo.svelte
<script lang="ts">
  import AutoCompleteRoot from '@fex-design/svelte/primitive/auto-complete'
  import AutoCompleteContent from '@fex-design/svelte/primitive/auto-complete-content'
  import AutoCompleteTrigger from '@fex-design/svelte/primitive/auto-complete-trigger'
  import Card from '@fex-design/svelte/ui/card'
  import { fieldNames, users } from './data'
  let selected = $state('No suggestion accepted')
</script>
<Card title="Free input and local suggestions" description="Type any text, or accept a matching name with pointer or keyboard.">
  <AutoCompleteRoot items={users} {fieldNames} onSelect={(_, meta) => selected = `${meta.selectedItem.name} · ${meta.selectedItem.email}`}>
    <AutoCompleteTrigger placeholder="Try A or Bella" clearable />
    <AutoCompleteContent />
  </AutoCompleteRoot>
  <p class="mt-space-sm text-xs text-muted-foreground">{selected}</p>
</Card>
