// packages/components/solid/src/primitive/empty/empty.tsx
import {
  emptyClassName,
  emptyContentClassName,
  emptyDescriptionClassName,
  emptyHeaderClassName,
  emptyMediaClassName,
  emptyTitleClassName,
  type EmptyMediaStyleProps,
} from '@fex/components-styles/empty'
import { cn } from '@fex/utils'
import type { JSX, ParentProps } from 'solid-js'
import { splitProps } from 'solid-js'

type DivProps = ParentProps<JSX.HTMLAttributes<HTMLDivElement>>

function createPart(slot: string, className: string) {
  return function Part(props: DivProps) {
    const [local, rest] = splitProps(props, ['class', 'children'])
    return (
      <div {...rest} data-slot={slot} class={cn(className, local.class)}>
        {local.children}
      </div>
    )
  }
}

export const Empty = createPart('empty', emptyClassName)
export const EmptyHeader = createPart('empty-header', emptyHeaderClassName)
export const EmptyTitle = createPart('empty-title', emptyTitleClassName)
export const EmptyContent = createPart('empty-content', emptyContentClassName)

export function EmptyDescription(props: ParentProps<JSX.HTMLAttributes<HTMLParagraphElement>>) {
  const [local, rest] = splitProps(props, ['class', 'children'])
  return (
    <p {...rest} data-slot="empty-description" class={cn(emptyDescriptionClassName, local.class)}>
      {local.children}
    </p>
  )
}

export function EmptyMedia(props: DivProps & EmptyMediaStyleProps) {
  const [local, rest] = splitProps(props, ['class', 'children', 'variant'])
  return (
    <div
      {...rest}
      data-slot="empty-icon"
      data-variant={local.variant ?? 'default'}
      class={cn(emptyMediaClassName({ variant: local.variant }), local.class)}
    >
      {local.children}
    </div>
  )
}

// packages/components/react/src/primitive/empty/empty.tsx
import {
  emptyClassName,
  emptyContentClassName,
  emptyDescriptionClassName,
  emptyHeaderClassName,
  emptyMediaClassName,
  emptyTitleClassName,
  type EmptyMediaStyleProps,
} from '@fex/components-styles/empty'
import { cn } from '@fex/utils'
import type { ComponentProps } from 'react'

export function Empty({ className, ...props }: ComponentProps<'div'>) {
  return <div data-slot="empty" className={cn(emptyClassName, className)} {...props} />
}

export function EmptyHeader({ className, ...props }: ComponentProps<'div'>) {
  return <div data-slot="empty-header" className={cn(emptyHeaderClassName, className)} {...props} />
}

export function EmptyMedia({
  className,
  variant = 'default',
  ...props
}: ComponentProps<'div'> & EmptyMediaStyleProps) {
  return (
    <div
      data-slot="empty-icon"
      data-variant={variant}
      className={cn(emptyMediaClassName({ variant }), className)}
      {...props}
    />
  )
}

export function EmptyTitle({ className, ...props }: ComponentProps<'div'>) {
  return <div data-slot="empty-title" className={cn(emptyTitleClassName, className)} {...props} />
}

export function EmptyDescription({ className, ...props }: ComponentProps<'p'>) {
  return (
    <p
      data-slot="empty-description"
      className={cn(emptyDescriptionClassName, className)}
      {...props}
    />
  )
}

export function EmptyContent({ className, ...props }: ComponentProps<'div'>) {
  return (
    <div data-slot="empty-content" className={cn(emptyContentClassName, className)} {...props} />
  )
}
