// packages/@fex-design/vue/src/primitive/alert/alert-description.vue
<script setup lang="ts">
import { alertDescriptionClassName } from '@fex-design/styles/alert'
import { cn } from '@fex/utils'

defineOptions({ inheritAttrs: false })
const props = defineProps<{ class?: string | undefined }>()
</script>

<template>
  <div
    v-bind="$attrs"
    data-slot="alert-description"
    :class="cn(alertDescriptionClassName, props.class)"
  >
    <slot />
  </div>
</template>

// packages/@fex-design/svelte/src/primitive/alert/alert-description.svelte
<script lang="ts">
  import { alertDescriptionClassName } from '@fex-design/styles/alert'
  import { cn } from '@fex/utils'
  import type { Snippet } from 'svelte'
  import type { HTMLAttributes } from 'svelte/elements'
  interface Props extends Omit<HTMLAttributes<HTMLDivElement>, 'class'> { class?: string; children?: Snippet }
  let { class: className, children, ...rest }: Props = $props()
  const classList = $derived(cn(alertDescriptionClassName, className))
</script>
<div {...rest} data-slot="alert-description" class={classList}>{@render children?.()}</div>
