// packages/@fex-design/angular/src/primitive/aspect-ratio/aspect-ratio.ts
import { aspectRatioClassName } from '@fex-design/styles/aspect-ratio'
import { ChangeDetectionStrategy, Component, input } from '@angular/core'
import { createHostClassName } from '../../signals/host-class'
@Component({
  selector: 'fex-aspect-ratio',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'hostClassName()',
    'data-slot': 'aspect-ratio',
    '[style.aspect-ratio]': 'ratio()',
  },
  template: '<ng-content />',
})
export class AspectRatio {
  readonly ratio = input.required<number>()
  protected readonly hostClassName = createHostClassName(() => aspectRatioClassName)
}

// packages/@fex-design/react/src/primitive/aspect-ratio/aspect-ratio.tsx
import { aspectRatioClassName } from '@fex-design/styles/aspect-ratio'
import { cn } from '@fex/utils'
import type { ComponentProps, CSSProperties } from 'react'

export function AspectRatio({
  ratio,
  className,
  style,
  ...props
}: ComponentProps<'div'> & { ratio: number }) {
  return (
    <div
      data-slot="aspect-ratio"
      className={cn(aspectRatioClassName, className)}
      style={{ aspectRatio: ratio, ...style } as CSSProperties}
      {...props}
    />
  )
}
