// apps/svelte-admin/src/routes/qrcode/render-type-demo.svelte
<script lang="ts">
  import { QrCodeBackground, QrCodeCanvas, QrCodeModules, QrCodeRoot, QrCodeSvg } from '@fex-design/svelte/primitive/qrcode'
  import Card from '@fex-design/svelte/ui/card'
</script>

<Card title="自定义渲染类型" description="同一个 Root 模型可以选择 SVG 或 Canvas 渲染面。">
  <div class="flex flex-wrap gap-space-lg">
    <QrCodeRoot value="https://fex.design/qrcode/svg" size={160}>
      <QrCodeSvg aria-label="SVG QR code"><QrCodeBackground /><QrCodeModules /></QrCodeSvg>
    </QrCodeRoot>
    <QrCodeRoot value="https://fex.design/qrcode/canvas" size={160}>
      <QrCodeCanvas aria-label="Canvas QR code" />
    </QrCodeRoot>
  </div>
</Card>

// apps/angular-admin/src/pages/qrcode/render-type-demo.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core'
import {
  QrCodeBackground,
  QrCodeCanvas,
  QrCodeModules,
  QrCodeRoot,
  QrCodeSvg,
} from '@fex-design/angular/primitive/qrcode'
import { Card } from '@fex-design/angular/ui/card'

@Component({
  selector: 'fex-qrcode-render-type-demo',
  standalone: true,
  imports: [Card, QrCodeRoot, QrCodeSvg, QrCodeBackground, QrCodeModules, QrCodeCanvas],
  templateUrl: './render-type-demo.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class RenderTypeDemo {}

<fex-card title="自定义渲染类型" description="同一个 Root 模型可以选择 SVG 或 Canvas 渲染面。">
  <div class="flex flex-wrap gap-space-lg">
    <fex-qrcode-root value="https://fex.design/qrcode/svg" [size]="160">
      <svg fexQrCodeSvg aria-label="SVG QR code">
        <rect fexQrCodeBackground />
        <path fexQrCodeModules />
      </svg>
    </fex-qrcode-root>
    <fex-qrcode-root value="https://fex.design/qrcode/canvas" [size]="160">
      <canvas fexQrCodeCanvas aria-label="Canvas QR code"></canvas>
    </fex-qrcode-root>
  </div>
</fex-card>
