// packages/components/react/src/ui/listbox/listbox.tsx
import {
  listboxGroupClassName,
  listboxGroupLabelClassName,
  listboxItemClassName,
  listboxItemContentClassName,
  listboxItemDescriptionClassName,
  listboxItemIndicatorClassName,
  listboxItemTitleClassName,
  listboxRootClassName,
  type ListboxItemStyleProps,
  type ListboxRootStyleProps,
} from '@fex/components-styles/listbox'
import { cn } from '@fex/utils'
import type { ComponentProps, ReactNode } from 'react'
import { CheckIcon } from '../../icon/check'
import {
  ListboxGroup as PrimitiveListboxGroup,
  ListboxGroupLabel as PrimitiveListboxGroupLabel,
  ListboxItem as PrimitiveListboxItem,
  ListboxItemIndicator as PrimitiveListboxItemIndicator,
  ListboxRoot as PrimitiveListboxRoot,
  type ListboxRootProps as PrimitiveListboxRootProps,
} from '../../primitive/listbox/listbox'

export type ListboxRootProps<TItem = unknown> = Omit<PrimitiveListboxRootProps<TItem>, 'className'> &
  ListboxRootStyleProps & {
    className?: string
  }

export function ListboxRoot<TItem = unknown>({ className, variant, ...props }: ListboxRootProps<TItem>) {
  return <PrimitiveListboxRoot {...props} className={cn(listboxRootClassName({ variant }), className)} />
}

export function ListboxGroup({ className, ...props }: ComponentProps<typeof PrimitiveListboxGroup>) {
  return <PrimitiveListboxGroup {...props} className={cn(listboxGroupClassName, className)} />
}

export function ListboxGroupLabel({ className, ...props }: ComponentProps<typeof PrimitiveListboxGroupLabel>) {
  return <PrimitiveListboxGroupLabel {...props} className={cn(listboxGroupLabelClassName, className)} />
}

export interface ListboxItemProps
  extends Omit<ComponentProps<typeof PrimitiveListboxItem>, 'className' | 'children' | 'title'>,
    ListboxItemStyleProps {
  title?: ReactNode
  description?: ReactNode
  className?: string
  children?: ReactNode
}

export function ListboxItem({ title, description, size, className, children, ...props }: ListboxItemProps) {
  return (
    <PrimitiveListboxItem {...props} className={cn(listboxItemClassName({ size }), className)}>
      {children ?? (
        <>
          <span className={listboxItemContentClassName}>
            <span className={listboxItemTitleClassName}>{title}</span>
            {description ? <span className={listboxItemDescriptionClassName}>{description}</span> : null}
          </span>
          <PrimitiveListboxItemIndicator className={listboxItemIndicatorClassName}>
            <CheckIcon />
          </PrimitiveListboxItemIndicator>
        </>
      )}
    </PrimitiveListboxItem>
  )
}

export function ListboxItemIndicator(props: ComponentProps<typeof PrimitiveListboxItemIndicator>) {
  return (
    <PrimitiveListboxItemIndicator {...props} className={cn(listboxItemIndicatorClassName, props.className)}>
      {props.children ?? <CheckIcon />}
    </PrimitiveListboxItemIndicator>
  )
}

export {
  ListboxRoot as Listbox,
  PrimitiveListboxGroup,
  PrimitiveListboxGroupLabel,
  PrimitiveListboxItem,
  PrimitiveListboxItemIndicator,
}

// packages/components/angular/src/ui/listbox/listbox.ts
import {
  listboxGroupClassName,
  listboxGroupLabelClassName,
  listboxItemClassName,
  listboxItemIndicatorClassName,
  listboxRootClassName,
} from '@fex/components-styles/listbox'
import { cn } from '@fex/utils'
import { ChangeDetectionStrategy, Component } from '@angular/core'
import { CheckIcon } from '../../icon/check'
import {
  ListboxGroup as PrimitiveListboxGroup,
  ListboxGroupLabel as PrimitiveListboxGroupLabel,
  ListboxItem as PrimitiveListboxItem,
  ListboxItemIndicator as PrimitiveListboxItemIndicator,
  ListboxRoot as PrimitiveListboxRoot,
} from '../../primitive/listbox/listbox'
import { createHostClassName } from '../../signals/host-class'

@Component({
  selector: 'fex-ui-listbox',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    role: 'listbox',
    'data-slot': 'listbox',
    '[class]': 'hostClassName()',
    '[attr.aria-multiselectable]': 'snapshot().multiple || null',
    '[attr.aria-orientation]': 'orientation()',
    '[attr.data-orientation]': 'orientation()',
  },
  providers: [{ provide: PrimitiveListboxRoot, useExisting: ListboxRoot }],
  template: '<ng-content />',
})
export class ListboxRoot extends PrimitiveListboxRoot {
  protected readonly hostClassName = createHostClassName(() => cn(listboxRootClassName({})))
}

@Component({
  selector: 'fex-ui-listbox-group',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    role: 'group',
    'data-slot': 'listbox-group',
    '[class]': 'hostClassName()',
  },
  template: '<ng-content />',
})
export class ListboxGroup extends PrimitiveListboxGroup {
  protected readonly hostClassName = createHostClassName(() => cn(listboxGroupClassName))
}

@Component({
  selector: 'fex-ui-listbox-group-label',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    'data-slot': 'listbox-group-label',
    '[class]': 'hostClassName()',
  },
  template: '<ng-content />',
})
export class ListboxGroupLabel extends PrimitiveListboxGroupLabel {
  protected readonly hostClassName = createHostClassName(() => cn(listboxGroupLabelClassName))
}

@Component({
  selector: 'fex-ui-listbox-item',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    role: 'option',
    tabindex: '0',
    'data-slot': 'listbox-item',
    '[class]': 'hostClassName()',
    '[attr.aria-selected]': 'selected()',
    '[attr.aria-disabled]': 'disabledState() || null',
    '[attr.data-selected]': "selected() ? 'true' : 'false'",
    '[attr.data-disabled]': "disabledState() ? 'true' : null",
  },
  template: '<ng-content />',
})
export class ListboxItem extends PrimitiveListboxItem {
  protected readonly hostClassName = createHostClassName(() => cn(listboxItemClassName({})))
}

@Component({
  selector: 'fex-ui-listbox-item-indicator',
  standalone: true,
  imports: [CheckIcon],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    'aria-hidden': 'true',
    'data-slot': 'listbox-item-indicator',
    '[class]': 'hostClassName()',
  },
  template: '<ng-content /><fex-check-icon />',
})
export class ListboxItemIndicator extends PrimitiveListboxItemIndicator {
  protected readonly hostClassName = createHostClassName(() => cn(listboxItemIndicatorClassName))
}

export { ListboxRoot as Listbox }
