// apps/svelte-admin/src/routes/context-menu/basic-demo.svelte
<script lang="ts">
  import type { ContextMenuOpenChangeInfo } from '@fex-design/core/overlay/context-menu/types'
  import ContextMenu from '@fex-design/svelte/primitive/context-menu'
  import ContextMenuContent from '@fex-design/svelte/primitive/context-menu-content'
  import ContextMenuPortal from '@fex-design/svelte/primitive/context-menu-portal'
  import ContextMenuTrigger from '@fex-design/svelte/primitive/context-menu-trigger'
  import MenuSurface from './menu-surface.svelte'

  let last = $state('Right click the panel')

  function handleOpenChange(open: boolean, info: ContextMenuOpenChangeInfo<string>) {
    if (!open) return
    last = 'Opened ' + info.payload + ' at ' + Math.round(info.clientX ?? 0) + ', ' + Math.round(info.clientY ?? 0)
  }
</script>

<ContextMenu onOpenChange={handleOpenChange}>
  <ContextMenuTrigger payload="basic-panel">
    {#snippet children(trigger)}
      <div
        use:trigger.action
        {...trigger.props}
        tabindex="0"
        class="rounded-md border border-dashed border-border bg-background p-space-xl text-sm text-muted-foreground outline-none focus:ring-2 focus:ring-ring"
      >
        {last}
      </div>
    {/snippet}
  </ContextMenuTrigger>
  <ContextMenuPortal>
    <ContextMenuContent>
      <MenuSurface label="Panel actions" />
    </ContextMenuContent>
  </ContextMenuPortal>
</ContextMenu>

// apps/solid-admin/src/pages/ContextMenu/basic-demo.tsx
import { createSignal } from 'solid-js'
import {
  ContextMenu,
  ContextMenuContent,
  ContextMenuPortal,
  ContextMenuTrigger,
} from '@fex-design/solid/primitive/context-menu'
import { ContextMenuSurface } from './menu-surface'

export function BasicContextMenuDemo() {
  const [last, setLast] = createSignal('Right click the panel')
  return (
    <ContextMenu
      onOpenChange={(open, info) => {
        if (open) setLast('Opened ' + info.payload + ' at ' + Math.round(info.clientX ?? 0) + ', ' + Math.round(info.clientY ?? 0))
      }}
    >
      {() => <>
      <ContextMenuTrigger payload="basic-panel">
        {(trigger) => (
          <div
            {...trigger.props}
            ref={trigger.ref}
            tabIndex={0}
            class="rounded-md border border-dashed border-border bg-background p-space-xl text-sm text-muted-foreground outline-none focus:ring-2 focus:ring-ring"
          >
            {last()}
          </div>
        )}
      </ContextMenuTrigger>
      <ContextMenuPortal>
        <ContextMenuContent>
          <ContextMenuSurface label="Panel actions" />
        </ContextMenuContent>
      </ContextMenuPortal>
      </>}
    </ContextMenu>
  )
}
