// packages/@fex-design/svelte/src/primitive/upload/upload-item.svelte
<script lang="ts" generics="TResponse">
  import type { UploadId } from '@fex-design/core/upload/types'
  import { uploadItemClassName } from '@fex-design/styles/upload'
  import { cn } from '@fex/utils'
  import type { Snippet } from 'svelte'
  import type { HTMLAttributes } from 'svelte/elements'
  import { useUploadContext, setUploadItemId } from './context'
  import { createUploadItem } from './create-upload'
  type InternalState = ReturnType<typeof createUploadItem<TResponse>>
  type State = Omit<InternalState, 'item'> & { item: import('@fex-design/core/upload/types').UploadItem<TResponse> | undefined }
  let { id, children, class: className, ...rest }: Omit<HTMLAttributes<HTMLDivElement>, 'children' | 'id'> & { id: UploadId, children?: Snippet<[State]> } = $props()
  const { upload } = useUploadContext<TResponse>()
  const state = createUploadItem(upload, () => id)
  const { item } = state
  const slotState: State = $derived({ ...state, item: $item })
  // svelte-ignore state_referenced_locally -- keyed upload items keep a stable id while mounted.
  setUploadItemId(id)
</script>
{#if $item}<div {...rest} role="listitem" class={cn(uploadItemClassName(), className)} data-status={$item.status}>{@render children?.(slotState)}</div>{/if}

// packages/@fex-design/vue/src/primitive/upload/upload-item.vue
<script setup lang="ts">
import type { UploadId } from '@fex-design/core/upload/types'
import { uploadItemClassName } from '@fex-design/styles/upload'
import { cn } from '@fex/utils'
import { provide, useAttrs } from 'vue'
import { uploadItemIdKey, useUploadContext } from './context'
import { useUploadItem } from './use-upload'
defineOptions({ inheritAttrs: false })
const props = defineProps<{ id: UploadId }>()
const attrs = useAttrs()
const { upload } = useUploadContext()
const state = useUploadItem(upload, () => props.id)
provide(uploadItemIdKey, props.id)
</script>
<template>
  <div
    v-if="state.item.value"
    v-bind="{ ...attrs, class: undefined }"
    role="listitem"
    :data-status="state.item.value.status"
    :class="cn(uploadItemClassName(), attrs.class as string | undefined)"
  >
    <slot
      :item="state.item.value"
      :start="state.start"
      :retry="state.retry"
      :cancel="state.cancel"
      :pause="state.pause"
      :continue="state.continue"
      :remove="state.remove"
    />
  </div>
</template>
