// apps/vue-admin/src/pages/Transfer/custom-demo.vue
<script setup lang="ts">
import { ChevronLeftIcon, ChevronRightIcon } from '@fex/components-vue/icon/chevron'
import { Transfer } from '@fex/components-vue/primitive/transfer'
import { Badge } from '@fex/components-vue/ui/badge'
import Button from '@fex/components-vue/ui/button'
import Card from '@fex/components-vue/ui/card'
import { fieldNames, members } from './data'
</script>
<template>
  <Card
    title="Custom panel regions"
    description="Source and target headers, bodies and optional footers are configured independently while the panel structure remains built in."
    ><Transfer
      :items="members"
      :field-names="fieldNames"
      :default-target-keys="['ada', 'susan']"
      :panels="{ source: { footer: true }, target: { footer: true } }"
      ><template #actions="{ controller, snapshot }"
        ><div class="flex flex-col items-center gap-2">
          <Button
            variant="outline"
            size="sm"
            :disabled="!snapshot.sourceCheckedKeys.length"
            @click="controller.moveToTarget()"
            >Assign <ChevronRightIcon /></Button
          ><Button
            variant="outline"
            size="sm"
            :disabled="!snapshot.targetCheckedKeys.length"
            @click="controller.moveToSource()"
            ><ChevronLeftIcon /> Remove</Button
          >
        </div></template
      ><template #sourceHeader="{ api }"
        ><span class="font-medium">Candidate pool</span
        ><Badge>{{ api.items.length }}</Badge></template
      ><template #targetHeader="{ api }"
        ><span class="font-medium text-primary">Delivery team</span
        ><span class="ml-auto text-muted-foreground">{{ api.items.length }} members</span></template
      ><template #item="{ item }"
        ><span
          >{{ item.name }} <span class="text-muted-foreground">· {{ item.department }}</span></span
        ></template
      ><template #sourceFooter
        ><span class="text-muted-foreground"
          >Disabled members stay in their current panel.</span
        ></template
      ><template #targetFooter
        ><span class="text-muted-foreground"
          >Changes are applied when the form is submitted.</span
        ></template
      ></Transfer
    ></Card
  >
</template>

// apps/angular-admin/src/pages/transfer/custom-demo.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core'
import {
  Transfer,
  TransferActionsTemplate,
  TransferItemTemplate,
  TransferPanelTemplate,
} from '@fex/components-angular/primitive/transfer'
import { ChevronLeftIcon, ChevronRightIcon } from '@fex/components-angular/icon/chevron'
import { Badge } from '@fex/components-angular/ui/badge'
import { Button } from '@fex/components-angular/ui/button'
import Card from '@fex/components-angular/ui/card'
import { transferFieldNames, transferMembers } from './data'

@Component({
  selector: 'fex-transfer-custom-demo',
  standalone: true,
  imports: [
    Card,
    Transfer,
    TransferActionsTemplate,
    TransferItemTemplate,
    TransferPanelTemplate,
    Button,
    Badge,
    ChevronLeftIcon,
    ChevronRightIcon,
  ],
  templateUrl: './custom-demo.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class TransferCustomDemoComponent {
  protected readonly members = transferMembers
  protected readonly fieldNames = transferFieldNames
}

<fex-card
  title="Custom panel regions"
  description="Source and target headers, bodies and optional footers are configured independently while the panel structure remains built in."
>
  <fex-transfer [items]="members" [fieldNames]="fieldNames" [defaultTargetKeys]="['ada', 'susan']">
    <ng-template fexTransferActions let-api>
      <div class="flex flex-col items-center gap-2">
        <button fexButton variant="outline" size="sm" [disabled]="!api.canMoveToTarget" (click)="api.controller.moveToTarget()">
          Assign <fex-chevron-right-icon />
        </button>
        <button fexButton variant="outline" size="sm" [disabled]="!api.canMoveToSource" (click)="api.controller.moveToSource()">
          <fex-chevron-left-icon /> Remove
        </button>
      </div>
    </ng-template>
    <ng-template fexTransferItem let-item>
      <span>{{ item.name }} <span class="text-muted-foreground">· {{ item.department }}</span></span>
    </ng-template>
    <ng-template fexTransferPanel="source" region="header" let-api>
      <span class="font-medium">Candidate pool</span><fex-badge>{{ api.items.length }}</fex-badge>
    </ng-template>
    <ng-template fexTransferPanel="target" region="header" let-api>
      <span class="font-medium text-primary">Delivery team</span>
      <span class="ml-auto text-muted-foreground">{{ api.items.length }} members</span>
    </ng-template>
    <ng-template fexTransferPanel="source" region="footer">
      <span class="text-muted-foreground">Disabled members stay in their current panel.</span>
    </ng-template>
    <ng-template fexTransferPanel="target" region="footer">
      <span class="text-muted-foreground">Changes are applied when the form is submitted.</span>
    </ng-template>
  </fex-transfer>
</fex-card>
