// packages/@fex-design/vue/src/primitive/tree/tree-viewport.vue
<script setup lang="ts" generic="TNode extends TreeNodeData">
import type { TreeNodeData } from '@fex-design/core/tree/types'
import { treeViewportClassName } from '@fex-design/styles/tree'
import { cn } from '@fex/utils'
import { computed, useAttrs } from 'vue'
import { useTreeContext } from './context'
import { useTreeVisibleItems } from './use-tree-visible-items'

defineOptions({ inheritAttrs: false })
const attrs = useAttrs()
const { tree } = useTreeContext<TNode>('TreeViewport')
const items = useTreeVisibleItems(tree)
const viewportClass = computed(() => cn(treeViewportClassName, attrs.class as string | undefined))
const viewportAttrs = computed(() => {
  const { class: _class, ...rest } = attrs
  return rest
})
</script>

<template>
  <div v-bind="viewportAttrs" data-slot="tree-viewport" :class="viewportClass">
    <slot v-for="item in items" :key="item.key" :item="item" :tree="tree" />
  </div>
</template>

// packages/@fex-design/svelte/src/primitive/tree/tree-viewport.svelte
<script lang="ts" generics="TNode extends TreeNodeData">
  import type { TreeController, TreeNodeData, TreeVisibleItem } from '@fex-design/core/tree/types'
  import { treeViewportClassName } from '@fex-design/styles/tree'
  import { cn } from '@fex/utils'
  import { getContext, type Snippet, untrack } from 'svelte'
  import type { HTMLAttributes } from 'svelte/elements'
  import { readableCoreStore } from '../../stores/core-store'
  import { treeContextKey, type TreeContext } from './tree-context'

  interface Props extends Omit<HTMLAttributes<HTMLDivElement>, 'children'> {
    controller?: TreeController<TNode>
    children?: Snippet<[TreeVisibleItem<TNode>]>
  }

  let { controller, children, class: className, ...rest }: Props = $props()
  const context = getContext<TreeContext<TNode>>(treeContextKey)
  const tree = untrack(() => controller ?? context.tree)
  const items = readableCoreStore({
    getSnapshot: tree.getVisibleItems,
    subscribe: tree.subscribeVisible,
  })
</script>

<div {...rest} data-slot="tree-viewport" class={cn(treeViewportClassName, className)}>
  {#each $items as item (item.key)}
    {@render children?.(item)}
  {/each}
</div>
