// apps/react-admin/src/pages/DataGrid/index.tsx
import { Link } from 'react-router'
import { BasicDataGridDemo } from './basic-demo'
import { CellEditingDataGridDemo } from './cell-editing-demo'
import { ColumnPinningDataGridDemo } from './column-pinning-demo'
import { DndDataGridDemo } from './dnd-demo'
import { ExpansionDataGridDemo } from './expansion-demo'
import { FilteringDataGridDemo } from './filtering-demo'
import { GroupingDataGridDemo } from './grouping-demo'
import { HeaderGroupingDataGridDemo } from './header-grouping-demo'
import { OrderingDataGridDemo } from './ordering-demo'
import { PaginationDataGridDemo } from './pagination-demo'
import { PresentationDataGridDemo } from './presentation-demo'
import { RowPinningDataGridDemo } from './row-pinning-demo'
import { RowEditingDataGridDemo } from './row-editing-demo'
import { SelectionDataGridDemo } from './selection-demo'
import { SizingDataGridDemo } from './sizing-demo'
import { SortingDataGridDemo } from './sorting-demo'
import { VisibilityDataGridDemo } from './visibility-demo'
import { VirtualDataGridDemo } from './virtual-demo'

export function DataGridPage() {
  return (
    <main className="min-h-screen bg-secondary-background px-page-padding py-space-xl">
      <div className="mx-auto w-full max-w-[1600px] space-y-space-xl">
        <header className="space-y-space-sm">
          <Link className="text-sm text-muted-foreground hover:text-foreground" to="/">
            Back home
          </Link>
          <div>
            <h1 className="text-2xl font-semibold text-foreground">Data Grid primitive</h1>
            <p className="max-w-4xl text-sm leading-6 text-muted-foreground">
              React 19 adapter for TanStack Table v9 beta. Every capability is registered
              independently; the primitive renders the resulting table instance and leaves requests,
              DnD policy and business UI to callers.
            </p>
          </div>
        </header>
        <div className="space-y-space-xl">
          <BasicDataGridDemo />
          <HeaderGroupingDataGridDemo />
          <SortingDataGridDemo />
          <FilteringDataGridDemo />
          <PaginationDataGridDemo />
          <SelectionDataGridDemo />
          <ExpansionDataGridDemo />
          <VisibilityDataGridDemo />
          <OrderingDataGridDemo />
          <DndDataGridDemo />
          <ColumnPinningDataGridDemo />
          <RowPinningDataGridDemo />
          <SizingDataGridDemo />
          <GroupingDataGridDemo />
          <VirtualDataGridDemo />
          <CellEditingDataGridDemo />
          <RowEditingDataGridDemo />
          <PresentationDataGridDemo />
        </div>
      </div>
    </main>
  )
}

// apps/svelte-admin/src/routes/data-grid/+page.svelte
<script lang="ts">
  import BasicDemo from './basic-demo.svelte'
  import HeaderGroupingDemo from './header-grouping-demo.svelte'
  import SortingDemo from './sorting-demo.svelte'
  import FilteringDemo from './filtering-demo.svelte'
  import PaginationDemo from './pagination-demo.svelte'
  import SelectionDemo from './selection-demo.svelte'
  import ExpansionDemo from './expansion-demo.svelte'
  import VisibilityDemo from './visibility-demo.svelte'
  import OrderingDemo from './ordering-demo.svelte'
  import DndDemo from './dnd-demo.svelte'
  import ColumnPinningDemo from './column-pinning-demo.svelte'
  import RowPinningDemo from './row-pinning-demo.svelte'
  import SizingDemo from './sizing-demo.svelte'
  import GroupingDemo from './grouping-demo.svelte'
  import VirtualDemo from './virtual-demo.svelte'
  import CellEditingDemo from './cell-editing-demo.svelte'
  import RowEditingDemo from './row-editing-demo.svelte'
  import PresentationDemo from './presentation-demo.svelte'
</script>

<svelte:head><title>DataGrid · Svelte Admin</title></svelte:head>
<main class="min-h-screen bg-secondary-background px-page-padding py-space-xl">
  <div class="mx-auto w-full max-w-[1600px] space-y-space-xl">
    <header class="space-y-space-sm"><a class="text-sm text-muted-foreground hover:text-foreground" href="/">Back home</a><h1 class="text-2xl font-semibold text-foreground">Data Grid primitive</h1><p class="max-w-4xl text-sm leading-6 text-muted-foreground">Svelte adapter for TanStack Table v9 beta. Every capability is registered independently; the primitive renders the resulting table instance and leaves requests, DnD policy and business UI to callers.</p></header>
    <div class="space-y-space-xl"><BasicDemo /><HeaderGroupingDemo /><SortingDemo /><FilteringDemo /><PaginationDemo /><SelectionDemo /><ExpansionDemo /><VisibilityDemo /><OrderingDemo /><DndDemo /><ColumnPinningDemo /><RowPinningDemo /><SizingDemo /><GroupingDemo /><VirtualDemo /><CellEditingDemo /><RowEditingDemo /><PresentationDemo /></div>
  </div>
</main>
