// packages/@fex-design/svelte/src/primitive/breadcrumb/breadcrumb.svelte
<script lang="ts">
  import { breadcrumbClassName, breadcrumbEllipsisClassName, breadcrumbItemClassName, breadcrumbLinkClassName, breadcrumbListClassName, breadcrumbPageClassName, breadcrumbSeparatorClassName } from '@fex-design/styles/breadcrumb'
  import { cn } from '@fex/utils'
  import type { Snippet } from 'svelte'
  interface Props { part?: 'root' | 'list' | 'item' | 'link' | 'page' | 'separator' | 'ellipsis'; class?: string; href?: string; children?: Snippet }
  let { part = 'root', class: className, href, children }: Props = $props()
  const classes = { root: breadcrumbClassName({}), list: breadcrumbListClassName, item: breadcrumbItemClassName, link: breadcrumbLinkClassName, page: breadcrumbPageClassName, separator: breadcrumbSeparatorClassName, ellipsis: breadcrumbEllipsisClassName }
</script>
{#if part === 'root'}<nav aria-label="Breadcrumb" class={cn(classes.root, className)} data-slot="breadcrumb">{@render children?.()}</nav>
{:else if part === 'list'}<ol class={cn(classes.list, className)} data-slot="breadcrumb-list">{@render children?.()}</ol>
{:else if part === 'item'}<li class={cn(classes.item, className)} data-slot="breadcrumb-item">{@render children?.()}</li>
{:else if part === 'link'}<a {href} class={cn(classes.link, className)} data-slot="breadcrumb-link">{@render children?.()}</a>
{:else if part === 'page'}<span aria-current="page" class={cn(classes.page, className)} data-slot="breadcrumb-page">{@render children?.()}</span>
{:else if part === 'separator'}<li aria-hidden="true" class={cn(classes.separator, className)} data-slot="breadcrumb-separator">{#if children}{@render children()}{:else}/{/if}</li>
{:else}<span aria-hidden="true" class={cn(classes.ellipsis, className)} data-slot="breadcrumb-ellipsis">{#if children}{@render children()}{:else}...{/if}</span>{/if}

// packages/@fex-design/react/src/primitive/breadcrumb/breadcrumb.tsx
import {
  breadcrumbClassName,
  breadcrumbEllipsisClassName,
  breadcrumbItemClassName,
  breadcrumbLinkClassName,
  breadcrumbListClassName,
  breadcrumbPageClassName,
  breadcrumbSeparatorClassName,
} from '@fex-design/styles/breadcrumb'
import { cn } from '@fex/utils'
import type { AnchorHTMLAttributes, HTMLAttributes, ReactNode, Ref } from 'react'

export function Breadcrumb({ className, children, ...props }: HTMLAttributes<HTMLElement>) {
  return (
    <nav
      {...props}
      aria-label={props['aria-label'] ?? 'Breadcrumb'}
      className={cn(breadcrumbClassName({}), className)}
      data-slot="breadcrumb"
    >
      {children}
    </nav>
  )
}
export function BreadcrumbList({
  className,
  children,
  ...props
}: HTMLAttributes<HTMLOListElement>) {
  return (
    <ol {...props} className={cn(breadcrumbListClassName, className)} data-slot="breadcrumb-list">
      {children}
    </ol>
  )
}
export function BreadcrumbItem({ className, children, ...props }: HTMLAttributes<HTMLLIElement>) {
  return (
    <li {...props} className={cn(breadcrumbItemClassName, className)} data-slot="breadcrumb-item">
      {children}
    </li>
  )
}

export type BreadcrumbLinkRenderProps = Omit<
  AnchorHTMLAttributes<HTMLAnchorElement>,
  'children'
> & { 'data-slot': string; ref?: Ref<HTMLAnchorElement> }
export interface BreadcrumbLinkProps extends Omit<
  AnchorHTMLAttributes<HTMLAnchorElement>,
  'children'
> {
  children?: ReactNode | ((props: BreadcrumbLinkRenderProps) => ReactNode)
}
export function BreadcrumbLink({
  children,
  className,
  ref,
  ...props
}: BreadcrumbLinkProps & { ref?: Ref<HTMLAnchorElement> }) {
  const linkProps: BreadcrumbLinkRenderProps = {
    ...props,
    className: cn(breadcrumbLinkClassName, className),
    'data-slot': 'breadcrumb-link',
    ref,
  }
  return typeof children === 'function' ? children(linkProps) : <a {...linkProps}>{children}</a>
}
export function BreadcrumbPage({ className, children, ...props }: HTMLAttributes<HTMLSpanElement>) {
  return (
    <span
      {...props}
      aria-current={props['aria-current'] ?? 'page'}
      className={cn(breadcrumbPageClassName, className)}
      data-slot="breadcrumb-page"
    >
      {children}
    </span>
  )
}
export function BreadcrumbSeparator({
  children,
  className,
  ...props
}: HTMLAttributes<HTMLLIElement>) {
  return (
    <li
      {...props}
      aria-hidden="true"
      className={cn(breadcrumbSeparatorClassName, className)}
      data-slot="breadcrumb-separator"
    >
      {children ?? '/'}
    </li>
  )
}
export function BreadcrumbEllipsis({
  children,
  className,
  ...props
}: HTMLAttributes<HTMLSpanElement>) {
  return (
    <span
      {...props}
      aria-hidden="true"
      className={cn(breadcrumbEllipsisClassName, className)}
      data-slot="breadcrumb-ellipsis"
    >
      {children ?? '...'}
    </span>
  )
}
