// packages/components/vue/src/primitive/form/form.vue
<script setup lang="ts">
import { scrollToFirstError, type ScrollToFirstError } from '@fex/components-core'
defineOptions({ inheritAttrs: false })
const props = withDefaults(defineProps<{
  form: { handleSubmit: () => unknown }
  component?: 'form' | false
  novalidate?: boolean
  scrollToFirstError?: ScrollToFirstError
}>(), { component: 'form' })
async function submit(event: Event) {
  const submitEvent = event as SubmitEvent
  if (submitEvent.defaultPrevented) return
  submitEvent.preventDefault()
  const element = submitEvent.currentTarget as HTMLFormElement
  await props.form.handleSubmit()
  await scrollToFirstError(element, props.scrollToFirstError ?? true)
}
</script>
<template><slot v-if="component === false" /><form v-else v-bind="$attrs" :novalidate="novalidate ?? true" @submit="submit"><slot /></form></template>

// packages/components/svelte/src/primitive/form/form.svelte
<script lang="ts">
  import { scrollToFirstError, type ScrollToFirstError } from '@fex/components-core'
  import type { AnyFormApi } from '@tanstack/svelte-form'
  import type { HTMLFormAttributes } from 'svelte/elements'
  import type { Snippet } from 'svelte'
  let { form, component = 'form', children, onsubmit, scrollToFirstError: scrollOption = true, ...rest }: HTMLFormAttributes & { form: AnyFormApi; component?: 'form' | false; children?: Snippet; scrollToFirstError?: ScrollToFirstError } = $props()
  async function submit(event: SubmitEvent & { currentTarget: EventTarget & HTMLFormElement }) { onsubmit?.(event); if (event.defaultPrevented) return; event.preventDefault(); const element = event.currentTarget; await form.handleSubmit(); await scrollToFirstError(element, scrollOption) }
</script>
{#if component === false}{@render children?.()}{:else}<form {...rest} novalidate={rest.novalidate ?? true} onsubmit={submit}>{@render children?.()}</form>{/if}
