// packages/components/svelte/src/primitive/popover/popover-portal.svelte
<script lang="ts">
  import type { Snippet } from 'svelte'
  import { getContext } from 'svelte'
  import { popoverContextKey, type PopoverContext } from './popover-context'

  interface PopoverPortalProps {
    children?: Snippet
    container?: HTMLElement | null
    forceMount?: boolean
  }

  let { children, container, forceMount }: PopoverPortalProps = $props()
  const { overlay, snapshot } = getContext<PopoverContext>(popoverContextKey)

  function portalAction(element: HTMLDivElement) {
    const target = container ?? overlay.resolvePopupContainer() ?? document.body
    target.appendChild(element)
    return {
      destroy() {
        element.remove()
      },
    }
  }
</script>

{#if $snapshot.mounted || forceMount}
  <div use:portalAction data-slot="popover-portal" style="display: contents">
    {@render children?.()}
  </div>
{/if}

// packages/components/vue/src/primitive/popover/popover-portal.vue
<script setup lang="ts">
import { computed } from 'vue'
import { usePopoverContext } from './context'

const props = defineProps<{
  container?: HTMLElement | null
  forceMount?: boolean
}>()

const { overlay, snapshot } = usePopoverContext('PopoverPortal')
const popupContainer = computed(() => props.container ?? overlay.resolvePopupContainer() ?? 'body')
const shouldRender = computed(() => snapshot.value.mounted || props.forceMount)
</script>

<template>
  <Teleport v-if="shouldRender" :to="popupContainer">
    <slot />
  </Teleport>
</template>
