// apps/svelte-admin/src/routes/data-grid/dnd-demo.svelte
<script lang="ts">
  import { columnOrderingFeature } from '@fex/components-core/data-grid/features/column-ordering'
  import { columnPinningFeature } from '@fex/components-core/data-grid/features/column-pinning'
  import { columnSizingFeature } from '@fex/components-core/data-grid/features/column-sizing'
  import type { DataGridColumnMeta } from '@fex/components-core/data-grid/types'
  import type { SortableControllerSnapshot } from '@fex/components-core/sortable/types'
  import { DataGrid, DataGridColumnOverlay, DataGridRowOverlay, tableFeatures, type ColumnDef } from '@fex/components-svelte/primitive/data-grid'
  import { createSortableAction } from '@fex/components-svelte/actions/sortable'
  import { createDataGridTable } from '@fex/components-svelte/stores/create-data-grid-table'
  import { onDestroy, untrack } from 'svelte'
  import type { Cell, Header } from '@fex/components-svelte/primitive/data-grid'
  import { people5, type Person } from './data'
  import DemoSection from './demo-section.svelte'
  import EllipsisIcon from '@fex/components-svelte/icon/more'

  const modules = { columnOrderingFeature, columnPinningFeature, columnSizingFeature }
  type Features = typeof modules & { columnMeta: DataGridColumnMeta<Features, Person> }
  const features: Features = tableFeatures({ ...modules, columnMeta: {} })
  const initial = ['name', 'department', 'status', 'id', 'age', 'visits', 'progress']
  const groups: Partial<Record<string, 'identity' | 'metrics'>> = { name: 'identity', department: 'identity', status: 'identity', visits: 'metrics', progress: 'metrics' }
  const labels: Record<string, string> = { name: 'Name', department: 'Department', status: 'Status', id: 'ID', age: 'Age', visits: 'Visits', progress: 'Progress' }
  const emptySnapshot: SortableControllerSnapshot = { activeId: null, activeContainerId: null, overId: null, overContainerId: null, dragging: false, activeRect: null, dragOffset: { x: 0, y: 0 }, items: {}, motionVersion: 0 }

  function columnGrid(constrained: boolean) {
    let order = [...initial]
    let snapshot = $state(emptySnapshot)
    let activeId: string | null = null
    let overId: string | null = null
    let message = $state('Drag a header with the project Sortable action.')
    const leaf = (id: string): ColumnDef<Features, Person> => ({ accessorKey: id, size: id === 'name' ? 180 : id === 'department' ? 170 : 140, header: labels[id] }) as unknown as ColumnDef<Features, Person>
    const leaves = initial.map(leaf)
    const columns: ColumnDef<Features, Person>[] = constrained ? [{ id: 'identity', header: 'Identity', columns: leaves.filter(column => 'accessorKey' in column && ['name', 'department', 'status'].includes(String(column.accessorKey))) }, ...leaves.filter(column => 'accessorKey' in column && ['id', 'age'].includes(String(column.accessorKey))), { id: 'metrics', header: 'Metrics', columns: leaves.filter(column => 'accessorKey' in column && ['visits', 'progress'].includes(String(column.accessorKey))) }] : leaves
    const table = createDataGridTable({ features, data: people5, columns, getRowId: row => row.id, initialState: { columnOrder: order, ...(constrained ? { columnPinning: { start: ['name'], end: ['progress'] } } : {}) } })
    const onChange = (next: string[]) => {
      const source = activeId ?? '', target = overId ?? ''
      if (constrained && (['name', 'progress'].includes(source) || ['name', 'progress'].includes(target))) { table.setColumnOrder(order); message = 'Rejected: pinned columns cannot be moved or targeted.'; return }
      if (constrained && groups[source] !== groups[target]) { table.setColumnOrder(order); message = 'Rejected: columns must share a real group, or both be ungrouped.'; return }
      order = [...next]; table.setColumnOrder(order); sortable.updateOptions({ items: order, axis: 'x', onChange, onSnapshot }); message = `Moved ${source} near ${target}.`
    }
    const onSnapshot = (value: SortableControllerSnapshot) => {
      snapshot = value
      if (typeof value.activeId === 'string') activeId = value.activeId
      if (typeof value.overId === 'string') overId = value.overId
      table.setColumnOrder(
        value.activeId === null ? order : (sortable.getPreviewItems() as string[]),
      )
    }
    const sortable = createSortableAction({ items: order, axis: 'x', onChange, onSnapshot })
    return {
      table, constrained,
      message: () => message,
      snapshot: () => snapshot,
      container: (node: HTMLElement) => sortable.container(node),
      headerAction: (node: HTMLElement, header: ReturnType<typeof table.getFlatHeaders>[number]) => header.isPlaceholder || header.column.columns.length || (constrained && ['name', 'progress'].includes(header.column.id)) ? undefined : sortable.item(node, { id: header.column.id }),
      cellAction: (node: HTMLElement, cell: Cell<Features, Person>) => { const cleanup = sortable.controller.registerMotionTarget(cell.column.id, node); return cleanup ? { destroy: cleanup } : undefined },
      activeHeader: () => typeof snapshot.activeId === 'string' ? table.getFlatHeaders().find(header => header.column.id === snapshot.activeId) : undefined,
      overlayStyle: () => {
        // Keep the inline style subscribed to pointer movement, not only the
        // active id that mounts the overlay.
        void snapshot.motionVersion
        return styleToString(sortable.getOverlayStyle())
      },
      motionStyle: (id: string) => {
        void snapshot.motionVersion
        return styleToString(sortable.getMotionStyle(id))
      },
      destroy: () => sortable.destroy(),
    }
  }
  const free = columnGrid(false), locked = columnGrid(true)
  const rowColumns: ColumnDef<Features, Person>[] = [{ id: '__drag__', header: '', size: 44 }, { accessorKey: 'name', header: 'Name' }, { accessorKey: 'department', header: 'Department' }, { accessorKey: 'status', header: 'Status' }]
  let rowOrder = $state(people5.map(person => person.id)), rowSnapshot = $state(emptySnapshot)
  const rowData = (order: readonly string[] = rowOrder) => order.map(id => people5.find(person => person.id === id)).filter((row): row is Person => row !== undefined)
  let committedRows = rowData()
  const rowTable = createDataGridTable({ features, data: committedRows, columns: rowColumns, getRowId: row => row.id })
  const syncRowTable = (order: readonly string[] = rowOrder) => {
    committedRows = rowData(order)
    rowTable.setDataGridOptions({ features, data: committedRows, columns: rowColumns, getRowId: row => row.id })
  }
  const onRowChange = (next: string[]) => {
    rowOrder = [...next]
    rowSortable.updateOptions({ items: rowOrder, axis: 'y', onChange: onRowChange, onSnapshot: updateRowSnapshot })
    syncRowTable()
  }
  const updateRowSnapshot = (value: SortableControllerSnapshot) => {
    rowSnapshot = value
    syncRowTable(value.activeId === null ? rowOrder : (rowSortable.getPreviewItems() as string[]))
  }
  const rowSortable = createSortableAction({ items: untrack(() => rowOrder), axis: 'y', onChange: onRowChange, onSnapshot: updateRowSnapshot })
  const rowContainer = (node: HTMLElement) => rowSortable.container(node)
  const rowAction = (node: HTMLElement, row: ReturnType<typeof rowTable.getRowModel>['rows'][number]) => rowSortable.item(node, { id: row.id })
  const activeRow = () => typeof rowSnapshot.activeId === 'string' ? rowTable.getRowModel().rows.find(row => row.id === rowSnapshot.activeId) : undefined
  const rowOverlayStyle = () => {
    void rowSnapshot.motionVersion
    return styleToString(rowSortable.getOverlayStyle())
  }
  const styleToString = (style: object) => (Object.entries(style) as Array<[string, string | number | undefined]>).filter(([, value]) => value !== undefined).map(([key, value]) => `${key.replace(/[A-Z]/g, match => `-${match.toLowerCase()}`)}:${value}`).join(';')
  onDestroy(() => { free.destroy(); locked.destroy(); rowSortable.destroy() })
</script>
{#snippet dndHeader(item: Header<Features, Person>)}
  {#if item.column.columns.length}{String(item.column.columnDef.header ?? '')}{:else}<span class="inline-flex min-w-0 items-center gap-2"><EllipsisIcon class="size-4 rotate-90 text-muted-foreground" /><span class="truncate">{labels[item.column.id]}</span></span>{/if}
{/snippet}
{#snippet rowOverlayCell(item: Cell<Features, Person>)}
  {#if item.column.id === '__drag__'}<EllipsisIcon class="size-4 rotate-90 text-muted-foreground" />{:else}{String(item.getValue() ?? '')}{/if}
{/snippet}
<DemoSection title="Column and row DnD with project Sortable" description="Both axes reuse the existing useSortable controller, overlay and motion registry. DataGrid only exposes native part props so callers can attach the project interaction without binding a policy into the table primitive.">
  <div class="space-y-space-lg">
    {#each [free, locked] as item (String(item.constrained))}<section class="space-y-space-sm"><h3 class="text-sm font-medium text-foreground">{item.constrained ? 'Column: group boundaries + pinned locked' : 'Column reorder'}</h3><div use:item.container><DataGrid table={item.table} header={dndHeader} headerAction={item.headerAction} cellAction={item.cellAction} getCellProps={cell => ({ style: `${item.motionStyle(cell.column.id)};visibility:${item.snapshot().activeId === cell.column.id ? 'hidden' : 'visible'}` })} /></div><p class="text-xs text-muted-foreground">{item.message()}</p>{#if item.activeHeader()}<DataGridColumnOverlay table={item.table} header={item.activeHeader()!} headerContent={dndHeader} style={`${item.overlayStyle()};height:auto`} />{/if}</section>{/each}
    <section class="space-y-space-sm"><h3 class="text-sm font-medium text-foreground">Row reorder</h3><div use:rowContainer><DataGrid table={rowTable} cell={rowOverlayCell} {rowAction} getRowProps={row => ({ class: rowSnapshot.activeId === row.id ? 'opacity-0' : undefined, style: styleToString(rowSortable.getItemStyle(row.id)) })} /></div><p class="text-xs text-muted-foreground">Current row order: {rowOrder.join(' → ')}</p>{#if activeRow()}<DataGridRowOverlay table={rowTable} row={activeRow()!} cellContent={rowOverlayCell} style={rowOverlayStyle()} />{/if}</section>
  </div>
</DemoSection>

// apps/angular-admin/src/pages/data-grid/dnd-demo.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core'
import { columnOrderingFeature } from '@fex/components-core/data-grid/features/column-ordering'
import { columnPinningFeature } from '@fex/components-core/data-grid/features/column-pinning'
import { columnSizingFeature } from '@fex/components-core/data-grid/features/column-sizing'
import type { DataGridColumnMeta } from '@fex/components-core/data-grid/types'
import { restoreSortableItems } from '@fex/components-core/sortable/containers'
import type { SortableControllerSnapshot } from '@fex/components-core/sortable/types'
import {
  DataGrid,
  DataGridCellTemplate,
  DataGridColumnOverlay,
  DataGridHeaderTemplate,
  DataGridRowOverlay,
  type DataGridPartAction,
  tableFeatures,
  type Cell,
  type ColumnDef,
  type Header,
  type Row,
} from '@fex/components-angular/primitive/data-grid'
import { createDataGridTable } from '@fex/components-angular/signals/create-data-grid-table'
import { EllipsisIcon } from '@fex/components-angular/icon/more'
import { bindSortableItem, FexSortable } from '@fex/components-angular/primitive/sortable'
import Card from '@fex/components-angular/ui/card'
import { people5, type Person } from './data'

const modules = { columnOrderingFeature, columnPinningFeature, columnSizingFeature }
type Features = typeof modules & { columnMeta: DataGridColumnMeta<Features, Person> }
type GridTable = ReturnType<typeof createDataGridTable<Features, Person>>
interface Grid {
  title: string
  constrained: boolean
  order: string[]
  table: GridTable
  message: string
}
const initial = ['name', 'department', 'status', 'id', 'age', 'visits', 'progress']
const labels: Record<string, string> = {
  name: 'Name',
  department: 'Department',
  status: 'Status',
  id: 'ID',
  age: 'Age',
  visits: 'Visits',
  progress: 'Progress',
}
const groups: Partial<Record<string, 'identity' | 'metrics'>> = {
  name: 'identity',
  department: 'identity',
  status: 'identity',
  visits: 'metrics',
  progress: 'metrics',
}

@Component({
  selector: 'fex-data-grid-dnd-demo',
  imports: [Card, DataGrid, DataGridCellTemplate, DataGridColumnOverlay, DataGridHeaderTemplate, DataGridRowOverlay, FexSortable, EllipsisIcon],
  templateUrl: './dnd-demo.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class DndDemoComponent {
  private readonly features: Features = tableFeatures({ ...modules, columnMeta: {} })
  protected readonly grids = [
    this.grid('Column reorder', false),
    this.grid('Column: group boundaries + pinned locked', true),
  ]
  private readonly rowColumns: ColumnDef<Features, Person>[] = [
    { id: '__drag__', header: '', size: 44 },
    { accessorKey: 'name', header: 'Name' },
    { accessorKey: 'department', header: 'Department' },
    { accessorKey: 'status', header: 'Status' },
  ]
  protected rowOrder = people5.map((person) => person.id)
  protected readonly rowTable = createDataGridTable({
    features: this.features,
    data: people5,
    columns: this.rowColumns,
    getRowId: (row) => row.id,
  })
  private readonly headerActions = new WeakMap<
    FexSortable<string[]>,
    DataGridPartAction<Header<Features, Person>>
  >()
  private readonly cellActions = new WeakMap<
    FexSortable<string[]>,
    DataGridPartAction<Cell<Features, Person>>
  >()
  private readonly rowActions = new WeakMap<
    FexSortable<string[]>,
    DataGridPartAction<Row<Features, Person>>
  >()

  private grid(title: string, constrained: boolean): Grid {
    const leaves: ColumnDef<Features, Person>[] = initial.map(
      (id) =>
        ({
          accessorKey: id,
          header: labels[id],
          size: id === 'name' ? 180 : id === 'department' ? 170 : 140,
        }) as ColumnDef<Features, Person>,
    )
    const columns: ColumnDef<Features, Person>[] = constrained
      ? [
          {
            id: 'identity',
            header: 'Identity',
            columns: leaves.filter(
              (column) =>
                'accessorKey' in column &&
                ['name', 'department', 'status'].includes(String(column.accessorKey)),
            ),
          },
          ...leaves.filter(
            (column) =>
              'accessorKey' in column && ['id', 'age'].includes(String(column.accessorKey)),
          ),
          {
            id: 'metrics',
            header: 'Metrics',
            columns: leaves.filter(
              (column) =>
                'accessorKey' in column &&
                ['visits', 'progress'].includes(String(column.accessorKey)),
            ),
          },
        ]
      : leaves
    return {
      title,
      constrained,
      order: [...initial],
      message: 'Drag a header with the project Sortable primitive.',
      table: createDataGridTable({
        features: this.features,
        data: people5,
        columns,
        getRowId: (row) => row.id,
        initialState: {
          columnOrder: initial,
          ...(constrained ? { columnPinning: { start: ['name'], end: ['progress'] } } : {}),
        },
      }),
    }
  }

  protected columnsChanged(grid: Grid, next: string[]) {
    const source = grid.order.find((id) => next.indexOf(id) !== grid.order.indexOf(id))
    const target = source ? grid.order[next.indexOf(source)] : undefined
    if (
      grid.constrained &&
      source &&
      target &&
      (['name', 'progress'].includes(source) ||
        ['name', 'progress'].includes(target) ||
        groups[source] !== groups[target])
    ) {
      grid.message =
        'Rejected: columns must share a real group, or both be ungrouped; pinned columns are locked.'
      return
    }
    grid.order = [...next]
    grid.table.setColumnOrder(next)
    grid.message = source && target ? `Moved ${source} near ${target}.` : 'Column order updated.'
  }

  protected columnsPreviewChanged(grid: Grid, snapshot: SortableControllerSnapshot) {
    if (!snapshot.dragging) {
      return
    }
    grid.table.setColumnOrder(restoreSortableItems(grid.order, snapshot.items))
  }

  protected rowsChanged(next: string[]) {
    this.rowOrder = [...next]
    const data = this.rowOrder
      .map((id) => people5.find((person) => person.id === id))
      .filter((row): row is Person => row !== undefined)
    this.rowTable.setDataGridOptions({
      features: this.features,
      data,
      columns: this.rowColumns,
      getRowId: (row) => row.id,
    })
  }

  protected rowsPreviewChanged(snapshot: SortableControllerSnapshot) {
    if (!snapshot.dragging) {
      return
    }
    const previewOrder = restoreSortableItems(this.rowOrder, snapshot.items)
    const data = previewOrder
      .map((id) => people5.find((person) => person.id === id))
      .filter((row): row is Person => row !== undefined)
    this.rowTable.setDataGridOptions({
      features: this.features,
      data,
      columns: this.rowColumns,
      getRowId: (row) => row.id,
    })
  }

  protected headerAction(sortable: FexSortable<string[]>, grid: Grid) {
    let action = this.headerActions.get(sortable)
    if (!action) {
      action = (node, header) => {
        if (
          header.isPlaceholder ||
          header.column.columns.length > 0 ||
          (grid.constrained && ['name', 'progress'].includes(header.column.id))
        )
          return
        node.classList.add('cursor-grab', 'touch-none', 'select-none')
        const cleanup = bindSortableItem(sortable, node, header.column.id)
        return () => {
          cleanup()
          node.classList.remove('cursor-grab', 'touch-none', 'select-none')
        }
      }
      this.headerActions.set(sortable, action)
    }
    return action
  }

  protected cellAction(sortable: FexSortable<string[]>) {
    let action = this.cellActions.get(sortable)
    if (!action) {
      action = (node, cell) => {
        const cleanupTarget = sortable.registerMotionTarget(cell.column.id, node)
        const apply = () => {
          const style = sortable.getMotionStyle(cell.column.id)
          node.style.transform = style.transform === undefined ? '' : String(style.transform)
          node.style.transition = style.transition === undefined ? '' : String(style.transition)
          node.style.visibility = sortable.activeId() === cell.column.id ? 'hidden' : ''
        }
        const unsubscribe = sortable.controller.subscribe(apply)
        apply()
        return () => {
          cleanupTarget?.()
          unsubscribe()
        }
      }
      this.cellActions.set(sortable, action)
    }
    return action
  }

  protected rowAction(sortable: FexSortable<string[]>) {
    let action = this.rowActions.get(sortable)
    if (!action) {
      action = (node, row) => {
        node.classList.add('cursor-grab', 'touch-none', 'select-none')
        const cleanup = bindSortableItem(sortable, node, row.id)
        return () => {
          cleanup()
          node.classList.remove('cursor-grab', 'touch-none', 'select-none')
        }
      }
      this.rowActions.set(sortable, action)
    }
    return action
  }

  protected label(id: string) {
    return labels[id] ?? id
  }
  protected activeRow(id: string | number | null) {
    return typeof id === 'string'
      ? this.rowTable.getRowModel().rows.find((row) => row.id === id)
      : undefined
  }
  protected activeHeader(grid: Grid, id: string | number) {
    const columnId = String(id)
    return grid.table.getFlatHeaders().find((header) => header.column.id === columnId)
  }
}

<fex-card
  title="Column and row DnD with project Sortable"
  description="Both axes reuse the existing useSortable controller, overlay and motion registry. DataGrid only exposes native part props so callers can attach the project interaction without binding a policy into the table primitive."
>
  <ng-template #overlayHeader let-header>
    <span class="inline-flex min-w-0 items-center gap-2">
      <fex-ellipsis-icon class="block size-4 rotate-90 text-muted-foreground" />
      <span class="truncate">{{ label(header.column.id) }}</span>
    </span>
  </ng-template>
  <ng-template #rowOverlayCell let-cell>
    @if (cell.column.id === '__drag__') { <fex-ellipsis-icon class="block size-4 rotate-90 text-muted-foreground" /> }
    @else { {{ cell.getValue() }} }
  </ng-template>
  <div class="space-y-space-lg">
    @for (grid of grids; track grid.title) {
      <section class="space-y-space-sm">
        <h3 class="text-sm font-medium text-foreground">{{ grid.title }}</h3>
        <fex-sortable
          #sortable="fexSortable"
          class="block"
          [items]="grid.order"
          axis="x"
          (itemsChange)="columnsChanged(grid, $event)"
          (snapshotChange)="columnsPreviewChanged(grid, $event)"
        >
          <fex-data-grid
            [table]="grid.table"
            [headerAction]="headerAction(sortable, grid)"
            [cellAction]="cellAction(sortable)"
          >
            <ng-template fexDataGridHeader let-header>
              @if (header.column.columns.length) {
                {{ header.column.columnDef.header }}
              } @else {
                <span class="inline-flex min-w-0 items-center gap-2">
                  <fex-ellipsis-icon class="block size-4 rotate-90 text-muted-foreground" />
                  <span class="truncate">{{ label(header.column.id) }}</span>
                </span>
              }
            </ng-template>
          </fex-data-grid>
          @if (sortable.activeId(); as activeId) {
            @if (activeHeader(grid, activeId); as activeHeader) {
              <fex-data-grid-column-overlay
                [table]="grid.table"
                [header]="activeHeader"
                [headerTemplate]="overlayHeader"
                [style]="sortable.getOverlayStyle()"
              />
            }
          }
        </fex-sortable>
        <p class="text-xs text-muted-foreground">{{ grid.message }}</p>
      </section>
    }
    <section class="space-y-space-sm">
      <h3 class="text-sm font-medium text-foreground">Row reorder</h3>
      <fex-sortable
        #rowSort="fexSortable"
        class="block"
        [items]="rowOrder"
        axis="y"
        (itemsChange)="rowsChanged($event)"
        (snapshotChange)="rowsPreviewChanged($event)"
      >
        <fex-data-grid [table]="rowTable" [rowAction]="rowAction(rowSort)">
          <ng-template fexDataGridCell let-cell>
            @if (cell.column.id === '__drag__') {
              <fex-ellipsis-icon class="block size-4 rotate-90 cursor-grab text-muted-foreground" />
            } @else {
              {{ cell.getValue() }}
            }
          </ng-template>
        </fex-data-grid>
        @if (activeRow(rowSort.activeId()); as row) {
          <fex-data-grid-row-overlay
            [table]="rowTable"
            [row]="row"
            [cellTemplate]="rowOverlayCell"
            [style]="rowSort.getOverlayStyle()"
          />
        }
      </fex-sortable>
      <p class="text-xs text-muted-foreground">Current row order: {{ rowOrder.join(' → ') }}</p>
    </section>
  </div>
</fex-card>
