// apps/svelte-admin/src/routes/data-grid/ordering-demo.svelte
<script lang="ts">
  import { columnOrderingFeature, moveDataGridColumn } from '@fex/components-core/data-grid/features/column-ordering'
  import type { DataGridColumnMeta } from '@fex/components-core/data-grid/types'
  import { DataGrid, tableFeatures, type ColumnDef } from '@fex/components-svelte/primitive/data-grid'
  import Button from '@fex/components-svelte/ui/button'
  import { createDataGridTable } from '@fex/components-svelte/stores/create-data-grid-table'
  import { people5, type Person } from './data'
  import DemoSection from './demo-section.svelte'
  const modules = { columnOrderingFeature }
  type Features = typeof modules & { columnMeta: DataGridColumnMeta<Features, Person> }
  const features: Features = tableFeatures({ ...modules, columnMeta: {} })
  const ids = ['name', 'department', 'status', 'visits']
  const columns: ColumnDef<Features, Person>[] = [{ accessorKey: 'name', header: 'Name' }, { accessorKey: 'department', header: 'Department' }, { accessorKey: 'status', header: 'Status' }, { accessorKey: 'visits', header: 'Visits' }]
  const table = createDataGridTable({ features, data: people5, columns, getRowId: row => row.id, initialState: { columnOrder: ids } })
</script>
<DemoSection title="Column ordering" description="The feature only owns columnOrder and actions. These buttons are one possible UI; DnD is demonstrated separately as caller-owned behavior."><section class="space-y-space-sm"><h3 class="text-sm font-medium text-foreground">Programmatic reorder</h3><div class="flex gap-space-sm"><Button size="sm" variant="outline" onclick={() => table.setColumnOrder(order => moveDataGridColumn(order, 'status', 'name'))}>Move Status first</Button><Button size="sm" variant="outline" onclick={() => table.resetColumnOrder()}>Reset</Button></div><DataGrid {table} /></section></DemoSection>

// apps/angular-admin/src/pages/data-grid/ordering-demo.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core'
import {
  columnOrderingFeature,
  moveDataGridColumn,
} from '@fex/components-core/data-grid/features/column-ordering'
import type { DataGridColumnMeta } from '@fex/components-core/data-grid/types'
import {
  DataGrid,
  tableFeatures,
  type ColumnDef,
} from '@fex/components-angular/primitive/data-grid'
import { createDataGridTable } from '@fex/components-angular/signals/create-data-grid-table'
import { Button } from '@fex/components-angular/ui/button'
import Card from '@fex/components-angular/ui/card'
import { people5, type Person } from './data'
const modules = { columnOrderingFeature }
type Features = typeof modules & { columnMeta: DataGridColumnMeta<Features, Person> }
export
@Component({
  selector: 'fex-data-grid-ordering-demo',
  imports: [Card, DataGrid, Button],
  templateUrl: './ordering-demo.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
class OrderingDemoComponent {
  private readonly features: Features = tableFeatures({ ...modules, columnMeta: {} })
  private readonly ids = ['name', 'department', 'status', 'visits']
  private readonly columns: ColumnDef<Features, Person>[] = [
    { accessorKey: 'name', header: 'Name' },
    { accessorKey: 'department', header: 'Department' },
    { accessorKey: 'status', header: 'Status' },
    { accessorKey: 'visits', header: 'Visits' },
  ]
  protected readonly table = createDataGridTable({
    features: this.features,
    data: people5,
    columns: this.columns,
    getRowId: (r) => r.id,
    initialState: { columnOrder: this.ids },
  })
  protected move() {
    this.table.setColumnOrder((order) => moveDataGridColumn(order, 'status', 'name'))
  }
}

<fex-card
  title="Column ordering"
  description="The feature only owns columnOrder and actions. These buttons are one possible UI; DnD is demonstrated separately as caller-owned behavior."
  ><section class="space-y-space-sm">
    <h3 class="text-sm font-medium">Programmatic reorder</h3>
    <div class="flex gap-space-sm">
      <button fexButton size="sm" variant="outline" (click)="move()">Move Status first</button
      ><button fexButton size="sm" variant="outline" (click)="table.resetColumnOrder()">Reset</button>
    </div>
    <fex-data-grid [table]="table" /></section
></fex-card>
