// packages/@fex-design/react/src/primitive/separator/separator.tsx
import { separatorClassName } from '@fex-design/styles/separator'
import { cn } from '@fex/utils'
import type { ComponentProps } from 'react'
export function Separator({
  orientation = 'horizontal',
  decorative = true,
  className,
  ...props
}: ComponentProps<'div'> & { orientation?: 'horizontal' | 'vertical'; decorative?: boolean }) {
  return (
    <div
      role={decorative ? 'none' : 'separator'}
      aria-orientation={decorative ? undefined : orientation}
      data-slot="separator"
      data-orientation={orientation}
      className={cn(separatorClassName, className)}
      {...props}
    />
  )
}

// packages/@fex-design/solid/src/primitive/separator/separator.tsx
import { separatorClassName } from '@fex-design/styles/separator'
import { cn } from '@fex/utils'
import { splitProps, type JSX } from 'solid-js'
export function Separator(
  props: JSX.HTMLAttributes<HTMLDivElement> & {
    orientation?: 'horizontal' | 'vertical'
    decorative?: boolean
  },
) {
  const [local, rest] = splitProps(props, ['class', 'orientation', 'decorative'])
  const orientation = () => local.orientation ?? 'horizontal'
  return (
    <div
      {...rest}
      role={(local.decorative ?? true) ? 'none' : 'separator'}
      aria-orientation={(local.decorative ?? true) ? undefined : orientation()}
      data-slot="separator"
      data-orientation={orientation()}
      class={cn(separatorClassName, local.class)}
    />
  )
}
