// packages/@fex-design/svelte/src/primitive/empty/empty-header.svelte
<script lang="ts">
  import { emptyHeaderClassName } from '@fex-design/styles/empty'
  import { cn } from '@fex/utils'
  import type { Snippet } from 'svelte'
  import type { HTMLAttributes } from 'svelte/elements'
  interface Props extends Omit<HTMLAttributes<HTMLDivElement>, 'class'> { class?: string; children?: Snippet }
  let { class: className, children, ...rest }: Props = $props()
  const classList = $derived(cn(emptyHeaderClassName, className))
</script>
<div {...rest} data-slot="empty-header" class={classList}>{@render children?.()}</div>

// packages/@fex-design/vue/src/primitive/empty/empty-header.vue
<script setup lang="ts">
import { emptyHeaderClassName } from '@fex-design/styles/empty'
import { cn } from '@fex/utils'

defineOptions({ inheritAttrs: false })
const props = defineProps<{ class?: string | undefined }>()
</script>

<template>
  <div v-bind="$attrs" data-slot="empty-header" :class="cn(emptyHeaderClassName, props.class)">
    <slot />
  </div>
</template>
