// packages/@fex-design/vue/src/primitive/mentions/mentions-item.vue
<script setup lang="ts" generic="TData = unknown">
import type { MentionsKey, MentionsRegisteredItem } from '@fex-design/core/mentions/types'
import { mentionsItemClassName } from '@fex-design/styles/mentions'
import { cn } from '@fex/utils'
import { computed, onScopeDispose, watchEffect } from 'vue'
import ListboxItem from '../listbox/listbox-item.vue'
import { useMentions } from './context'

const props = withDefaults(
  defineProps<{
    itemKey?: MentionsKey
    value: string
    disabled?: boolean
    data?: TData
    class?: string
  }>(),
  { disabled: false },
)
const mentions = useMentions('MentionsItem')
const key = computed(() => props.itemKey ?? props.value)
const active = computed(() => mentions.snapshot.value.activeKey === key.value)
const item = computed<MentionsRegisteredItem<TData>>(() => ({
  key: key.value,
  value: props.value,
  disabled: props.disabled,
  data: props.data,
}))
let unregister: (() => void) | undefined
watchEffect(() => {
  unregister?.()
  unregister = mentions.controller.registerItem(item.value)
})
onScopeDispose(() => unregister?.())
const className = computed(() => cn(mentionsItemClassName, props.class))
</script>

<template>
  <ListboxItem
    :id="`${mentions.listId}-${key}`"
    :value="key"
    :disabled="props.disabled"
    :class="className"
    @pointermove="mentions.controller.setActiveKey(key, 'pointer')"
    @pointerdown.prevent
    @select="mentions.controller.selectItem(key)"
  >
    <slot :active="active" :disabled="props.disabled" :item="item">{{ props.value }}</slot>
  </ListboxItem>
</template>

// packages/@fex-design/svelte/src/primitive/mentions/mentions-item.svelte
<script lang="ts">
  import type { MentionsKey, MentionsRegisteredItem } from '@fex-design/core/mentions/types'
  import { mentionsItemClassName } from '@fex-design/styles/mentions'
  import { cn } from '@fex/utils'
  import type { Snippet } from 'svelte'
  import ListboxItem from '../listbox/listbox-item.svelte'
  import { useMentions } from './context'

  interface Props {
    class?: string | undefined
    itemKey?: MentionsKey | undefined
    value: string
    disabled?: boolean | undefined
    data?: unknown
    children?: Snippet | undefined
  }

  let { class: className, itemKey, value, disabled = false, data, children }: Props = $props()
  const mentions = useMentions('MentionsItem')
  const key = $derived(itemKey ?? value)
  const active = $derived(mentions.snapshot().activeKey === key)
  let unregister: (() => void) | undefined
  $effect(() => {
    unregister?.()
    const item: MentionsRegisteredItem = { key, value, disabled, data }
    unregister = mentions.controller.registerItem(item)
    return () => unregister?.()
  })
</script>

<ListboxItem
  id={mentions.listId + '-' + key}
  value={key}
  {disabled}
  class={cn(mentionsItemClassName, className)}
  onpointermove={() => mentions.controller.setActiveKey(key, 'pointer')}
  onpointerdown={(event) => event.preventDefault()}
  onSelect={() => mentions.controller.selectItem(key)}
>
  {@render children?.()}
  {#if !children}{value}{/if}
</ListboxItem>
