// packages/@fex-design/vue/src/primitive/mentions/mentions-content.vue
<script setup lang="ts">
import { mentionsContentClassName } from '@fex-design/styles/mentions'
import { cn } from '@fex/utils'
import { computed } from 'vue'
import { useMentions } from './context'

const props = defineProps<{ class?: string }>()
const mentions = useMentions('MentionsContent')
const className = computed(() =>
  cn(mentionsContentClassName, 'absolute left-0 top-full mt-1 min-w-64', props.class),
)
</script>

<template>
  <div
    v-if="mentions.snapshot.value.open && mentions.snapshot.value.query"
    data-slot="mentions-content"
    :class="className"
  >
    <slot />
  </div>
</template>

// packages/@fex-design/svelte/src/primitive/mentions/mentions-content.svelte
<script lang="ts">
  import { mentionsContentClassName } from '@fex-design/styles/mentions'
  import { cn } from '@fex/utils'
  import type { Snippet } from 'svelte'
  import { useMentions } from './context'

  let { class: className, children }: { class?: string; children?: Snippet } = $props()
  const mentions = useMentions('MentionsContent')
</script>

{#if mentions.snapshot().open && mentions.snapshot().query}
  <div
    data-slot="mentions-content"
    class={cn(mentionsContentClassName, 'absolute left-0 top-full mt-1 min-w-64', className)}
  >
    {@render children?.()}
  </div>
{/if}
