// apps/react-admin/src/pages/Breadcrumb/classic-breadcrumb.tsx
import {
  Breadcrumb,
  BreadcrumbItem,
  BreadcrumbLink,
  BreadcrumbList,
  BreadcrumbPage,
  BreadcrumbSeparator,
} from '@fex-design/react/primitive/breadcrumb'

export function ClassicBreadcrumb({ separator = '/' }: { separator?: string }) {
  return (
    <Breadcrumb>
      <BreadcrumbList>
        <BreadcrumbItem>
          <BreadcrumbLink href="/">Workspace</BreadcrumbLink>
        </BreadcrumbItem>
        <BreadcrumbSeparator>{separator}</BreadcrumbSeparator>
        <BreadcrumbItem>
          <BreadcrumbLink href="/projects">Projects</BreadcrumbLink>
        </BreadcrumbItem>
        <BreadcrumbSeparator>{separator}</BreadcrumbSeparator>
        <BreadcrumbItem>
          <BreadcrumbPage>Quarterly plan</BreadcrumbPage>
        </BreadcrumbItem>
      </BreadcrumbList>
    </Breadcrumb>
  )
}

// apps/angular-app/src/pages/breadcrumb/classic-breadcrumb.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core'
import { RouterLink } from '@angular/router'
import { Breadcrumb, BreadcrumbItem, BreadcrumbLink, BreadcrumbList, BreadcrumbPage, BreadcrumbSeparator } from '@fex-design/angular/primitive/breadcrumb'
@Component({ selector: 'app-breadcrumb-classic', standalone: true, imports: [RouterLink, Breadcrumb, BreadcrumbList, BreadcrumbItem, BreadcrumbLink, BreadcrumbPage, BreadcrumbSeparator], templateUrl: './classic-breadcrumb.component.html', changeDetection: ChangeDetectionStrategy.OnPush })
export class ClassicBreadcrumbComponent {}
