// packages/components/react/src/primitive/data-grid/data-grid-filter-input.tsx
import { dataGridInputRootClassName } from '@fex/components-styles/data-grid'
import { cn } from '@fex/utils'
import type { Column, RowData, TableFeatures } from '@tanstack/react-table'
import type { InputHTMLAttributes } from 'react'
import { InputControl, InputRoot } from '../input/input'

export interface DataGridFilterInputProps<
  TFeatures extends TableFeatures,
  TData extends RowData,
> extends Omit<InputHTMLAttributes<HTMLInputElement>, 'value' | 'onChange'> {
  column: Column<TFeatures, TData>
}

export function DataGridFilterInput<TFeatures extends TableFeatures, TData extends RowData>({
  column,
  className,
  ...props
}: DataGridFilterInputProps<TFeatures, TData>) {
  const filterColumn = column as unknown as Column<TFeatures, TData> & {
    getFilterValue: () => unknown
    setFilterValue: (value: unknown) => void
  }
  return (
    <InputRoot
      value={String(filterColumn.getFilterValue() ?? '')}
      className={cn(dataGridInputRootClassName, className)}
    >
      <InputControl {...props} onChange={(event) => filterColumn.setFilterValue(event.currentTarget.value)} />
    </InputRoot>
  )
}

// packages/components/vue/src/primitive/data-grid/data-grid-filter-input.vue
<script setup lang="ts" generic="TFeatures extends TableFeatures, TData extends RowData">
import { dataGridInputRootClassName } from '@fex/components-styles/data-grid'
import type { Column, RowData, TableFeatures } from '@tanstack/table-core'
import { InputControl, InputRoot } from '../input/input'
interface FilterableColumn {
  getFilterValue(): unknown
  setFilterValue(value: unknown): void
}
const props = defineProps<{ column: Column<TFeatures, TData>; placeholder?: string }>()
const column = props.column as unknown as FilterableColumn
</script>
<template>
  <InputRoot :value="String(column.getFilterValue() ?? '')" :class="dataGridInputRootClassName"><InputControl :placeholder="props.placeholder" @input="column.setFilterValue(($event.target as HTMLInputElement).value)" /></InputRoot>
</template>
