// apps/solid-admin/src/pages/Transfer/basic-demo.tsx
import { Transfer } from '@fex/components-solid/primitive/transfer'
import { Card } from '@fex/components-solid/ui/card'
import { createSignal } from 'solid-js'
import { fieldNames, members } from './data'
export function BasicDemo() {
  const [targetKeys, setTargetKeys] = createSignal<readonly (string | number)[]>(['susan'])
  return (
    <Card
      title="Basic, controlled and uncontrolled"
      description="The first Transfer owns its target keys; the second exposes target keys and complete moved items through onChange meta."
    >
      <div class="grid gap-space-lg xl:grid-cols-2">
        <section class="space-y-space-sm">
          <h3 class="text-sm font-medium">Uncontrolled</h3>
          <Transfer
            items={members}
            fieldNames={fieldNames}
            defaultTargetKeys={['grace']}
            title={{ source: 'Available', target: 'Assigned' }}
          />
        </section>
        <section class="space-y-space-sm">
          <h3 class="text-sm font-medium">Controlled</h3>
          <Transfer
            items={members}
            fieldNames={fieldNames}
            targetKeys={targetKeys()}
            onChange={setTargetKeys}
            title={{ source: 'Team directory', target: 'Project team' }}
          />
          <p class="text-xs text-muted-foreground">
            Target keys: {targetKeys().join(', ') || 'none'}
          </p>
        </section>
      </div>
    </Card>
  )
}

// apps/vue-admin/src/pages/Transfer/basic-demo.vue
<script setup lang="ts">
import { Transfer } from '@fex/components-vue/primitive/transfer'
import Card from '@fex/components-vue/ui/card'
import { ref } from 'vue'
import { fieldNames, members } from './data'
const targetKeys = ref<readonly (string | number)[]>(['susan'])
</script>
<template>
  <Card
    title="Basic, controlled and uncontrolled"
    description="The first Transfer owns its target keys; the second exposes target keys and complete moved items through onChange meta."
    ><div class="grid gap-space-lg xl:grid-cols-2">
      <section class="space-y-space-sm">
        <h3 class="text-sm font-medium">Uncontrolled</h3>
        <Transfer
          :items="members"
          :field-names="fieldNames"
          :default-target-keys="['grace']"
          :title="{ source: 'Available', target: 'Assigned' }"
        />
      </section>
      <section class="space-y-space-sm">
        <h3 class="text-sm font-medium">Controlled</h3>
        <Transfer
          :items="members"
          :field-names="fieldNames"
          :target-keys="targetKeys"
          :title="{ source: 'Team directory', target: 'Project team' }"
          @change="targetKeys = $event"
        />
        <p class="text-xs text-muted-foreground">
          Target keys: {{ targetKeys.join(', ') || 'none' }}
        </p>
      </section>
    </div></Card
  >
</template>
