// apps/svelte-admin/src/routes/data-grid/presentation-demo.svelte
<script lang="ts">
  import type { DataGridColumnMeta } from '@fex/components-core/data-grid/types'
  import { DataGrid, tableFeatures, type ColumnDef } from '@fex/components-svelte/primitive/data-grid'
  import { createDataGridTable } from '@fex/components-svelte/stores/create-data-grid-table'
  import { people, type Person } from './data'
  import DemoSection from './demo-section.svelte'
  type Features = { columnMeta: DataGridColumnMeta<Features, Person> }
  const features: Features = tableFeatures({ columnMeta: {} })
  const columns: ColumnDef<Features, Person>[] = [{ accessorKey: 'name', header: 'Name' }, { accessorKey: 'status', header: 'Status' }]
  const dataTable = createDataGridTable({ features, data: people.slice(0, 3), columns, getRowId: row => row.id })
  const emptyTable = createDataGridTable({ features, data: [], columns, getRowId: row => row.id })
</script>
<DemoSection title="Loading, empty and customization states" description="Presentation states are primitive props and structured part classes; they do not change table state or start requests."><div class="grid gap-space-lg xl:grid-cols-3"><section class="space-y-space-sm"><h3 class="text-sm font-medium text-foreground">Loading overlay</h3><DataGrid table={dataTable} loading loadingContent="Refreshing rows…" /></section><section class="space-y-space-sm"><h3 class="text-sm font-medium text-foreground">Custom empty</h3><DataGrid table={emptyTable} emptyContent="No matching members" /></section><section class="space-y-space-sm"><h3 class="text-sm font-medium text-foreground">Part class customization</h3><DataGrid table={dataTable} class={{ header: 'bg-primary/10', row: 'hover:bg-primary/5', cell: 'font-medium' }} /></section></div></DemoSection>

// apps/react-admin/src/pages/DataGrid/presentation-demo.tsx
import type { DataGridColumnMeta } from '@fex/components-core/data-grid/types'
import type { TableFeatures } from '@fex/components-react/primitive/data-grid'
import {
  DataGrid,
  tableFeatures,
  useDataGridTable,
  type ColumnDef,
} from '@fex/components-react/primitive/data-grid'
import { DataGridDemoSection, DemoBranch } from './demo-section'
import { people3, type Person } from './data'

const presentationFeatures = tableFeatures({
  columnMeta: {} as DataGridColumnMeta<TableFeatures, Person>,
})
const columns: ColumnDef<typeof presentationFeatures, Person>[] = [
  { accessorKey: 'name', header: 'Name' },
  { accessorKey: 'status', header: 'Status' },
]

export function PresentationDataGridDemo() {
  const dataTable = useDataGridTable({
    features: presentationFeatures,
    data: people3,
    columns,
    getRowId: (row) => row.id,
  })
  const emptyTable = useDataGridTable({
    features: presentationFeatures,
    data: [],
    columns,
    getRowId: (row) => row.id,
  })
  return (
    <DataGridDemoSection
      title="Loading, empty and customization states"
      description="Presentation states are primitive props and structured part classes; they do not change table state or start requests."
    >
      <div className="grid gap-space-lg xl:grid-cols-3">
        <DemoBranch title="Loading overlay">
          <DataGrid table={dataTable} loading loadingContent="Refreshing rows…" />
        </DemoBranch>
        <DemoBranch title="Custom empty">
          <DataGrid table={emptyTable} emptyContent="No matching members" />
        </DemoBranch>
        <DemoBranch title="Part class customization">
          <DataGrid
            table={dataTable}
            className={{ header: 'bg-primary/10', row: 'hover:bg-primary/5', cell: 'font-medium' }}
          />
        </DemoBranch>
      </div>
    </DataGridDemoSection>
  )
}
