// apps/vue-admin/src/pages/DataGrid/row-pinning-demo.vue
﻿<script setup lang="ts">
import { rowPinningFeature } from '@fex/components-core/data-grid/features/row-pinning'
import type { DataGridColumnMeta } from '@fex/components-core/data-grid/types'
import { DataGrid, tableFeatures, type ColumnDef } from '@fex/components-vue/primitive/data-grid'
import { useDataGridTable } from '@fex/components-vue/composables/use-data-grid-table'
import { Badge } from '@fex/components-vue/ui/badge'
import Button from '@fex/components-vue/ui/button'
import { h, type Component } from 'vue'
import { people, type Person } from './data'
import DemoSection from './demo-section.vue'
const m = { rowPinningFeature }
type F = typeof m & { columnMeta: DataGridColumnMeta<F, Person> }
const f: F = tableFeatures({ ...m, columnMeta: {} })
interface P {
  getIsPinned(): false | 'top' | 'bottom'
  pin(value: false | 'top' | 'bottom'): void
}
const B = Button as Component,
  Tag = Badge as Component
const columns: ColumnDef<F, Person>[] = [
  {
    accessorKey: 'name',
    header: 'Name',
    cell: ({ row, getValue }) => {
      const p = row as unknown as P
      return h('span', { class: 'inline-flex items-center gap-2' }, [
        p.getIsPinned() ? h(Tag, { variant: 'outline' }, () => `Pinned ${p.getIsPinned()}`) : null,
        String(getValue()),
      ])
    },
  },
  { accessorKey: 'status', header: 'Status' },
  {
    id: 'pin',
    header: 'Pin row',
    cell: ({ row }) => {
      const p = row as unknown as P
      return h('span', { class: 'inline-flex gap-1' }, [
        h(B, { size: 'sm', variant: 'outline', onClick: () => p.pin('top') }, () => 'Top'),
        h(B, { size: 'sm', variant: 'outline', onClick: () => p.pin(false) }, () => 'Center'),
        h(B, { size: 'sm', variant: 'outline', onClick: () => p.pin('bottom') }, () => 'Bottom'),
      ])
    },
  },
]
const table = useDataGridTable({
  features: f,
  data: people.slice(0, 7),
  columns,
  getRowId: (r) => r.id,
  initialState: { rowPinning: { top: ['u-006'], bottom: ['u-002'] } },
})
</script>
<template>
  <DemoSection
    title="Row pinning"
    description="Pinned rows are opaque layers above the scrollable center region. Their edge shadow appears only at the boundary, and the controls can add more rows to either region."
    ><section class="space-y-space-sm">
      <h3 class="text-sm font-medium text-foreground">Top, scrollable center and bottom</h3>
      <DataGrid :table="table" :part-class="{ viewport: 'max-h-56' }" /></section
  ></DemoSection>
</template>

// apps/react-admin/src/pages/DataGrid/row-pinning-demo.tsx
/* oxlint-disable react/no-unstable-nested-components -- TanStack cell renderers are configuration callbacks stabilized by useDataGridTable. */
import { rowPinningFeature } from '@fex/components-core/data-grid/features/row-pinning'
import type { DataGridColumnMeta } from '@fex/components-core/data-grid/types'
import type { TableFeatures } from '@fex/components-react/primitive/data-grid'
import {
  DataGrid,
  tableFeatures,
  useDataGridTable,
  type ColumnDef,
} from '@fex/components-react/primitive/data-grid'
import { Badge } from '@fex/components-react/ui/badge'
import { Button } from '@fex/components-react/ui/button'
import { DataGridDemoSection, DemoBranch } from './demo-section'
import { people7, type Person } from './data'

const rowPinningFeatures = tableFeatures({
  rowPinningFeature,
  columnMeta: {} as DataGridColumnMeta<TableFeatures, Person>,
})

export function RowPinningDataGridDemo() {
  type PinnedRow = {
    id: string
    getIsPinned: () => false | 'top' | 'bottom'
    pin: (position: false | 'top' | 'bottom') => void
  }
  const columns: ColumnDef<typeof rowPinningFeatures, Person>[] = [
    {
      accessorKey: 'name',
      header: 'Name',
      cell: ({ row, getValue }: { row: PinnedRow; getValue: () => unknown }) => (
        <span className="inline-flex items-center gap-2">
          {row.getIsPinned() ? <Badge variant="outline">Pinned {row.getIsPinned()}</Badge> : null}
          {String(getValue())}
        </span>
      ),
    } as unknown as ColumnDef<typeof rowPinningFeatures, Person>,
    { accessorKey: 'status', header: 'Status' },
    {
      id: 'pin',
      header: 'Pin row',
      cell: ({ row }: { row: PinnedRow }) => (
        <span className="inline-flex gap-1">
          <Button size="sm" variant="outline" onClick={() => row.pin('top')}>
            Top
          </Button>
          <Button size="sm" variant="outline" onClick={() => row.pin(false)}>
            Center
          </Button>
          <Button size="sm" variant="outline" onClick={() => row.pin('bottom')}>
            Bottom
          </Button>
        </span>
      ),
    } as unknown as ColumnDef<typeof rowPinningFeatures, Person>,
  ]
  const table = useDataGridTable({
    features: rowPinningFeatures,
    data: people7,
    columns,
    getRowId: (row) => row.id,
    initialState: { rowPinning: { top: ['u-006'], bottom: ['u-002'] } },
  })
  return (
    <DataGridDemoSection
      title="Row pinning"
      description="Pinned rows are opaque layers above the scrollable center region. Their edge shadow appears only at the boundary, and the controls can add more rows to either region."
    >
      <DemoBranch title="Top, scrollable center and bottom">
        <DataGrid table={table} className={{ viewport: 'max-h-56' }} />
      </DemoBranch>
    </DataGridDemoSection>
  )
}
