// packages/@fex-design/react/src/primitive/textarea/textarea.tsx
import { textareaClassName } from '@fex-design/styles/textarea'
import { cn } from '@fex/utils'
import type { ComponentProps } from 'react'

export function Textarea({ className, ...props }: ComponentProps<'textarea'>) {
  return <textarea data-slot="textarea" className={cn(textareaClassName, className)} {...props} />
}

// packages/@fex-design/svelte/src/primitive/textarea/textarea.svelte
<script lang="ts">
  import { textareaClassName } from '@fex-design/styles/textarea'
  import { cn } from '@fex/utils'
  import type { HTMLTextareaAttributes } from 'svelte/elements'
  interface Props extends Omit<HTMLTextareaAttributes, 'class'> { class?: string }
  let { class: className, ...rest }: Props = $props()
  const classList = $derived(cn(textareaClassName, className))
</script>
<textarea {...rest} data-slot="textarea" class={classList}></textarea>
