// packages/@fex-design/svelte/src/primitive/pagination/pagination-content.svelte
<script lang="ts">
  import { paginationContentClassName } from '@fex-design/styles/pagination'
  import { cn } from '@fex/utils'
  import type { Snippet } from 'svelte'
  import type { HTMLAttributes } from 'svelte/elements'
  interface Props extends Omit<HTMLAttributes<HTMLUListElement>, 'class'> { class?: string; children?: Snippet }
  let { class: className, children, ...rest }: Props = $props()
  const classList = $derived(cn(paginationContentClassName, className))
</script>
<ul {...rest} data-slot="pagination-content" class={classList}>{@render children?.()}</ul>

// packages/@fex-design/vue/src/primitive/pagination/pagination-content.vue
﻿<script setup lang="ts">
import { paginationContentClassName } from '@fex-design/styles/pagination'
import { cn } from '@fex/utils'

defineOptions({ inheritAttrs: false })
const props = defineProps<{ class?: string | undefined }>()
</script>

<template>
  <ul
    v-bind="$attrs"
    data-slot="pagination-content"
    :class="cn(paginationContentClassName, props.class)"
  >
    <slot />
  </ul>
</template>
