// packages/components/solid/src/ui/card/card.tsx
import type { JSX, ParentProps } from 'solid-js'
import { Show, splitProps } from 'solid-js'
import {
  Card as PrimitiveCard,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from '../../primitive/card/card'

type SectionClass = {
  header?: string
  content?: string
  footer?: string
}

type SectionStyle = {
  header?: JSX.CSSProperties
  content?: JSX.CSSProperties
  footer?: JSX.CSSProperties
}

export interface CardProps extends ParentProps<Omit<JSX.HTMLAttributes<HTMLDivElement>, 'class' | 'style' | 'title'>> {
  title?: JSX.Element
  description?: JSX.Element
  footer?: JSX.Element
  class?: SectionClass
  style?: SectionStyle
}

export function Card(props: CardProps) {
  const [local, rest] = splitProps(props, ['title', 'description', 'footer', 'class', 'style', 'children'])

  return (
    <PrimitiveCard {...rest}>
      <Show when={local.title || local.description}>
        <CardHeader class={local.class?.header} style={local.style?.header}>
          <Show when={local.title}>
            <CardTitle>{local.title}</CardTitle>
          </Show>
          <Show when={local.description}>
            <CardDescription>{local.description}</CardDescription>
          </Show>
        </CardHeader>
      </Show>
      <CardContent class={local.class?.content} style={local.style?.content}>
        {local.children}
      </CardContent>
      <Show when={local.footer}>
        <CardFooter class={local.class?.footer} style={local.style?.footer}>
          {local.footer}
        </CardFooter>
      </Show>
    </PrimitiveCard>
  )
}

export default Card

// packages/components/svelte/src/ui/card/card.svelte
<script lang="ts">
  import type { Snippet } from 'svelte'
  import type { HTMLAttributes } from 'svelte/elements'
  import PrimitiveCard from '../../primitive/card/card.svelte'
  import CardContent from '../../primitive/card/card-content.svelte'
  import CardDescription from '../../primitive/card/card-description.svelte'
  import CardFooter from '../../primitive/card/card-footer.svelte'
  import CardHeader from '../../primitive/card/card-header.svelte'
  import CardTitle from '../../primitive/card/card-title.svelte'

  type SectionClass = {
    header?: string
    content?: string
    footer?: string
  }

  type SectionStyle = {
    header?: HTMLAttributes<HTMLDivElement>['style']
    content?: HTMLAttributes<HTMLDivElement>['style']
    footer?: HTMLAttributes<HTMLDivElement>['style']
  }

  interface CardProps extends Omit<HTMLAttributes<HTMLDivElement>, 'class' | 'style' | 'title'> {
    title?: Snippet | string
    description?: Snippet | string
    footer?: Snippet | string
    class?: SectionClass
    style?: SectionStyle
    children?: Snippet
  }

  let { title, description, footer, class: className, style, children, ...rest }: CardProps = $props()

  const headerProps = $derived({
    ...(className?.header ? { class: className.header } : {}),
    ...(style?.header ? { style: style.header } : {}),
  })
  const contentProps = $derived({
    ...(className?.content ? { class: className.content } : {}),
    ...(style?.content ? { style: style.content } : {}),
  })
  const footerProps = $derived({
    ...(className?.footer ? { class: className.footer } : {}),
    ...(style?.footer ? { style: style.footer } : {}),
  })
</script>

<PrimitiveCard {...rest}>
  {#if title || description}
    <CardHeader {...headerProps}>
      {#if title}
        <CardTitle>
          {#if typeof title === 'function'}
            {@render title()}
          {:else}
            {title}
          {/if}
        </CardTitle>
      {/if}
      {#if description}
        <CardDescription>
          {#if typeof description === 'function'}
            {@render description()}
          {:else}
            {description}
          {/if}
        </CardDescription>
      {/if}
    </CardHeader>
  {/if}
  <CardContent {...contentProps}>
    {@render children?.()}
  </CardContent>
  {#if footer}
    <CardFooter {...footerProps}>
      {#if typeof footer === 'function'}
        {@render footer()}
      {:else}
        {footer}
      {/if}
    </CardFooter>
  {/if}
</PrimitiveCard>
