// packages/components/vue/src/primitive/sortable/sortable-overlay.vue
<script setup lang="ts">
import { sortableItemClassName } from '@fex/components-styles/sortable'
import { cn } from '@fex/utils'
import { useAttrs } from 'vue'
import { useSortableContext } from './context'
defineOptions({ inheritAttrs: false })
const props = defineProps<{ class?: string }>()
const attrs = useAttrs()
const { sortable } = useSortableContext()
</script>
<template><Teleport to="body"><div v-if="sortable.snapshot.value.activeId" v-bind="attrs" data-sortable-overlay="" :class="cn(sortableItemClassName, 'bg-card text-foreground opacity-100 shadow-xl ring-1 ring-border/70', props.class)" :style="sortable.getOverlayStyle()"><slot :active-id="sortable.snapshot.value.activeId" :style="sortable.getOverlayStyle()" /></div></Teleport></template>

// packages/components/svelte/src/primitive/sortable/sortable-overlay.svelte
<script lang="ts">
  import { cn } from '@fex/utils'
  import type { Snippet } from 'svelte'
  import type { HTMLAttributes } from 'svelte/elements'
  import { getContext } from 'svelte'
  import { sortableContextKey, type SortableContext, type SortableOverlaySnippet } from './sortable-context'

  interface SortableOverlayProps extends Omit<HTMLAttributes<HTMLDivElement>, 'class' | 'children'> {
    class?: string
    children?: Snippet<SortableOverlaySnippet>
  }

  let { class: className, children, ...rest }: SortableOverlayProps = $props()
  const { sortable, snapshot, styleToString } = getContext<SortableContext>(sortableContextKey)
  const overlayStyle = $derived(styleToString((snapshot().motionVersion, sortable.getOverlayStyle())))
  const activeId = $derived(snapshot().activeId)
</script>

{#if activeId}
  <div
    {...rest}
    data-sortable-overlay
    class={cn(
      'rounded-md border border-border bg-card text-foreground opacity-100 shadow-xl ring-1 ring-border/70',
      className,
    )}
    style={overlayStyle}
  >
    {@render children?.({ activeId, style: overlayStyle })}
  </div>
{/if}
