// packages/components/react/src/primitive/input/input.tsx
import { inputClassName } from '@fex/components-styles/input'
import { cn } from '@fex/utils'
import type { ComponentProps } from 'react'

export function Input({ className, type, ...props }: ComponentProps<'input'>) {
  return (
    <input type={type} data-slot="input" className={cn(inputClassName, className)} {...props} />
  )
}

// packages/components/vue/src/primitive/input/input.vue
<script setup lang="ts">
import { inputClassName } from '@fex/components-styles/input'
import { cn } from '@fex/utils'
import { useAttrs } from 'vue'

defineOptions({ name: 'Input', inheritAttrs: false })

const attrs = useAttrs()
</script>

<template>
  <input v-bind="attrs" data-slot="input" :class="cn(inputClassName, attrs.class as string | undefined)">
</template>
