// apps/vue-admin/src/pages/Select/local-search-demo.vue
<script setup lang="ts">
import { defaultSelectFilterOption } from '@fex/components-core/select/filter-options'
import { SelectContent, SelectRoot, SelectTrigger } from '@fex/components-vue/primitive/select'
import { frameworkOptions } from './data'
import Demo from './demo-section.vue'
</script>
<template>
  <Demo
    title="Local search"
    description="filterOption filters options locally and search still receives every keyword."
    ><SelectRoot show-search :options="frameworkOptions" :filter-option="defaultSelectFilterOption"
      ><SelectTrigger placeholder="搜索选项" /><SelectContent /></SelectRoot
  ></Demo>
</template>

// apps/solid-admin/src/pages/Select/local-search-demo.tsx
import { defaultSelectFilterOption } from '@fex/components-core/select/filter-options'
import { SelectContent, SelectRoot, SelectTrigger } from '@fex/components-solid/primitive/select'
import { frameworkOptions } from './data'
import { SelectDemoSection as Demo } from './demo-section'
export function LocalSearchDemo() {
  return (
    <Demo
      title="Local search"
      description="filterOption filters locally and onSearch still receives every keyword."
    >
      <SelectRoot showSearch filterOption={defaultSelectFilterOption} options={frameworkOptions}>
        <SelectTrigger placeholder="搜索选项" />
        <SelectContent />
      </SelectRoot>
    </Demo>
  )
}
