// apps/vue-app/src/pages/Anchor/horizontal-demo.vue
<script setup lang="ts">
import { Anchor } from '@fex-design/vue/primitive/anchor'
import Card from '@fex-design/vue/ui/card'
import { ref } from 'vue'
const container = ref<HTMLElement>()
const items = [
  { key: 'horizontal-one', title: 'Overview', target: '#horizontal-overview' },
  { key: 'horizontal-two', title: 'API', target: '#horizontal-api' },
  { key: 'horizontal-three', title: 'Examples', target: '#horizontal-examples' },
]
</script>
<template><Card title="Horizontal" description="Horizontal anchors use the same tracking behavior."><Anchor :items="items" orientation="horizontal" :active-offset="80" :container="() => container ?? window" /><div ref="container" class="mt-space-md h-40 overflow-y-auto rounded-md border border-border p-space-lg"><section id="horizontal-overview" class="min-h-32">Overview content</section><section id="horizontal-api" class="min-h-32">API content</section><section id="horizontal-examples" class="min-h-32">Examples content</section></div></Card></template>

// apps/angular-app/src/pages/anchor/horizontal-demo.component.ts
import { ChangeDetectionStrategy, Component, ElementRef, viewChild } from '@angular/core'
import { Anchor } from '@fex-design/angular/primitive/anchor'
import Card from '@fex-design/angular/ui/card'
@Component({ selector: 'fex-anchor-horizontal-demo', standalone: true, imports: [Card, Anchor], templateUrl: './horizontal-demo.component.html', changeDetection: ChangeDetectionStrategy.OnPush })
export class HorizontalDemo {
  protected readonly container = viewChild<ElementRef<HTMLElement>>('container')
  protected readonly getContainer = () => this.container()?.nativeElement ?? window
  protected readonly items = [{ key: 'horizontal-one', title: 'Overview', target: '#horizontal-overview' }, { key: 'horizontal-two', title: 'API', target: '#horizontal-api' }, { key: 'horizontal-three', title: 'Examples', target: '#horizontal-examples' }]
}
