// apps/react-admin/src/pages/DataGrid/demo-section.tsx
import { Card } from '@fex/components-react/ui/card'
import type { ReactNode } from 'react'

export function DataGridDemoSection({
  title,
  description,
  children,
}: {
  title: string
  description: string
  children: ReactNode
}) {
  return <Card title={title} description={description}>{children}</Card>
}

export function DemoBranch({ title, children }: { title: string; children: ReactNode }) {
  return (
    <section className="space-y-space-sm">
      <h3 className="text-sm font-medium text-foreground">{title}</h3>
      {children}
    </section>
  )
}

// apps/solid-admin/src/pages/DataGrid/demo-section.tsx
import { Card } from '@fex/components-solid/ui/card'
import type { ParentProps } from 'solid-js'

export function DataGridDemoSection(props: ParentProps<{ title: string; description: string }>) {
  return (
    <Card title={props.title} description={props.description}>
      {props.children}
    </Card>
  )
}

export function DemoBranch(props: ParentProps<{ title: string }>) {
  return (
    <section class="space-y-space-sm">
      <h3 class="text-sm font-medium text-foreground">{props.title}</h3>
      {props.children}
    </section>
  )
}
