// apps/react-admin/src/pages/Tree/dnd-demo.tsx
import { createTreeController } from '@fex-design/core/tree/create-tree-controller'
import { dndFeature, expansionFeature } from '@fex-design/core'
import type { TreeController } from '@fex-design/core/tree/types'
import {
  TreeDropIndicator,
  TreeItem,
  TreeRoot,
  TreeTitle,
  TreeTrigger,
  TreeViewport,
} from '@fex-design/react/primitive/tree'
import { useTreeDndItem } from '@fex-design/react/primitive/tree/use-tree-dnd-item'
import { useState } from 'react'
import {
  departmentFieldNames,
  departmentTreeData,
  isDepartmentLeaf,
  type DepartmentNode,
} from './data'
import { TreeDemoSection } from './demo-section'

function DraggableTreeRow({
  controller,
  itemKey,
}: {
  controller: TreeController<DepartmentNode>
  itemKey: string | number
}) {
  const dnd = useTreeDndItem({ tree: controller, itemKey })
  return (
    <TreeItem<DepartmentNode> itemKey={itemKey}>
      {({ item, itemProps }) => (
        <div
          {...itemProps}
          {...dnd.itemProps}
          className={itemProps.className}
          style={{ ...itemProps.style, ...dnd.itemProps.style }}
        >
          <TreeTrigger itemKey={item.key} />
          <TreeTitle>{item.node.name}</TreeTitle>
          <TreeDropIndicator item={item} intent={dnd.intent} style={dnd.dropIndicatorStyle} />
        </div>
      )}
    </TreeItem>
  )
}

export function TreeDndDemo() {
  const [controller] = useState(() =>
    createTreeController<DepartmentNode>({
      treeData: departmentTreeData,
      fieldNames: departmentFieldNames,
      isLeaf: isDepartmentLeaf,
      features: [
        expansionFeature({ defaultExpandedKeys: ['company', 'engineering', 'product'] }),
        dndFeature(),
      ],
    }),
  )

  return (
    <TreeDemoSection
      title="Optional drag and drop feature"
      description="This example uses a custom 24px indent. Vertical movement chooses the row; moving the dragged row one indent into it makes it a child."
    >
      <TreeRoot
        controller={controller}
        indent={24}
        className="max-w-xl rounded-md border border-border bg-background p-space-sm"
      >
        <TreeViewport>
          {(item) => <DraggableTreeRow key={item.key} controller={controller} itemKey={item.key} />}
        </TreeViewport>
      </TreeRoot>
    </TreeDemoSection>
  )
}

// apps/vue-admin/src/pages/Tree/dnd-demo.vue
<script setup lang="ts">
import { dndFeature, expansionFeature } from '@fex-design/core'
import { createTreeController } from '@fex-design/core/tree/create-tree-controller'
import { TreeRoot, TreeViewport } from '@fex-design/vue/primitive/tree'
import Card from '@fex-design/vue/ui/card'
import DndTreeRow from './dnd-tree-row.vue'
import {
  departmentFieldNames,
  departmentTreeData,
  isDepartmentLeaf,
  type DepartmentNode,
} from './data'
const controller = createTreeController<DepartmentNode>({
  treeData: departmentTreeData,
  fieldNames: departmentFieldNames,
  isLeaf: isDepartmentLeaf,
  features: [
    expansionFeature({ defaultExpandedKeys: ['company', 'engineering', 'product'] }),
    dndFeature(),
  ],
})
</script>
<template>
  <Card
    title="Optional drag and drop feature"
    description="This example uses a custom 24px indent. Vertical edge zones reorder; in the middle zone, dropping in the target row's trailing half makes the source a child, while moving left can outdent it."
    ><TreeRoot
      :controller="controller"
      :indent="24"
      class="max-w-xl rounded-md border border-border bg-background p-space-sm"
      ><TreeViewport v-slot="{ item }"
        ><DndTreeRow
          :key="item.key"
          :controller="controller"
          :item-key="item.key" /></TreeViewport></TreeRoot
  ></Card>
</template>
