// apps/svelte-admin/src/routes/tree/dnd-tree-row.svelte
<script lang="ts">
  import type { TreeController, TreeKey } from '@fex/components-core/tree/types'
  import { TreeItem, TreeTitle, TreeTrigger } from '@fex/components-svelte/primitive/tree'
  import { treeDndItemAction } from '@fex/components-svelte/primitive/tree/tree-dnd-item'
  import type { DepartmentNode } from './data'

  let { controller, itemKey, indent = 24 }: { controller: TreeController<DepartmentNode>; itemKey: TreeKey; indent?: number } = $props()
</script>

<TreeItem controller={controller} {itemKey}>
  {#snippet children(state)}
    <div {...state.itemProps} use:treeDndItemAction={{ tree: controller, itemKey, indent }}>
      <TreeTrigger itemKey={state.item.key} />
      <TreeTitle>{String(state.item.node.name)}</TreeTitle>
    </div>
  {/snippet}
</TreeItem>

// apps/vue-admin/src/pages/Tree/dnd-tree-row.vue
<script setup lang="ts">
import type { TreeController, TreeKey } from '@fex/components-core/tree/types'
import { TreeItem, TreeTitle, TreeTrigger } from '@fex/components-vue/primitive/tree'
import { useTreeDndItem } from '@fex/components-vue/primitive/tree/use-tree-dnd-item'
import type { ComponentPublicInstance, StyleValue } from 'vue'
import type { DepartmentNode } from './data'
const props = defineProps<{ controller: TreeController<DepartmentNode>; itemKey: TreeKey }>()
const { itemProps: dndItemProps, setItemRef } = useTreeDndItem({
  tree: props.controller,
  itemKey: props.itemKey,
})
function bindItemRef(value: Element | ComponentPublicInstance | null) {
  setItemRef(value instanceof window.Element ? value : null)
}
function getStyle(value: Record<string, unknown>): StyleValue {
  return value.style as StyleValue
}
</script>
<template>
  <!-- @vue-generic {DepartmentNode} --><TreeItem
    :item-key="props.itemKey"
    v-slot="{ item, itemProps }"
    ><div
      v-bind="itemProps"
      :ref="bindItemRef"
      :data-droppable-id="dndItemProps['data-droppable-id']"
      :data-over="dndItemProps['data-over']"
      :data-can-drop="dndItemProps['data-can-drop']"
      :data-drop-edge="dndItemProps['data-drop-edge']"
      :data-drop-position="dndItemProps['data-drop-position']"
      :data-dragging="dndItemProps['data-dragging']"
      :data-dnd-enabled="dndItemProps['data-dnd-enabled']"
      :style="[getStyle(itemProps), dndItemProps.style]"
    >
      <TreeTrigger :item-key="item.key" /><TreeTitle>{{ item.node.name }}</TreeTitle>
    </div></TreeItem
  >
</template>
