// packages/@fex-design/svelte/src/primitive/button/button-group.svelte
<script lang="ts">
  import { buttonGroupClassName, type ButtonGroupStyleProps } from '@fex-design/styles/button'
  import { cn } from '@fex/utils'
  import type { Snippet } from 'svelte'
  import type { HTMLAttributes } from 'svelte/elements'
  interface Props extends Omit<HTMLAttributes<HTMLDivElement>, 'class' | 'style'>, ButtonGroupStyleProps { class?: string; style?: string; spacing?: number | string; children?: Snippet }
  let { class: className, style, spacing = 0, orientation = 'horizontal', children, ...rest }: Props = $props()
  const gap = $derived(typeof spacing === 'number' ? `${spacing}px` : spacing)
</script>
<div {...rest} role="group" data-slot="button-group" data-orientation={orientation} class={cn(buttonGroupClassName({ orientation, connected: spacing === 0 }), className)} style={`gap:${gap};${style ?? ''}`}>{@render children?.()}</div>

// packages/@fex-design/vue/src/primitive/button/button-group.vue
<script setup lang="ts">
import { buttonGroupClassName } from '@fex-design/styles/button'
import { cn } from '@fex/utils'
import { computed, useAttrs } from 'vue'

defineOptions({ inheritAttrs: false })
const props = withDefaults(defineProps<{
  orientation?: 'horizontal' | 'vertical'
  spacing?: number | string
}>(), { orientation: 'horizontal', spacing: 0 })
const attrs = useAttrs()
const className = computed(() => cn(buttonGroupClassName({
  orientation: props.orientation,
  connected: props.spacing === 0,
}), attrs.class as string | undefined))
const style = computed(() => ({
  ...(attrs.style as Record<string, unknown> | undefined),
  gap: typeof props.spacing === 'number' ? `${props.spacing}px` : props.spacing,
}))
</script>

<template>
  <div v-bind="{ ...attrs, class: undefined, style: undefined }" role="group" data-slot="button-group" :data-orientation="props.orientation" :class="className" :style="style"><slot /></div>
</template>
