// apps/react-admin/src/pages/AspectRatio/index.tsx
import { LandscapeDemo } from './landscape-demo'
import { PortraitDemo } from './portrait-demo'
import { SquareDemo } from './square-demo'
export function AspectRatioPage() {
  return (
    <main className="grid gap-space-xl p-page-padding">
      <LandscapeDemo />
      <SquareDemo />
      <PortraitDemo />
    </main>
  )
}

// apps/vue-admin/src/pages/AspectRatio/index.vue
<script setup lang="ts">
import LandscapeDemo from './landscape-demo.vue'
import PortraitDemo from './portrait-demo.vue'
import SquareDemo from './square-demo.vue'
</script>
<template>
  <main class="grid gap-space-xl p-page-padding">
    <LandscapeDemo /><SquareDemo /><PortraitDemo />
  </main>
</template>
