// apps/react-app/src/pages/Select/tags-demo.tsx
import { defaultSelectFilterOption } from '@fex-design/core/select/filter-options'
import {
  SelectContent,
  SelectList,
  SelectRoot,
  SelectTrigger,
} from '@fex-design/react/primitive/select'
import { frameworkOptions } from './data'
import { SelectDemoSection } from './demo-section'

export function TagsDemo() {
  return (
    <SelectDemoSection
      title="Tags"
      description="Type a new value and press Enter, or choose an existing option."
    >
      <SelectRoot
        mode="tags"
        filterOption={defaultSelectFilterOption}
        options={frameworkOptions}
        defaultValue={['react']}
      >
        <SelectTrigger placeholder="请输入或选择标签" />
        <SelectContent>
          <SelectList />
        </SelectContent>
      </SelectRoot>
    </SelectDemoSection>
  )
}

// apps/vue-app/src/pages/Select/tags-demo.vue
<script setup lang="ts">
import { defaultSelectFilterOption } from '@fex-design/core/select/filter-options'
import { SelectContent, SelectRoot, SelectTrigger } from '@fex-design/vue/primitive/select'
import { frameworkOptions } from './data'
import Demo from './demo-section.vue'
</script>
<template>
  <Demo title="Tags" description="Type a new value and press Enter, or choose an existing option."
    ><SelectRoot
      mode="tags"
      :filter-option="defaultSelectFilterOption"
      :options="frameworkOptions"
      :default-value="['react']"
      ><SelectTrigger placeholder="请输入或选择标签" /><SelectContent /></SelectRoot
  ></Demo>
</template>
