// packages/components/react/src/button/button.tsx
import {
  buttonClassName,
  buttonIconClassName,
  buttonSpinnerClassName,
  type ButtonStyleProps,
} from "@fex/components-styles/button";
import type { ButtonHTMLAttributes, ReactNode, Ref } from "react";

export interface ButtonProps extends ButtonHTMLAttributes<HTMLButtonElement>, ButtonStyleProps {
  ref?: Ref<HTMLButtonElement>;
  icon?: ReactNode;
  iconPlacement?: "start" | "end";
  loading?: boolean;
}

const LoadingIcon = () => (
  <svg
    className={buttonSpinnerClassName}
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth={2}
    strokeLinecap="round"
    strokeLinejoin="round"
    aria-hidden="true"
  >
    <path d="M21 12a9 9 0 1 1-6.219-8.56" />
  </svg>
);
export function Button({
  className,
  variant = "default",
  size = "default",
  effect,
  icon,
  iconPlacement = "start",
  loading = false,
  disabled,
  children,
  ref,
  ...props
}: ButtonProps) {
  const isDisabled = disabled || loading;
  const iconNode = loading ? <LoadingIcon /> : icon;

  return (
    <button
      {...props}
      ref={ref}
      className={buttonClassName({ variant, size, effect, className })}
      data-slot="button"
      data-variant={variant}
      data-size={size}
      data-effect={effect}
      data-loading={loading ? "true" : undefined}
      disabled={isDisabled}
    >
      {iconPlacement === "start" && iconNode ? (
        <span
          className={buttonIconClassName({ placement: "start", effect })}
          data-icon="inline-start"
        >
          {iconNode}
        </span>
      ) : null}
      {children}
      {iconPlacement === "end" && iconNode ? (
        <span
          className={buttonIconClassName({ placement: "end", effect })}
          data-icon="inline-end"
        >
          {iconNode}
        </span>
      ) : null}
    </button>
  );
}

// packages/components/solid/src/button/button.tsx
import {
  buttonClassName,
  buttonIconClassName,
  buttonSpinnerClassName,
  type ButtonStyleProps,
} from '@fex/components-styles/button'
import type { JSX, ParentProps } from 'solid-js'
import { Show, splitProps } from 'solid-js'

export interface ButtonProps
  extends ParentProps<Omit<JSX.ButtonHTMLAttributes<HTMLButtonElement>, 'disabled'>>,
    ButtonStyleProps {
  icon?: JSX.Element
  iconPlacement?: 'start' | 'end'
  loading?: boolean
  disabled?: boolean
}

export function Button(props: ButtonProps) {
  const [local, rest] = splitProps(props, [
    'class',
    'variant',
    'size',
    'effect',
    'icon',
    'iconPlacement',
    'loading',
    'disabled',
    'children',
    'type',
  ])

  const variant = () => local.variant ?? 'default'
  const size = () => local.size ?? 'default'
  const iconPlacement = () => local.iconPlacement ?? 'start'
  const isLoading = () => local.loading === true
  const isDisabled = () => local.disabled === true || isLoading()
  const buttonType = () => local.type ?? 'button'
  const iconNode = () =>
    isLoading() ? <LoadingIcon /> : local.icon

  return (
    <button
      {...rest}
      type={buttonType()}
      class={buttonClassName({
        variant: variant(),
        size: size(),
        effect: local.effect,
        className: local.class,
      })}
      data-slot="button"
      data-variant={variant()}
      data-size={size()}
      data-effect={local.effect}
      data-loading={isLoading() ? 'true' : undefined}
      disabled={isDisabled()}
    >
      <Show when={iconPlacement() === 'start' && iconNode()}>
        <span
          class={buttonIconClassName({ placement: 'start', effect: local.effect })}
          data-icon="inline-start"
        >
          {iconNode()}
        </span>
      </Show>
      {local.children}
      <Show when={iconPlacement() === 'end' && iconNode()}>
        <span
          class={buttonIconClassName({ placement: 'end', effect: local.effect })}
          data-icon="inline-end"
        >
          {iconNode()}
        </span>
      </Show>
    </button>
  )
}

function LoadingIcon() {
  return (
    <svg
      class={buttonSpinnerClassName}
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      stroke-width={2}
      stroke-linecap="round"
      stroke-linejoin="round"
      aria-hidden="true"
    >
      <path d="M21 12a9 9 0 1 1-6.219-8.56" />
    </svg>
  )
}
