// packages/@fex-design/react/src/primitive/data-table/data-table-checkbox.tsx
import type { CheckboxCheckedState } from '@fex-design/core/checkbox/types'
import type { ButtonHTMLAttributes } from 'react'
import { Checkbox } from '../../ui/checkbox/checkbox'

interface DataTableCheckboxProps extends Omit<
  ButtonHTMLAttributes<HTMLButtonElement>,
  'onChange' | 'checked' | 'defaultChecked'
> {
  checked: CheckboxCheckedState
  onCheckedChange: (checked: CheckboxCheckedState) => void
}

export function DataTableCheckbox({ checked, onCheckedChange, ...props }: DataTableCheckboxProps) {
  return <Checkbox {...props} checked={checked} onCheckedChange={onCheckedChange} />
}

// packages/@fex-design/vue/src/primitive/data-table/data-table-checkbox.vue
<script setup lang="ts">
import type { CheckboxCheckedState } from '@fex-design/core/checkbox/types'
import Checkbox from '../../ui/checkbox/checkbox.vue'
const props = defineProps<{
  checked: CheckboxCheckedState
  disabled?: boolean
  ariaLabel?: string
}>()
const emit = defineEmits<{ change: [value: CheckboxCheckedState] }>()
</script>
<template>
  <Checkbox
    :checked="props.checked"
    :disabled="props.disabled"
    :aria-label="props.ariaLabel"
    @checked-change="(value) => emit('change', value)"
  />
</template>
