// packages/components/svelte/src/primitive/scrollbar/scrollbar-thumb.svelte
<script lang="ts">
  import type { ScrollbarAxis } from '@fex/components-core/scrollbar/types'; import { scrollbarThumbClassName } from '@fex/components-styles/scrollbar'; import { cn } from '@fex/utils'; import type { HTMLAttributes } from 'svelte/elements'
  interface Props extends HTMLAttributes<HTMLDivElement> { axis: ScrollbarAxis }
  let { axis, class: className, ...rest }: Props = $props()
</script>
<div {...rest} data-slot="scrollbar-thumb" class={cn(scrollbarThumbClassName({ axis }), className)}></div>

// packages/components/vue/src/primitive/scrollbar/scrollbar-thumb.vue
<script setup lang="ts">
import type { ScrollbarAxis } from '@fex/components-core/scrollbar/types'
import { scrollbarThumbClassName } from '@fex/components-styles/scrollbar'
import { cn } from '@fex/utils'
import { useAttrs } from 'vue'
defineOptions({ inheritAttrs: false }); const props = defineProps<{ axis: ScrollbarAxis }>(); const attrs = useAttrs()
</script>
<template><div v-bind="attrs" data-slot="scrollbar-thumb" :class="cn(scrollbarThumbClassName({ axis: props.axis }), attrs.class as string | undefined)" /></template>
