// packages/components/vue/src/primitive/drawer/drawer-content.vue
<script setup lang="ts">
import { drawerContentClassName } from '@fex/components-styles/drawer'
import { cn } from '@fex/utils'
import { computed, onBeforeUnmount } from 'vue'
import { useResize } from '../../composables/use-resize'
import { useDrawerContext } from './context'

const props = defineProps<{ class?: string; size?: string | number; style?: Record<string, string> }>()
const context = useDrawerContext('DrawerContent')
const { drawer, snapshot, placement } = context
const horizontal = computed(() => placement.value === 'left' || placement.value === 'right')
const edge = computed(() => ({ left: 'right', right: 'left', top: 'bottom', bottom: 'top' }[placement.value ?? 'right'] as 'top' | 'right' | 'bottom' | 'left'))
const numericSize = typeof props.size === 'number'
  ? props.size
  : Number.parseInt(({ sm: '320', md: '400', lg: '560', xl: '720', full: '100' } as Record<string, string>)[props.size ?? 'md'] ?? props.size ?? '400', 10) || 400
const resize = useResize({
  defaultRect: { x: 0, y: 0, width: horizontal.value ? numericSize : 0, height: horizontal.value ? 0 : numericSize },
  edges: [edge.value],
  ...(horizontal.value
    ? { minWidth: context.resizeOptions.minSize, maxWidth: context.resizeOptions.maxSize }
    : { minHeight: context.resizeOptions.minSize, maxHeight: context.resizeOptions.maxSize }),
  disabled: !context.resizeOptions.resizable,
  onResize(rect) {
    context.resizeOptions.onSizeChange?.(horizontal.value ? rect.width : rect.height)
  },
})
context.resize = resize
const sizeValue = computed(() => typeof props.size === 'number' ? `${props.size}px` : ({ sm: '320px', md: '400px', lg: '560px', xl: '720px', full: '100%' } as Record<string, string>)[props.size ?? 'md'] ?? props.size ?? '400px')

function setContent(element: HTMLDivElement | null) {
  drawer.setLayerElement(element)
  resize.setTarget(element)
}
function keydown(event: KeyboardEvent) {
  if (event.key === 'Escape') drawer.dismiss.escapeKey({ target: event.target, currentTarget: event.currentTarget, event })
}
onBeforeUnmount(() => {
  drawer.setLayerElement(null)
  resize.setTarget(null)
})
</script>

<template>
  <div v-if="snapshot.mounted" :ref="setContent" v-bind="$attrs" role="dialog" tabindex="-1" data-slot="drawer-content" :data-placement="placement" :data-state="snapshot.open ? 'open' : 'closed'" :data-phase="snapshot.phase" :aria-modal="true" :class="cn(drawerContentClassName({ placement }), props.class)" :style="{ '--drawer-size': sizeValue, ...props.style }" @keydown="keydown"><slot /></div>
</template>

// packages/components/svelte/src/primitive/drawer/drawer-content.svelte
<script lang="ts">
  import { drawerContentClassName } from '@fex/components-styles/drawer'
  import type { DrawerPlacement, DrawerSize } from '@fex/components-core/drawer/create-drawer-controller'
  import type { HTMLAttributes } from 'svelte/elements'
  import { resizeAction } from '../../actions/resize'
  import { useDrawer } from './drawer-context'

  interface Props extends Omit<HTMLAttributes<HTMLDivElement>, 'class'> {
    children?: import('svelte').Snippet
    class?: string
    size?: DrawerSize
  }
  let { children, class: className = '', size, ...rest }: Props = $props()
  const context = useDrawer('DrawerContent')
  const { drawer, snapshot } = context
  const sizes: Record<string, string> = { sm: '320px', md: '400px', lg: '560px', xl: '720px', full: '100%' }
  const currentPlacement = $derived(context.placement() as DrawerPlacement)
  const configuredSize = $derived(size ?? context.size() ?? 'md')
  const numericSize = $derived(typeof configuredSize === 'number' ? configuredSize : Number.parseInt(sizes[configuredSize] ?? configuredSize, 10) || 400)
  const edge = $derived(({ left: 'right', right: 'left', top: 'bottom', bottom: 'top' } as const)[currentPlacement])
  function contentAction(node: HTMLDivElement) {
    drawer.setLayerElement(node)
    return { destroy: () => drawer.setLayerElement(null) }
  }
</script>

{#if $snapshot.mounted}
  <div
    {...rest}
    use:contentAction
    use:resizeAction={{
      applyStyle: false,
      edge,
      edges: [edge],
      disabled: !context.resizable(),
      rect: { x: 0, y: 0, width: currentPlacement === 'left' || currentPlacement === 'right' ? numericSize : 0, height: currentPlacement === 'top' || currentPlacement === 'bottom' ? numericSize : 0 },
      minWidth: currentPlacement === 'left' || currentPlacement === 'right' ? context.minSize() : undefined,
      maxWidth: currentPlacement === 'left' || currentPlacement === 'right' ? context.maxSize() : undefined,
      minHeight: currentPlacement === 'top' || currentPlacement === 'bottom' ? context.minSize() : undefined,
      maxHeight: currentPlacement === 'top' || currentPlacement === 'bottom' ? context.maxSize() : undefined,
      onResize: (rect) => context.onSizeChange()?.(currentPlacement === 'left' || currentPlacement === 'right' ? rect.width : rect.height),
    }}
    role="dialog"
    tabindex="-1"
    data-slot="drawer-content"
    data-placement={currentPlacement}
    data-state={$snapshot.open ? 'open' : 'closed'}
    data-phase={$snapshot.phase}
    aria-modal="true"
    class={`${drawerContentClassName({ placement: currentPlacement })} ${className}`}
    style={`--drawer-size:${typeof configuredSize === 'number' ? `${configuredSize}px` : sizes[configuredSize] ?? configuredSize}`}
    onkeydown={(event) => {
      if (event.key === 'Escape') drawer.dismiss.escapeKey({ target: event.target, currentTarget: event.currentTarget, event })
    }}
  >
    {@render children?.()}
  </div>
{/if}
